FalconView: src/guiLib/util/ally3d.cpp File Reference
ally3d.cpp File Reference
#include <ally3d.h>
#include <graphicfactory.h>
#include <occtviewer.h>
#include <valuemanager.h>
#include <guicore.h>
#include <AIS_ColoredShape.hxx>
#include <BRepPrimAPI_MakeCone.hxx>
Functions
static Quantity_Color convertColor (const QColor &c)
Function Documentation
convertColor()
static Quantity_Color convertColor (const QColor & c) static
Referenced by Ally3D::setCurSegColor(), Ally3D::setFeedColor(), Ally3D::setLimitsColor(), Ally3D::setOldSegColor(), and Ally3D::setWorkPieceColor().