FalconView: src/app/LC/canonif.cpp File Reference
canonif.cpp File Reference
#include <canonif.h>
#include <canonifsettings.h>
#include <tooltable.h>
#include <lcproperties.h>
#include <axismask.h>
#include <stupidtoolchangerif.h>
#include <core.h>
#include <graphicfactory.h>
#include <AIS_Shape.hxx>
#include <gce_MakeDir.hxx>
#include <QVector3D>
#include <QDebug>
Macros
#define CANONIF_CPP
Functions
static void arc (int lineno, double x0, double y0, double x1, double y1, double dx, double dy)
void ARC_FEED (int lineno, double first_end, double second_end, double first_axis, double second_axis, int rotation, double axis_end_point, double a, double b, double c, double u, double v, double w)
static int biarc (int lineno, double p0x, double p0y, double tsx, double tsy, double p4x, double p4y, double tex, double tey, double r=1.0)
nurbs stuff taken from linuxcnc (task/emccanon.cc)
void CANON_ERROR (const char *,...)
void CANON_UPDATE_END_POINT (double x, double y, double z, double a, double b, double c, double u, double v, double w)
void CHANGE_TOOL (int slot)
void CHANGE_TOOL_NUMBER (int)
static double chord_deviation (double sx, double sy, double ex, double ey, double cx, double cy, int rotation, double &mx, double &my)
static PM_CARTESIAN circshift (PM_CARTESIAN &vec, int steps)
void CLAMP_AXIS (CANON_AXIS)
void CLEAR_AUX_OUTPUT_BIT (int)
void CLEAR_MOTION_OUTPUT_BIT (int)
void COMMENT (const char *)
void DISABLE_ADAPTIVE_FEED ()
void DISABLE_FEED_HOLD ()
void DISABLE_FEED_OVERRIDE ()
void DISABLE_SPEED_OVERRIDE (int)
void DWELL (double seconds)
void ENABLE_ADAPTIVE_FEED ()
void ENABLE_FEED_HOLD ()
void ENABLE_FEED_OVERRIDE ()
void ENABLE_SPEED_OVERRIDE (int)
void FINISH (void)
void FLOOD_OFF ()
void FLOOD_ON ()
double FROM_EXT_ANG (double a)
double FROM_EXT_LEN (double l)
static void from_prog (CANON_POSITION &pos)
static void from_prog (double &x, double &y, double &z, double &a, double &b, double &c, double &u, double &v, double &w)
double FROM_PROG_ANG (double a)
double FROM_PROG_LEN (double l)
Interpreter helper functions (don't use preprocessor macros!)
static void from_prog_len (PM_CARTESIAN &vec)
bool GET_BLOCK_DELETE (void)
int GET_EXTERNAL_ADAPTIVE_FEED_ENABLE ()
double GET_EXTERNAL_ANALOG_INPUT (int, double)
double GET_EXTERNAL_ANGLE_UNITS ()
int GET_EXTERNAL_AXIS_MASK ()
int GET_EXTERNAL_DIGITAL_INPUT (int, int)
int GET_EXTERNAL_FEED_HOLD_ENABLE ()
int GET_EXTERNAL_FEED_OVERRIDE_ENABLE ()
double GET_EXTERNAL_FEED_RATE ()
int GET_EXTERNAL_FLOOD ()
CANON_UNITS GET_EXTERNAL_LENGTH_UNIT_TYPE ()
double GET_EXTERNAL_LENGTH_UNITS ()
int GET_EXTERNAL_MIST ()
CANON_MOTION_MODE GET_EXTERNAL_MOTION_CONTROL_MODE ()
double GET_EXTERNAL_MOTION_CONTROL_NAIVECAM_TOLERANCE ()
double GET_EXTERNAL_MOTION_CONTROL_TOLERANCE ()
int GET_EXTERNAL_OFFSET_APPLIED ()
EmcPose GET_EXTERNAL_OFFSETS ()
void GET_EXTERNAL_PARAMETER_FILE_NAME (char *filename, int max_size)
CANON_PLANE GET_EXTERNAL_PLANE ()
double GET_EXTERNAL_POSITION_A ()
double GET_EXTERNAL_POSITION_B ()
double GET_EXTERNAL_POSITION_C ()
double GET_EXTERNAL_POSITION_U ()
double GET_EXTERNAL_POSITION_V ()
double GET_EXTERNAL_POSITION_W ()
double GET_EXTERNAL_POSITION_X ()
double GET_EXTERNAL_POSITION_Y ()
double GET_EXTERNAL_POSITION_Z ()
double GET_EXTERNAL_PROBE_POSITION_A ()
double GET_EXTERNAL_PROBE_POSITION_B ()
double GET_EXTERNAL_PROBE_POSITION_C ()
double GET_EXTERNAL_PROBE_POSITION_U ()
double GET_EXTERNAL_PROBE_POSITION_V ()
double GET_EXTERNAL_PROBE_POSITION_W ()
double GET_EXTERNAL_PROBE_POSITION_X ()
double GET_EXTERNAL_PROBE_POSITION_Y ()
double GET_EXTERNAL_PROBE_POSITION_Z ()
int GET_EXTERNAL_PROBE_TRIPPED_VALUE ()
double GET_EXTERNAL_PROBE_VALUE ()
int GET_EXTERNAL_QUEUE_EMPTY ()
int GET_EXTERNAL_SELECTED_TOOL_SLOT ()
double GET_EXTERNAL_SPEED (int spindle)
CANON_DIRECTION GET_EXTERNAL_SPINDLE (int spindle)
int GET_EXTERNAL_SPINDLE_OVERRIDE_ENABLE (int spindle)
int GET_EXTERNAL_TC_FAULT ()
int GET_EXTERNAL_TC_REASON ()
double GET_EXTERNAL_TOOL_LENGTH_AOFFSET ()
double GET_EXTERNAL_TOOL_LENGTH_BOFFSET ()
double GET_EXTERNAL_TOOL_LENGTH_COFFSET ()
double GET_EXTERNAL_TOOL_LENGTH_UOFFSET ()
double GET_EXTERNAL_TOOL_LENGTH_VOFFSET ()
double GET_EXTERNAL_TOOL_LENGTH_WOFFSET ()
double GET_EXTERNAL_TOOL_LENGTH_XOFFSET ()
double GET_EXTERNAL_TOOL_LENGTH_YOFFSET ()
double GET_EXTERNAL_TOOL_LENGTH_ZOFFSET ()
int GET_EXTERNAL_TOOL_SLOT ()
CANON_TOOL_TABLE GET_EXTERNAL_TOOL_TABLE (int ttIndex)
double GET_EXTERNAL_TRAVERSE_RATE ()
bool GET_OPTIONAL_PROGRAM_STOP ()
void INIT_CANON ()
void IO_PLUGIN_CALL (int, const char *)
int LOCK_ROTARY (int, int)
void LOCK_SPINDLE_Z ()
void LOG (char *)
void LOGAPPEND (char *)
void LOGCLOSE ()
void LOGOPEN (char *)
void MESSAGE (char *)
void MIST_OFF ()
void MIST_ON ()
void NURB_CONTROL_POINT (int, double, double, double, double)
void NURB_FEED (double, double)
void NURB_KNOT_VECTOR ()
void NURBS_FEED (int lineno, std::vector< CONTROL_POINT > nurbs_control_points, unsigned int k)
void ON_RESET (void)
void OPTIONAL_PROGRAM_STOP ()
void ORIENT_SPINDLE (int, double, int)
void PALLET_SHUTTLE ()
void PLUGIN_CALL (int, const char *)
void PROGRAM_END ()
void PROGRAM_STOP ()
void RELOAD_TOOLDATA (void)
void RIGID_TAP (int, double x, double y, double z, double)
static void rotate (double &x, double &y, double angle)
static void rotate_and_offset (CANON_POSITION &pos)
static void rotate_and_offset_pos (double &x, double &y, double &, double &, double &, double &, double &, double &, double &)
static void rotate_and_offset_xyz (PM_CARTESIAN &xyz)
void SELECT_PLANE (CANON_PLANE pl)
void SELECT_TOOL (int toolNum)
void SET_AUX_OUTPUT_BIT (int)
void SET_AUX_OUTPUT_VALUE (int, double)
void SET_BLOCK_DELETE (bool)
void SET_CUTTER_RADIUS_COMPENSATION (double)
void SET_FEED_MODE (int, int)
void SET_FEED_RATE (double)
void SET_FEED_REFERENCE (CANON_FEED_REFERENCE)
void SET_G5X_OFFSET (int fixture, double x, double y, double z, double a, double b, double c, double u, double v, double w)
void SET_G92_OFFSET (double x, double y, double z, double a, double b, double c, double u, double v, double w)
void SET_MOTION_CONTROL_MODE (CANON_MOTION_MODE, double)
void SET_MOTION_OUTPUT_BIT (int)
void SET_MOTION_OUTPUT_VALUE (int, double)
void SET_NAIVECAM_TOLERANCE (double)
void SET_OPTIONAL_PROGRAM_STOP (bool)
void SET_PARAMETER_FILE_NAME (const char *)
void SET_SPINDLE_MODE (int spindle, double mode)
void SET_SPINDLE_SPEED (int, double)
void SET_TOOL_TABLE_ENTRY (int, int, EmcPose, double, double, double, int)
void SET_TRAVERSE_RATE (double)
void SET_XY_ROTATION (double t)
void SPINDLE_RETRACT ()
void SPINDLE_RETRACT_TRAVERSE ()
void START_CHANGE (void)
void START_CUTTER_RADIUS_COMPENSATION (int)
void START_SPEED_FEED_SYNCH (int, double, bool)
void START_SPINDLE_CLOCKWISE (int, int)
void START_SPINDLE_COUNTERCLOCKWISE (int, int)
void STOP ()
void STOP_CUTTER_RADIUS_COMPENSATION ()
void STOP_SPEED_FEED_SYNCH ()
void STOP_SPINDLE_TURNING (int)
void STRAIGHT_FEED (int lineno, double x, double y, double z, double a, double b, double c, double u, double v, double w)
void STRAIGHT_PROBE (int, double, double, double, double, double, double, double, double, double, unsigned char)
void STRAIGHT_TRAVERSE (int lineno, double x, double y, double z, double a, double b, double c, double u, double v, double w)
double TO_EXT_ANG (double a)
static gp_Pnt to_ext_len (const gp_Pnt &p)
double TO_EXT_LEN (double l)
static void to_prog (CANON_POSITION &e)
double TO_PROG_ANG (double a)
double TO_PROG_LEN (double l)
static void to_rotated (PM_CARTESIAN &vec)
void TURN_PROBE_OFF ()
void TURN_PROBE_ON ()
void UNCLAMP_AXIS (CANON_AXIS)
static void unit (double *x, double *y)
int UNLOCK_ROTARY (int, int)
void UPDATE_TAG (StateTag)
void USE_LENGTH_UNITS (CANON_UNITS u)
void USE_NO_SPINDLE_FORCE ()
void USE_SPINDLE_FORCE ()
void USE_TOOL_LENGTH_OFFSET (EmcPose offset)
int WAIT (int, int, int, double)
void WAIT_SPINDLE_ORIENT_COMPLETE (int, double)
Variables
USER_DEFINED_FUNCTION_TYPE USER_DEFINED_FUNCTION [USER_DEFINED_FUNCTION_NUM]
Macro Definition Documentation
CANONIF_CPP
#define CANONIF_CPP
Function Documentation
arc()
static void arc (int lineno, double x0, double y0, double x1, double y1, double dx, double dy) static
References ARC_FEED(), CanonIF::endPoint(), STRAIGHT_FEED(), and to_prog().
Referenced by biarc().
ARC_FEED()
void ARC_FEED (int lineno, double first_end, double second_end, double first_axis, double second_axis, int rotation, double axis_end_point, double a, double b, double c, double u, double v, double w)
References CanonIF::activePlane(), CanonIF::appendShape(), CANON_ERROR(), chord_deviation(), circshift(), CanonIF::endPoint(), CanonIF::feedColor(), from_prog(), FROM_PROG_ANG(), FROM_PROG_LEN(), from_prog_len(), CanonIF::graphicFactory(), Handle(), CanonIF::motionMode(), CanonIF::naiveTolerance(), rotate_and_offset(), rotate_and_offset_pos(), rotate_and_offset_xyz(), CanonIF::setEndPoint(), to_ext_len(), and to_rotated().
Referenced by arc().
biarc()
static int biarc (int lineno, double p0x, double p0y, double tsx, double tsy, double p4x, double p4y, double tex, double tey, double r = 1.0) static
nurbs stuff taken from linuxcnc (task/emccanon.cc)
References arc(), and unit().
Referenced by NURBS_FEED().
CANON_ERROR()
void CANON_ERROR (const char * , ...)
Referenced by ARC_FEED().
CANON_UPDATE_END_POINT()
void CANON_UPDATE_END_POINT (double x, double y, double z, double a, double b, double c, double u, double v, double w)
References CanonIF::setEndPoint().
CHANGE_TOOL()
void CHANGE_TOOL (int slot)
References CanonIF::changeTool().
CHANGE_TOOL_NUMBER()
void CHANGE_TOOL_NUMBER (int)
chord_deviation()
static double chord_deviation (double sx, double sy, double ex, double ey, double cx, double cy, int rotation, double & mx, double & my) static
Referenced by ARC_FEED().
circshift()
static PM_CARTESIAN circshift (PM_CARTESIAN & vec, int steps) static
Simple circular shift function for PM_CARTESIAN type. Cycle around axes without changing the individual values. A circshift of -1 makes the X value become the new Y, Y become the Z, and Z become the new X.
Referenced by ARC_FEED().
CLAMP_AXIS()
void CLAMP_AXIS (CANON_AXIS)
CLEAR_AUX_OUTPUT_BIT()
void CLEAR_AUX_OUTPUT_BIT (int)
CLEAR_MOTION_OUTPUT_BIT()
void CLEAR_MOTION_OUTPUT_BIT (int)
COMMENT()
void COMMENT (const char *)
DISABLE_ADAPTIVE_FEED()
void DISABLE_ADAPTIVE_FEED ()
DISABLE_FEED_HOLD()
void DISABLE_FEED_HOLD ()
DISABLE_FEED_OVERRIDE()
void DISABLE_FEED_OVERRIDE ()
DISABLE_SPEED_OVERRIDE()
void DISABLE_SPEED_OVERRIDE (int)
DWELL()
void DWELL (double seconds)
ENABLE_ADAPTIVE_FEED()
void ENABLE_ADAPTIVE_FEED ()
ENABLE_FEED_HOLD()
void ENABLE_FEED_HOLD ()
ENABLE_FEED_OVERRIDE()
void ENABLE_FEED_OVERRIDE ()
ENABLE_SPEED_OVERRIDE()
void ENABLE_SPEED_OVERRIDE (int)
FINISH()
void FINISH (void)
FLOOD_OFF()
void FLOOD_OFF ()
FLOOD_ON()
void FLOOD_ON ()
FROM_EXT_ANG()
double FROM_EXT_ANG (double a) inline
References GET_EXTERNAL_ANGLE_UNITS().
FROM_EXT_LEN()
double FROM_EXT_LEN (double l) inline
References GET_EXTERNAL_LENGTH_UNITS().
from_prog() [1/2]
static void from_prog (CANON_POSITION & pos) static
References FROM_PROG_ANG(), and FROM_PROG_LEN().
Referenced by ARC_FEED(), STRAIGHT_FEED(), and STRAIGHT_TRAVERSE().
from_prog() [2/2]
static void from_prog (double & x, double & y, double & z, double & a, double & b, double & c, double & u, double & v, double & w) static
References FROM_PROG_ANG(), and FROM_PROG_LEN().
FROM_PROG_ANG()
double FROM_PROG_ANG (double a) inline
Referenced by ARC_FEED(), and from_prog().
FROM_PROG_LEN()
double FROM_PROG_LEN (double l) inline
Interpreter helper functions (don't use preprocessor macros!)
References CanonIF::lengthUnits().
Referenced by ARC_FEED(), from_prog(), and from_prog_len().
from_prog_len()
static void from_prog_len (PM_CARTESIAN & vec) static
References FROM_PROG_LEN().
Referenced by ARC_FEED().
GET_BLOCK_DELETE()
bool GET_BLOCK_DELETE (void)
GET_EXTERNAL_ADAPTIVE_FEED_ENABLE()
int GET_EXTERNAL_ADAPTIVE_FEED_ENABLE ()
References CanonIF::isAdaptiveFeedEnabled().
GET_EXTERNAL_ANALOG_INPUT()
double GET_EXTERNAL_ANALOG_INPUT (int , double)
GET_EXTERNAL_ANGLE_UNITS()
double GET_EXTERNAL_ANGLE_UNITS ()
Referenced by FROM_EXT_ANG(), and TO_EXT_ANG().
GET_EXTERNAL_AXIS_MASK()
int GET_EXTERNAL_AXIS_MASK ()
References Core::axisMask().
GET_EXTERNAL_DIGITAL_INPUT()
int GET_EXTERNAL_DIGITAL_INPUT (int , int)
GET_EXTERNAL_FEED_HOLD_ENABLE()
int GET_EXTERNAL_FEED_HOLD_ENABLE ()
References CanonIF::isFeedHoldActive().
GET_EXTERNAL_FEED_OVERRIDE_ENABLE()
int GET_EXTERNAL_FEED_OVERRIDE_ENABLE ()
References CanonIF::isFeedOverrideEnabled().
GET_EXTERNAL_FEED_RATE()
double GET_EXTERNAL_FEED_RATE ()
References CanonIF::feedRate().
GET_EXTERNAL_FLOOD()
int GET_EXTERNAL_FLOOD ()
References CanonIF::isFloodActive().
GET_EXTERNAL_LENGTH_UNIT_TYPE()
CANON_UNITS GET_EXTERNAL_LENGTH_UNIT_TYPE ()
References CanonIF::machineUnits().
GET_EXTERNAL_LENGTH_UNITS()
double GET_EXTERNAL_LENGTH_UNITS ()
References CanonIF::lengthUnits().
Referenced by FROM_EXT_LEN(), and TO_EXT_LEN().
GET_EXTERNAL_MIST()
int GET_EXTERNAL_MIST ()
References CanonIF::isMistActive().
GET_EXTERNAL_MOTION_CONTROL_MODE()
CANON_MOTION_MODE GET_EXTERNAL_MOTION_CONTROL_MODE ()
References CanonIF::motionMode().
GET_EXTERNAL_MOTION_CONTROL_NAIVECAM_TOLERANCE()
double GET_EXTERNAL_MOTION_CONTROL_NAIVECAM_TOLERANCE ()
References CanonIF::naiveTolerance().
GET_EXTERNAL_MOTION_CONTROL_TOLERANCE()
double GET_EXTERNAL_MOTION_CONTROL_TOLERANCE ()
References CanonIF::motionTolerance().
GET_EXTERNAL_OFFSET_APPLIED()
int GET_EXTERNAL_OFFSET_APPLIED ()
GET_EXTERNAL_OFFSETS()
EmcPose GET_EXTERNAL_OFFSETS ()
GET_EXTERNAL_PARAMETER_FILE_NAME()
void GET_EXTERNAL_PARAMETER_FILE_NAME (char * filename, int max_size)
GET_EXTERNAL_PLANE()
CANON_PLANE GET_EXTERNAL_PLANE ()
References CanonIF::activePlane().
GET_EXTERNAL_POSITION_A()
double GET_EXTERNAL_POSITION_A ()
References CanonIF::posA().
GET_EXTERNAL_POSITION_B()
double GET_EXTERNAL_POSITION_B ()
References CanonIF::posB().
GET_EXTERNAL_POSITION_C()
double GET_EXTERNAL_POSITION_C ()
References CanonIF::posC().
GET_EXTERNAL_POSITION_U()
double GET_EXTERNAL_POSITION_U ()
References CanonIF::posU().
GET_EXTERNAL_POSITION_V()
double GET_EXTERNAL_POSITION_V ()
References CanonIF::posV().
GET_EXTERNAL_POSITION_W()
double GET_EXTERNAL_POSITION_W ()
References CanonIF::posW().
GET_EXTERNAL_POSITION_X()
double GET_EXTERNAL_POSITION_X ()
References CanonIF::posX().
GET_EXTERNAL_POSITION_Y()
double GET_EXTERNAL_POSITION_Y ()
References CanonIF::posY().
GET_EXTERNAL_POSITION_Z()
double GET_EXTERNAL_POSITION_Z ()
References CanonIF::posZ().
GET_EXTERNAL_PROBE_POSITION_A()
double GET_EXTERNAL_PROBE_POSITION_A ()
GET_EXTERNAL_PROBE_POSITION_B()
double GET_EXTERNAL_PROBE_POSITION_B ()
GET_EXTERNAL_PROBE_POSITION_C()
double GET_EXTERNAL_PROBE_POSITION_C ()
GET_EXTERNAL_PROBE_POSITION_U()
double GET_EXTERNAL_PROBE_POSITION_U ()
GET_EXTERNAL_PROBE_POSITION_V()
double GET_EXTERNAL_PROBE_POSITION_V ()
GET_EXTERNAL_PROBE_POSITION_W()
double GET_EXTERNAL_PROBE_POSITION_W ()
GET_EXTERNAL_PROBE_POSITION_X()
double GET_EXTERNAL_PROBE_POSITION_X ()
GET_EXTERNAL_PROBE_POSITION_Y()
double GET_EXTERNAL_PROBE_POSITION_Y ()
GET_EXTERNAL_PROBE_POSITION_Z()
double GET_EXTERNAL_PROBE_POSITION_Z ()
GET_EXTERNAL_PROBE_TRIPPED_VALUE()
int GET_EXTERNAL_PROBE_TRIPPED_VALUE ()
GET_EXTERNAL_PROBE_VALUE()
double GET_EXTERNAL_PROBE_VALUE ()
GET_EXTERNAL_QUEUE_EMPTY()
int GET_EXTERNAL_QUEUE_EMPTY ()
GET_EXTERNAL_SELECTED_TOOL_SLOT()
int GET_EXTERNAL_SELECTED_TOOL_SLOT ()
References CanonIF::nextSlot().
GET_EXTERNAL_SPEED()
double GET_EXTERNAL_SPEED (int spindle)
References CanonIF::spindleSpeed().
GET_EXTERNAL_SPINDLE()
CANON_DIRECTION GET_EXTERNAL_SPINDLE (int spindle)
References CanonIF::spindleDir().
GET_EXTERNAL_SPINDLE_OVERRIDE_ENABLE()
int GET_EXTERNAL_SPINDLE_OVERRIDE_ENABLE (int spindle)
References CanonIF::isSpeedOverrideEnabled().
GET_EXTERNAL_TC_FAULT()
int GET_EXTERNAL_TC_FAULT ()
GET_EXTERNAL_TC_REASON()
int GET_EXTERNAL_TC_REASON ()
GET_EXTERNAL_TOOL_LENGTH_AOFFSET()
double GET_EXTERNAL_TOOL_LENGTH_AOFFSET ()
References CanonIF::toolOffset().
GET_EXTERNAL_TOOL_LENGTH_BOFFSET()
double GET_EXTERNAL_TOOL_LENGTH_BOFFSET ()
References CanonIF::toolOffset().
GET_EXTERNAL_TOOL_LENGTH_COFFSET()
double GET_EXTERNAL_TOOL_LENGTH_COFFSET ()
References CanonIF::toolOffset().
GET_EXTERNAL_TOOL_LENGTH_UOFFSET()
double GET_EXTERNAL_TOOL_LENGTH_UOFFSET ()
References CanonIF::toolOffset().
GET_EXTERNAL_TOOL_LENGTH_VOFFSET()
double GET_EXTERNAL_TOOL_LENGTH_VOFFSET ()
References CanonIF::toolOffset().
GET_EXTERNAL_TOOL_LENGTH_WOFFSET()
double GET_EXTERNAL_TOOL_LENGTH_WOFFSET ()
References CanonIF::toolOffset().
GET_EXTERNAL_TOOL_LENGTH_XOFFSET()
double GET_EXTERNAL_TOOL_LENGTH_XOFFSET ()
References CanonIF::toolOffset().
GET_EXTERNAL_TOOL_LENGTH_YOFFSET()
double GET_EXTERNAL_TOOL_LENGTH_YOFFSET ()
References CanonIF::toolOffset().
GET_EXTERNAL_TOOL_LENGTH_ZOFFSET()
double GET_EXTERNAL_TOOL_LENGTH_ZOFFSET ()
References CanonIF::toolOffset().
GET_EXTERNAL_TOOL_SLOT()
int GET_EXTERNAL_TOOL_SLOT ()
References CanonIF::lastSlot().
GET_EXTERNAL_TOOL_TABLE()
CANON_TOOL_TABLE GET_EXTERNAL_TOOL_TABLE (int ttIndex)
References CanonIF::toolEntry().
GET_EXTERNAL_TRAVERSE_RATE()
double GET_EXTERNAL_TRAVERSE_RATE ()
References CanonIF::traverseRate().
GET_OPTIONAL_PROGRAM_STOP()
bool GET_OPTIONAL_PROGRAM_STOP ()
INIT_CANON()
void INIT_CANON ()
IO_PLUGIN_CALL()
void IO_PLUGIN_CALL (int , const char *)
LOCK_ROTARY()
int LOCK_ROTARY (int , int)
LOCK_SPINDLE_Z()
void LOCK_SPINDLE_Z ()
LOG()
void LOG (char *)
LOGAPPEND()
void LOGAPPEND (char *)
LOGCLOSE()
void LOGCLOSE ()
LOGOPEN()
void LOGOPEN (char *)
MESSAGE()
void MESSAGE (char *)
MIST_OFF()
void MIST_OFF ()
MIST_ON()
void MIST_ON ()
NURB_CONTROL_POINT()
void NURB_CONTROL_POINT (int , double , double , double , double)
NURB_FEED()
void NURB_FEED (double , double)
NURB_KNOT_VECTOR()
void NURB_KNOT_VECTOR ()
NURBS_FEED()
void NURBS_FEED (int lineno, std::vector< CONTROL_POINT > nurbs_control_points, unsigned int k)
References biarc().
ON_RESET()
void ON_RESET (void)
OPTIONAL_PROGRAM_STOP()
void OPTIONAL_PROGRAM_STOP ()
ORIENT_SPINDLE()
void ORIENT_SPINDLE (int , double , int)
PALLET_SHUTTLE()
void PALLET_SHUTTLE ()
PLUGIN_CALL()
void PLUGIN_CALL (int , const char *)
PROGRAM_END()
void PROGRAM_END ()
PROGRAM_STOP()
void PROGRAM_STOP ()
RELOAD_TOOLDATA()
void RELOAD_TOOLDATA (void)
RIGID_TAP()
void RIGID_TAP (int , double x, double y, double z, double)
References CanonIF::endPoint(), and CanonIF::setEndPoint().
rotate()
static void rotate (double & x, double & y, double angle) static
Referenced by rotate_and_offset(), rotate_and_offset_pos(), rotate_and_offset_xyz(), and to_rotated().
rotate_and_offset()
static void rotate_and_offset (CANON_POSITION & pos) static
References rotate(), and CanonIF::xyRotation().
Referenced by ARC_FEED().
rotate_and_offset_pos()
static void rotate_and_offset_pos (double & x, double & y, double & , double & , double & , double & , double & , double & , double &) static
References rotate(), and CanonIF::xyRotation().
Referenced by ARC_FEED(), STRAIGHT_FEED(), and STRAIGHT_TRAVERSE().
rotate_and_offset_xyz()
static void rotate_and_offset_xyz (PM_CARTESIAN & xyz) static
References rotate(), and CanonIF::xyRotation().
Referenced by ARC_FEED().
SELECT_PLANE()
void SELECT_PLANE (CANON_PLANE pl)
References CanonIF::selectPlane().
SELECT_TOOL()
void SELECT_TOOL (int toolNum)
References CanonIF::selectTool().
SET_AUX_OUTPUT_BIT()
void SET_AUX_OUTPUT_BIT (int)
SET_AUX_OUTPUT_VALUE()
void SET_AUX_OUTPUT_VALUE (int , double)
SET_BLOCK_DELETE()
void SET_BLOCK_DELETE (bool)
SET_CUTTER_RADIUS_COMPENSATION()
void SET_CUTTER_RADIUS_COMPENSATION (double)
SET_FEED_MODE()
void SET_FEED_MODE (int , int)
SET_FEED_RATE()
void SET_FEED_RATE (double)
SET_FEED_REFERENCE()
void SET_FEED_REFERENCE (CANON_FEED_REFERENCE)
SET_G5X_OFFSET()
void SET_G5X_OFFSET (int fixture, double x, double y, double z, double a, double b, double c, double u, double v, double w)
References CanonIF::setG5xOffset().
SET_G92_OFFSET()
void SET_G92_OFFSET (double x, double y, double z, double a, double b, double c, double u, double v, double w)
References CanonIF::setG92Offset().
SET_MOTION_CONTROL_MODE()
void SET_MOTION_CONTROL_MODE (CANON_MOTION_MODE , double)
SET_MOTION_OUTPUT_BIT()
void SET_MOTION_OUTPUT_BIT (int)
SET_MOTION_OUTPUT_VALUE()
void SET_MOTION_OUTPUT_VALUE (int , double)
SET_NAIVECAM_TOLERANCE()
void SET_NAIVECAM_TOLERANCE (double)
SET_OPTIONAL_PROGRAM_STOP()
void SET_OPTIONAL_PROGRAM_STOP (bool)
SET_PARAMETER_FILE_NAME()
void SET_PARAMETER_FILE_NAME (const char *)
SET_SPINDLE_MODE()
void SET_SPINDLE_MODE (int spindle, double mode)
References CanonIF::setSpindleMode().
SET_SPINDLE_SPEED()
void SET_SPINDLE_SPEED (int , double)
SET_TOOL_TABLE_ENTRY()
void SET_TOOL_TABLE_ENTRY (int , int , EmcPose , double , double , double , int)
SET_TRAVERSE_RATE()
void SET_TRAVERSE_RATE (double)
SET_XY_ROTATION()
void SET_XY_ROTATION (double t)
References CanonIF::setXYRotation().
SPINDLE_RETRACT()
void SPINDLE_RETRACT ()
SPINDLE_RETRACT_TRAVERSE()
void SPINDLE_RETRACT_TRAVERSE ()
START_CHANGE()
void START_CHANGE (void)
START_CUTTER_RADIUS_COMPENSATION()
void START_CUTTER_RADIUS_COMPENSATION (int)
START_SPEED_FEED_SYNCH()
void START_SPEED_FEED_SYNCH (int , double , bool)
START_SPINDLE_CLOCKWISE()
void START_SPINDLE_CLOCKWISE (int , int)
START_SPINDLE_COUNTERCLOCKWISE()
void START_SPINDLE_COUNTERCLOCKWISE (int , int)
STOP()
void STOP ()
STOP_CUTTER_RADIUS_COMPENSATION()
void STOP_CUTTER_RADIUS_COMPENSATION ()
STOP_SPEED_FEED_SYNCH()
void STOP_SPEED_FEED_SYNCH ()
STOP_SPINDLE_TURNING()
void STOP_SPINDLE_TURNING (int)
STRAIGHT_FEED()
void STRAIGHT_FEED (int lineno, double x, double y, double z, double a, double b, double c, double u, double v, double w)
References CanonIF::appendShape(), CanonIF::endPoint(), CanonIF::feedColor(), from_prog(), CanonIF::graphicFactory(), Handle(), rotate_and_offset_pos(), and CanonIF::setEndPoint().
Referenced by arc().
STRAIGHT_PROBE()
void STRAIGHT_PROBE (int , double , double , double , double , double , double , double , double , double , unsigned char)
STRAIGHT_TRAVERSE()
void STRAIGHT_TRAVERSE (int lineno, double x, double y, double z, double a, double b, double c, double u, double v, double w)
References CanonIF::appendShape(), CanonIF::endPoint(), from_prog(), CanonIF::graphicFactory(), Handle(), rotate_and_offset_pos(), CanonIF::setEndPoint(), and CanonIF::traverseColor().
TO_EXT_ANG()
double TO_EXT_ANG (double a) inline
References GET_EXTERNAL_ANGLE_UNITS().
to_ext_len()
static gp_Pnt to_ext_len (const gp_Pnt & p) static
References TO_EXT_LEN().
Referenced by ARC_FEED().
TO_EXT_LEN()
double TO_EXT_LEN (double l) inline
References GET_EXTERNAL_LENGTH_UNITS().
Referenced by to_ext_len().
to_prog()
static void to_prog (CANON_POSITION & e) static
References TO_PROG_ANG(), and TO_PROG_LEN().
Referenced by arc().
TO_PROG_ANG()
double TO_PROG_ANG (double a) inline
Referenced by to_prog().
TO_PROG_LEN()
double TO_PROG_LEN (double l) inline
References CanonIF::lengthUnits().
Referenced by to_prog().
to_rotated()
static void to_rotated (PM_CARTESIAN & vec) static
References rotate().
Referenced by ARC_FEED().
TURN_PROBE_OFF()
void TURN_PROBE_OFF ()
TURN_PROBE_ON()
void TURN_PROBE_ON ()
UNCLAMP_AXIS()
void UNCLAMP_AXIS (CANON_AXIS)
unit()
static void unit (double * x, double * y) static
Referenced by biarc(), PositionCalculator::convertUnit(), and LCInterface::parseInline().
UNLOCK_ROTARY()
int UNLOCK_ROTARY (int , int)
UPDATE_TAG()
void UPDATE_TAG (StateTag)
USE_LENGTH_UNITS()
void USE_LENGTH_UNITS (CANON_UNITS u)
References CanonIF::setLengthUnits().
USE_NO_SPINDLE_FORCE()
void USE_NO_SPINDLE_FORCE ()
USE_SPINDLE_FORCE()
void USE_SPINDLE_FORCE ()
USE_TOOL_LENGTH_OFFSET()
void USE_TOOL_LENGTH_OFFSET (EmcPose offset)
References CanonIF::setToolOffset().
WAIT()
int WAIT (int , int , int , double)
WAIT_SPINDLE_ORIENT_COMPLETE()
void WAIT_SPINDLE_ORIENT_COMPLETE (int , double)
Variable Documentation
USER_DEFINED_FUNCTION
USER_DEFINED_FUNCTION_TYPE USER_DEFINED_FUNCTION[USER_DEFINED_FUNCTION_NUM]