FalconView: HHelixCurveAdaptor Class Reference
HHelixCurveAdaptor Class Reference
#include <HHelixCurveAdaptor.h>
Public Member Functions
HHelixCurveAdaptor (const Geom_HelixData &theData)
Constructor.
HHelixCurveAdaptor (const std::shared_ptr< HelixCurveAdaptor::Evaluator > &theEvaluator, Standard_Real theMin, Standard_Real theMax)
Constructor.
virtual GeomAbs_Shape Continuity () const override
virtual void D0 (const double U, gp_Pnt &P) const override
virtual void D1 (const double U, gp_Pnt &P, gp_Vec &V) const override
virtual void D2 (const double U, gp_Pnt &P, gp_Vec &V1, gp_Vec &V2) const override
virtual void D3 (const double U, gp_Pnt &P, gp_Vec &V1, gp_Vec &V2, gp_Vec &V3) const override
virtual gp_Vec DN (const double U, const Standard_Integer N) const override
virtual double FirstParameter () const override
virtual GeomAbs_CurveType GetType () const override
virtual Handle (Adaptor3d_Curve) Trim(const double First
virtual void Intervals (TColStd_Array1OfReal &T, const GeomAbs_Shape S) __CADEX_ADAPTOR3D_CURVE_CONST override
virtual Standard_Boolean IsClosed () const override
virtual Standard_Boolean IsPeriodic () const override
virtual double LastParameter () const override
virtual Standard_Integer NbIntervals (const GeomAbs_Shape S) __CADEX_ADAPTOR3D_CURVE_CONST override
virtual double Resolution (const double R3d) const override
virtual gp_Pnt Value (const double U) const override
Public Attributes
virtual const double Last
virtual const double const double Tol const override
Protected Attributes
HelixCurveAdaptor myAdaptor
Constructor & Destructor Documentation
HHelixCurveAdaptor() [1/2]
HHelixCurveAdaptor::HHelixCurveAdaptor (const Geom_HelixData & theData)
Constructor.
HHelixCurveAdaptor() [2/2]
HHelixCurveAdaptor::HHelixCurveAdaptor (const std::shared_ptr< HelixCurveAdaptor::Evaluator > & theEvaluator, Standard_Real theMin, Standard_Real theMax)
Constructor.
Member Function Documentation
Continuity()
GeomAbs_Shape HHelixCurveAdaptor::Continuity () const override virtual
References HelixCurveAdaptor::Continuity(), and myAdaptor.
D0()
virtual void HHelixCurveAdaptor::D0 (const double U, gp_Pnt & P) const override virtual
D1()
virtual void HHelixCurveAdaptor::D1 (const double U, gp_Pnt & P, gp_Vec & V) const override virtual
D2()
virtual void HHelixCurveAdaptor::D2 (const double U, gp_Pnt & P, gp_Vec & V1, gp_Vec & V2) const override virtual
D3()
virtual void HHelixCurveAdaptor::D3 (const double U, gp_Pnt & P, gp_Vec & V1, gp_Vec & V2, gp_Vec & V3) const override virtual
DN()
virtual gp_Vec HHelixCurveAdaptor::DN (const double U, const Standard_Integer N) const override virtual
FirstParameter()
double HHelixCurveAdaptor::FirstParameter () const override virtual
References HelixCurveAdaptor::FirstParameter(), and myAdaptor.
GetType()
virtual GeomAbs_CurveType HHelixCurveAdaptor::GetType () const override virtual
Handle()
virtual HHelixCurveAdaptor::Handle (Adaptor3d_Curve) const virtual
Intervals()
void HHelixCurveAdaptor::Intervals (TColStd_Array1OfReal & T, const GeomAbs_Shape S) override virtual
IsClosed()
virtual Standard_Boolean HHelixCurveAdaptor::IsClosed () const override virtual
IsPeriodic()
virtual Standard_Boolean HHelixCurveAdaptor::IsPeriodic () const override virtual
LastParameter()
double HHelixCurveAdaptor::LastParameter () const override virtual
References HelixCurveAdaptor::LastParameter(), and myAdaptor.
NbIntervals()
Standard_Integer HHelixCurveAdaptor::NbIntervals (const GeomAbs_Shape S) override virtual
Resolution()
virtual double HHelixCurveAdaptor::Resolution (const double R3d) const override virtual
Value()
virtual gp_Pnt HHelixCurveAdaptor::Value (const double U) const override virtual
Member Data Documentation
Last
virtual const double HHelixCurveAdaptor::Last
myAdaptor
HelixCurveAdaptor HHelixCurveAdaptor::myAdaptor protected
Referenced by Continuity(), FirstParameter(), and LastParameter().
override
virtual const double const double Tol const HHelixCurveAdaptor::override
The documentation for this class was generated from the following files:
src/guiLib/util/HHelixCurveAdaptor.h
src/guiLib/util/HHelixCurveAdaptor.cpp