FalconView: StupidToolChangerIF Class Reference
StupidToolChangerIF Class Reference
The StupidToolChangerIF class - dumb model of a tool changer as required by lc.
#include <stupidtoolchangerif.h>
Public Member Functions
StupidToolChangerIF ()
int nextTool () const
void selectNextTool (int toolNum)
void setCurrentTool (int slot)
int slot4ToolInSpindle () const
Private Attributes
int actualSlot
int nextToolNum
Detailed Description
The StupidToolChangerIF class - dumb model of a tool changer as required by lc.
Constructor & Destructor Documentation
StupidToolChangerIF()
StupidToolChangerIF::StupidToolChangerIF ()
Member Function Documentation
nextTool()
int StupidToolChangerIF::nextTool () const inline
References nextToolNum.
Referenced by CanonIF::nextSlot().
selectNextTool()
void StupidToolChangerIF::selectNextTool (int toolNum) inline
References nextToolNum.
Referenced by CanonIF::selectTool().
setCurrentTool()
void StupidToolChangerIF::setCurrentTool (int slot) inline
References actualSlot.
Referenced by CanonIFSettings::changeTool().
slot4ToolInSpindle()
int StupidToolChangerIF::slot4ToolInSpindle () const inline
References actualSlot.
Referenced by CanonIF::lastSlot().
Member Data Documentation
actualSlot
int StupidToolChangerIF::actualSlot private
Referenced by setCurrentTool(), and slot4ToolInSpindle().
nextToolNum
int StupidToolChangerIF::nextToolNum private
Referenced by nextTool(), and selectNextTool().
The documentation for this class was generated from the following files:
src/app/LC/stupidtoolchangerif.h
src/app/LC/stupidtoolchangerif.cpp