FalconView: PositionCalculator Class Reference
PositionCalculator Class Reference
#include <positioncalculator.h>
Public Member Functions
PositionCalculator (QObject *parent=nullptr)
void update (EmcPose *absPos, EmcPose *relPos, EmcPose *dtg, int units, EmcPose *g5x, EmcPose *g92, double rotXY, EmcPose *toolOffset)
Protected Member Functions
double convertUnit (double value, int unit)
void createModels ()
Private Attributes
ValueManager vm
Constructor & Destructor Documentation
PositionCalculator()
PositionCalculator::PositionCalculator (QObject * parent = nullptr) explicit
References createModels().
Member Function Documentation
convertUnit()
double PositionCalculator::convertUnit (double value, int unit) protected
References unit().
Referenced by update().
createModels()
void PositionCalculator::createModels () protected
References ValueManager::setValue(), and vm.
Referenced by PositionCalculator().
update()
void PositionCalculator::update (EmcPose * absPos, EmcPose * relPos, EmcPose * dtg, int units, EmcPose * g5x, EmcPose * g92, double rotXY, EmcPose * toolOffset)
References convertUnit(), ValueManager::setValue(), and vm.
Referenced by StatusReader::update().
Member Data Documentation
vm
ValueManager PositionCalculator::vm private
Referenced by createModels(), and update().
The documentation for this class was generated from the following files:
src/app/LC/positioncalculator.h
src/app/LC/positioncalculator.cpp