FalconView: SysEventModel Class Reference
SysEventModel Class Reference
#include <syseventmodel.h>
Public Member Functions
SysEventModel (DBConnection &conn, QObject *parent=nullptr)
void append (const SysEvent *e)
virtual QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const override
virtual QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const override
Protected Member Functions
int nextId ()
Static Private Member Functions
static bool createTable ()
Constructor & Destructor Documentation
SysEventModel()
SysEventModel::SysEventModel (DBConnection & conn, QObject * parent = nullptr) explicit
References DBConnection::connect().
Member Function Documentation
append()
void SysEventModel::append (const SysEvent * e)
References nextId(), Core::riseError(), SysEvent::type(), SysEvent::what(), and SysEvent::when().
Referenced by GuiKernel::logSysEvent(), and GuiKernel::timerEvent().
createTable()
bool SysEventModel::createTable () static private
Referenced by FalconViewDB::createDatabase().
data()
QVariant SysEventModel::data (const QModelIndex & index, int role = Qt::DisplayRole) const override virtual
References SysEvent::toString().
headerData()
QVariant SysEventModel::headerData (int section, Qt::Orientation orientation, int role = Qt::DisplayRole) const override virtual
nextId()
int SysEventModel::nextId () protected
Referenced by append().
The documentation for this class was generated from the following files:
src/baselib/model/syseventmodel.h
src/baselib/model/syseventmodel.cpp