FalconView: TestEngine Class Reference
TestEngine Class Reference
Public Slots
void updateCondition (bool result)
Private Slots
void init ()
void testAnd3Condition ()
void testAnd4Condition ()
void testAndCondition ()
void testBoolean ()
void testEqualCondition ()
void testGreaterCondition ()
void testOrCondition ()
void testSmallerCondition ()
Private Attributes
volatile bool result
Member Function Documentation
init
void TestEngine::init () inline private slot
References result.
testAnd3Condition
void TestEngine::testAnd3Condition () private slot
References AndCondition::addCondition(), AbstractCondition::conditionChanged(), AbstractCondition::result(), result, ValueModel::setValue(), and updateCondition().
testAnd4Condition
void TestEngine::testAnd4Condition () private slot
References AndCondition::addCondition(), AbstractCondition::conditionChanged(), AbstractCondition::result(), result, ValueModel::setValue(), and updateCondition().
testAndCondition
void TestEngine::testAndCondition () private slot
References AbstractCondition::conditionChanged(), AbstractCondition::result(), result, ValueModel::setValue(), and updateCondition().
testBoolean
void TestEngine::testBoolean () private slot
References AbstractCondition::conditionChanged(), AbstractCondition::result(), result, ValueModel::setValue(), and updateCondition().
testEqualCondition
void TestEngine::testEqualCondition () private slot
References AbstractCondition::conditionChanged(), AbstractCondition::result(), result, ValueModel::setValue(), and updateCondition().
testGreaterCondition
void TestEngine::testGreaterCondition () private slot
References AbstractCondition::conditionChanged(), AbstractCondition::result(), result, ValueModel::setValue(), and updateCondition().
testOrCondition
void TestEngine::testOrCondition () private slot
References AbstractCondition::conditionChanged(), AbstractCondition::result(), result, ValueModel::setValue(), and updateCondition().
testSmallerCondition
void TestEngine::testSmallerCondition () private slot
References AbstractCondition::conditionChanged(), AbstractCondition::result(), result, ValueModel::setValue(), and updateCondition().
updateCondition
void TestEngine::updateCondition (bool result) inline slot
References result.
Referenced by testAnd3Condition(), testAnd4Condition(), testAndCondition(), testBoolean(), testEqualCondition(), testGreaterCondition(), testOrCondition(), and testSmallerCondition().
Member Data Documentation
result
volatile bool TestEngine::result private
Referenced by init(), testAnd3Condition(), testAnd4Condition(), testAndCondition(), testBoolean(), testEqualCondition(), testGreaterCondition(), testOrCondition(), testSmallerCondition(), and updateCondition().
The documentation for this class was generated from the following file:
src/app/test/testengine.cpp