FalconView: AndCondition Class Reference
AndCondition Class Reference
#include <andcondition.h>
Public Slots
virtual bool eval () override
virtual void update ()
Signals
void conditionChanged (bool result)
Public Member Functions
AndCondition (AbstractCondition *c0, AbstractCondition *c1, QObject *parent=nullptr)
virtual ~AndCondition ()
AndCondition * addCondition (AbstractCondition *c)
QString name () const
virtual bool result () const
Protected Member Functions
ValueModel * model ()
QVariant value ()
Private Attributes
QList< AbstractCondition * > cl
bool initialized
ValueModel * m
bool met
QVariant v
Constructor & Destructor Documentation
AndCondition()
AndCondition::AndCondition (AbstractCondition * c0, AbstractCondition * c1, QObject * parent = nullptr) explicit
References addCondition().
~AndCondition()
AndCondition::~AndCondition () virtual
Member Function Documentation
addCondition()
AndCondition * AndCondition::addCondition (AbstractCondition * c)
References cl, AbstractCondition::conditionChanged(), and AbstractCondition::update().
Referenced by AndCondition(), TestEngine::testAnd3Condition(), and TestEngine::testAnd4Condition().
conditionChanged
void AbstractCondition::conditionChanged (bool result) signal inherited
Referenced by DynaAction::DynaAction(), addCondition(), OrCondition::addCondition(), TestEngine::testAnd3Condition(), TestEngine::testAnd4Condition(), TestEngine::testAndCondition(), TestEngine::testBoolean(), TestEngine::testEqualCondition(), TestEngine::testGreaterCondition(), TestEngine::testOrCondition(), TestEngine::testSmallerCondition(), and AbstractCondition::update().
eval
bool AndCondition::eval () override virtual slot
References cl.
model()
ValueModel* AbstractCondition::model () inline protected inherited
References AbstractCondition::m.
Referenced by EqualCondition::eval(), GreaterCondition::eval(), NotCondition::eval(), and SmallerCondition::eval().
name()
QString AbstractCondition::name () const inherited
References ValueModel::getName(), and AbstractCondition::m.
result()
bool AbstractCondition::result () const virtual inherited
Reimplemented in TrueCondition, and FalseCondition.
References AbstractCondition::met.
Referenced by DynaAction::DynaAction(), TestEngine::testAnd3Condition(), TestEngine::testAnd4Condition(), TestEngine::testAndCondition(), TestEngine::testBoolean(), TestEngine::testEqualCondition(), TestEngine::testGreaterCondition(), TestEngine::testOrCondition(), and TestEngine::testSmallerCondition().
update
void AbstractCondition::update () virtual slot inherited
References AbstractCondition::conditionChanged(), AbstractCondition::eval(), AbstractCondition::initialized, and AbstractCondition::met.
Referenced by AbstractCondition::AbstractCondition(), EqualCondition::EqualCondition(), GreaterCondition::GreaterCondition(), NotCondition::NotCondition(), SmallerCondition::SmallerCondition(), addCondition(), and OrCondition::addCondition().
value()
QVariant AbstractCondition::value () inline protected inherited
References AbstractCondition::v.
Referenced by EqualCondition::eval(), GreaterCondition::eval(), NotCondition::eval(), and SmallerCondition::eval().
Member Data Documentation
cl
QList<AbstractCondition*> AndCondition::cl private
Referenced by addCondition(), and eval().
initialized
bool AbstractCondition::initialized private inherited
Referenced by AbstractCondition::update().
m
ValueModel* AbstractCondition::m private inherited
Referenced by AbstractCondition::AbstractCondition(), AbstractCondition::model(), and AbstractCondition::name().
met
bool AbstractCondition::met private inherited
Referenced by AbstractCondition::result(), and AbstractCondition::update().
v
QVariant AbstractCondition::v private inherited
Referenced by AbstractCondition::value().
The documentation for this class was generated from the following files:
src/app/control/andcondition.h
src/app/control/andcondition.cpp