FalconView: Geom_HelixData Class Reference
Geom_HelixData Class Reference
Defines data elements that can be reused for both common.
#include <Geom_HelixData.h>
Public Member Functions
Geom_HelixData ()
bool MakeHelix (const Geom_HelixData &theSource, Handle(Geom_BSplineCurve)&theTarget)
double Pitch () const
const gp_Ax3 & Position () const
double RangeMax () const
double RangeMin () const
double ScaleFactor () const
void setPitch (double p)
void setPosition (const gp_Ax3 &pos)
void setRadius (double r)
void setRangeMax (double r)
void setScaleFactor (double f)
double Taper () const
double XRadius () const
double YRadius () const
Private Attributes
double myPitch
gp_Ax3 myPosition
double myRangeMax
double myRangeMin
double myScaleFactor
double myTaper
double myXRadius
double myYRadius
Detailed Description
Defines data elements that can be reused for both common.
Constructor & Destructor Documentation
Geom_HelixData()
Geom_HelixData::Geom_HelixData () inline
Member Function Documentation
MakeHelix()
bool Geom_HelixData::MakeHelix (const Geom_HelixData & theSource, Handle(Geom_BSplineCurve)& theTarget)
Uses adaptor classes and invokes GeomConvert_ApproxCurve to approximate with a B-Spline. Created B-Spline is polynomial and is of C2-continuity. Returns true if the B-Spline has been successfully created and false otherwise.
References Handle().
Pitch()
double Geom_HelixData::Pitch () const inline
References myPitch.
Referenced by HelixCurveAdaptor_CylinderEvaluator::HelixCurveAdaptor_CylinderEvaluator().
Position()
const gp_Ax3& Geom_HelixData::Position () const inline
References myPosition.
Referenced by HelixCurveAdaptor::Evaluator::Loc(), HelixCurveAdaptor::Evaluator::XDir(), HelixCurveAdaptor::Evaluator::YDir(), and HelixCurveAdaptor::Evaluator::ZDir().
RangeMax()
double Geom_HelixData::RangeMax () const inline
References myRangeMax.
RangeMin()
double Geom_HelixData::RangeMin () const inline
References myRangeMin.
ScaleFactor()
double Geom_HelixData::ScaleFactor () const inline
References myScaleFactor.
Referenced by HelixCurveAdaptor_CylinderEvaluator::HelixCurveAdaptor_CylinderEvaluator().
setPitch()
void Geom_HelixData::setPitch (double p) inline
References myPitch.
setPosition()
void Geom_HelixData::setPosition (const gp_Ax3 & pos) inline
References myPosition.
setRadius()
void Geom_HelixData::setRadius (double r) inline
References myXRadius, and myYRadius.
setRangeMax()
void Geom_HelixData::setRangeMax (double r) inline
References myRangeMax.
setScaleFactor()
void Geom_HelixData::setScaleFactor (double f) inline
References myScaleFactor.
Taper()
double Geom_HelixData::Taper () const inline
References myTaper.
Referenced by HelixCurveAdaptor::HelixCurveAdaptor().
XRadius()
double Geom_HelixData::XRadius () const inline
References myXRadius.
Referenced by HelixCurveAdaptor_CylinderEvaluator::D0(), HelixCurveAdaptor_CylinderEvaluator::D1(), and HelixCurveAdaptor_CylinderEvaluator::D2().
YRadius()
double Geom_HelixData::YRadius () const inline
References myYRadius.
Referenced by HelixCurveAdaptor_CylinderEvaluator::D0(), HelixCurveAdaptor_CylinderEvaluator::D1(), and HelixCurveAdaptor_CylinderEvaluator::D2().
Member Data Documentation
myPitch
double Geom_HelixData::myPitch private
Referenced by Pitch(), and setPitch().
myPosition
gp_Ax3 Geom_HelixData::myPosition private
Referenced by Position(), and setPosition().
myRangeMax
double Geom_HelixData::myRangeMax private
Referenced by RangeMax(), and setRangeMax().
myRangeMin
double Geom_HelixData::myRangeMin private
Referenced by RangeMin().
myScaleFactor
double Geom_HelixData::myScaleFactor private
Referenced by ScaleFactor(), and setScaleFactor().
myTaper
double Geom_HelixData::myTaper private
Referenced by Taper().
myXRadius
double Geom_HelixData::myXRadius private
Referenced by setRadius(), and XRadius().
myYRadius
double Geom_HelixData::myYRadius private
Referenced by setRadius(), and YRadius().
The documentation for this class was generated from the following files:
src/guiLib/util/Geom_HelixData.h
src/guiLib/util/Geom_HelixData.cpp