FalconView: FlowLayout Class Reference
FlowLayout Class Reference
[0]
#include <flowlayout.h>
Public Member Functions
FlowLayout (int margin=-1, int hSpacing=-1, int vSpacing=-1)
FlowLayout (QWidget *parent, int margin=-1, int hSpacing=-1, int vSpacing=-1)
~FlowLayout ()
void addItem (QLayoutItem *item) override
int count () const override
Qt::Orientations expandingDirections () const override
bool hasHeightForWidth () const override
int heightForWidth (int) const override
int horizontalSpacing () const
QLayoutItem * itemAt (int index) const override
QSize minimumSize () const override
void setGeometry (const QRect &rect) override
QSize sizeHint () const override
QLayoutItem * takeAt (int index) override
int verticalSpacing () const
Private Member Functions
int doLayout (const QRect &rect, bool testOnly) const
int smartSpacing (QStyle::PixelMetric pm) const
Private Attributes
int hSpace
QList< QLayoutItem * > itemList
int vSpace
Detailed Description
[0]
Constructor & Destructor Documentation
FlowLayout() [1/2]
FlowLayout::FlowLayout (QWidget * parent, int margin = -1, int hSpacing = -1, int vSpacing = -1) explicit
FlowLayout() [2/2]
FlowLayout::FlowLayout (int margin = -1, int hSpacing = -1, int vSpacing = -1) explicit
~FlowLayout()
FlowLayout::~FlowLayout ()
References takeAt().
Member Function Documentation
addItem()
void FlowLayout::addItem (QLayoutItem * item) override
References itemList.
count()
int FlowLayout::count () const override
References itemList.
doLayout()
int FlowLayout::doLayout (const QRect & rect, bool testOnly) const private
References horizontalSpacing(), itemList, and verticalSpacing().
Referenced by heightForWidth(), and setGeometry().
expandingDirections()
Qt::Orientations FlowLayout::expandingDirections () const override
hasHeightForWidth()
bool FlowLayout::hasHeightForWidth () const override
heightForWidth()
int FlowLayout::heightForWidth (int width) const override
References doLayout().
horizontalSpacing()
int FlowLayout::horizontalSpacing () const
References hSpace, and smartSpacing().
Referenced by doLayout().
itemAt()
QLayoutItem * FlowLayout::itemAt (int index) const override
References itemList.
minimumSize()
QSize FlowLayout::minimumSize () const override
References itemList.
Referenced by sizeHint().
setGeometry()
void FlowLayout::setGeometry (const QRect & rect) override
References doLayout().
sizeHint()
QSize FlowLayout::sizeHint () const override
References minimumSize().
smartSpacing()
int FlowLayout::smartSpacing (QStyle::PixelMetric pm) const private
Referenced by horizontalSpacing(), and verticalSpacing().
takeAt()
QLayoutItem * FlowLayout::takeAt (int index) override
References itemList.
Referenced by ~FlowLayout().
verticalSpacing()
int FlowLayout::verticalSpacing () const
References smartSpacing(), and vSpace.
Referenced by doLayout().
Member Data Documentation
hSpace
int FlowLayout::hSpace private
Referenced by horizontalSpacing().
itemList
QList<QLayoutItem *> FlowLayout::itemList private
Referenced by addItem(), count(), doLayout(), itemAt(), minimumSize(), and takeAt().
vSpace
int FlowLayout::vSpace private
Referenced by verticalSpacing().
The documentation for this class was generated from the following files:
src/baselib/util/flowlayout.h
src/baselib/util/flowlayout.cpp