FalconView: HelpEngine Class Reference
HelpEngine Class Reference
#include <helpengine.h>
Public Member Functions
HelpEngine (const QString &helpFile, QObject *parent=nullptr)
QWidget * contentWidget ()
QString document4Keyword (const QString &keyWord) const
QByteArray fileData (const QString &file) const
QWidget * keywordWidget ()
void tellContent ()
Protected Member Functions
void buildDir (const QVector< QZipReader::FileInfo > entries)
QByteArray wrapPage (const QString &title, const QByteArray &ba) const
Private Attributes
HelpContentWidget * cw
const QString defXT
QMap< QString, int > helpDir
QMap< QString, QString > keyWords
HelpKeywordWidget * kw
int level
const QString locXT
QMap< QString, QString > pages
QZipReader * reader
Constructor & Destructor Documentation
HelpEngine()
HelpEngine::HelpEngine (const QString & helpFile, QObject * parent = nullptr) explicit
References buildDir(), cw, keyWords, kw, pages, HelpKeywordWidget::parse(), HelpContentWidget::parse(), reader, HelpContentWidget::setFolderIcon(), HelpKeywordWidget::setIcon(), and HelpContentWidget::setPageIcon().
Member Function Documentation
buildDir()
void HelpEngine::buildDir (const QVector< QZipReader::FileInfo > entries) protected
References helpDir.
Referenced by HelpEngine().
contentWidget()
QWidget * HelpEngine::contentWidget ()
References cw.
Referenced by HelpView::createContent().
document4Keyword()
QString HelpEngine::document4Keyword (const QString & keyWord) const
References keyWords.
Referenced by HelpView::help4Keyword().
fileData()
QByteArray HelpEngine::fileData (const QString & file) const
References defXT, helpDir, locXT, pages, reader, and wrapPage().
Referenced by HelpBrowser::loadResource().
keywordWidget()
QWidget * HelpEngine::keywordWidget ()
References kw.
Referenced by HelpView::createContent().
tellContent()
void HelpEngine::tellContent ()
References keyWords, pages, and reader.
wrapPage()
QByteArray HelpEngine::wrapPage (const QString & title, const QByteArray & ba) const protected
References Core::languagePrefix().
Referenced by fileData().
Member Data Documentation
cw
HelpContentWidget* HelpEngine::cw private
Referenced by HelpEngine(), and contentWidget().
defXT
const QString HelpEngine::defXT private
Referenced by fileData().
helpDir
QMap<QString, int> HelpEngine::helpDir private
Referenced by buildDir(), and fileData().
keyWords
QMap<QString, QString> HelpEngine::keyWords private
Referenced by HelpEngine(), document4Keyword(), and tellContent().
kw
HelpKeywordWidget* HelpEngine::kw private
Referenced by HelpEngine(), and keywordWidget().
level
int HelpEngine::level private
locXT
const QString HelpEngine::locXT private
Referenced by fileData().
pages
QMap<QString, QString> HelpEngine::pages private
Referenced by HelpEngine(), fileData(), and tellContent().
reader
QZipReader* HelpEngine::reader private
Referenced by HelpEngine(), fileData(), and tellContent().
The documentation for this class was generated from the following files:
src/guiLib/control/helpengine.h
src/guiLib/control/helpengine.cpp