FalconView: DynaAction Class Reference
DynaAction Class Reference
#include <dynaaction.h>
Public Slots
void setChecked (bool checked)
void setEnabled (bool enabled)
Public Member Functions
DynaAction (const QIcon &disabledIcon, const QIcon &enabledIcon, const QIcon &checkedIcon, const QString &text, AbstractCondition *cEnabled, AbstractCondition *cChecked, QObject *parent=nullptr)
Private Attributes
AbstractCondition * cChecked
AbstractCondition * cEnabled
QIcon checkedIcon
QIcon disabledIcon
QIcon enabledIcon
Constructor & Destructor Documentation
DynaAction()
DynaAction::DynaAction (const QIcon & disabledIcon, const QIcon & enabledIcon, const QIcon & checkedIcon, const QString & text, AbstractCondition * cEnabled, AbstractCondition * cChecked, QObject * parent = nullptr) explicit
References cChecked, cEnabled, AbstractCondition::conditionChanged(), AbstractCondition::result(), setChecked(), and setEnabled().
Member Function Documentation
setChecked
void DynaAction::setChecked (bool checked) slot
References checkedIcon, and enabledIcon.
Referenced by DynaAction().
setEnabled
void DynaAction::setEnabled (bool enabled) slot
References disabledIcon, and enabledIcon.
Referenced by DynaAction().
Member Data Documentation
cChecked
AbstractCondition* DynaAction::cChecked private
Referenced by DynaAction().
cEnabled
AbstractCondition* DynaAction::cEnabled private
Referenced by DynaAction().
checkedIcon
QIcon DynaAction::checkedIcon private
Referenced by setChecked().
disabledIcon
QIcon DynaAction::disabledIcon private
Referenced by setEnabled().
enabledIcon
QIcon DynaAction::enabledIcon private
Referenced by setChecked(), and setEnabled().
The documentation for this class was generated from the following files:
src/app/control/dynaaction.h
src/app/control/dynaaction.cpp