FalconView: HelixCurveAdaptor::Evaluator Class Reference
HelixCurveAdaptor::Evaluator Class Reference abstract
Base abstract class to evaluate helix.
#include <HelixCurveAdaptor_p.h>
Public Member Functions
Evaluator (const Geom_HelixData &theData)
virtual ~Evaluator ()
virtual void D0 (double U, gp_Pnt &P) const =0
virtual void D1 (double U, gp_Pnt &P, gp_Vec &V) const =0
virtual void D2 (double U, gp_Pnt &P, gp_Vec &V1, gp_Vec &V2) const =0
virtual void D3 (double U, gp_Pnt &P, gp_Vec &V1, gp_Vec &V2, gp_Vec &V3) const =0
const Geom_HelixData & Data () const
virtual gp_Vec DN (double U, Standard_Integer N) const =0
double VParameter (double U) const
Protected Member Functions
const gp_XYZ & Loc () const
const gp_XYZ & XDir () const
const gp_XYZ & YDir () const
const gp_XYZ & ZDir () const
Protected Attributes
Geom_HelixData myData
double myVCoef
Detailed Description
Base abstract class to evaluate helix.
Constructor & Destructor Documentation
Evaluator()
HelixCurveAdaptor::Evaluator::Evaluator (const Geom_HelixData & theData) inline
~Evaluator()
virtual HelixCurveAdaptor::Evaluator::~Evaluator () inline virtual
Member Function Documentation
D0()
virtual void HelixCurveAdaptor::Evaluator::D0 (double U, gp_Pnt & P) const pure virtual
Implemented in HelixCurveAdaptor_CylinderEvaluator.
D1()
virtual void HelixCurveAdaptor::Evaluator::D1 (double U, gp_Pnt & P, gp_Vec & V) const pure virtual
Implemented in HelixCurveAdaptor_CylinderEvaluator.
D2()
virtual void HelixCurveAdaptor::Evaluator::D2 (double U, gp_Pnt & P, gp_Vec & V1, gp_Vec & V2) const pure virtual
Implemented in HelixCurveAdaptor_CylinderEvaluator.
D3()
virtual void HelixCurveAdaptor::Evaluator::D3 (double U, gp_Pnt & P, gp_Vec & V1, gp_Vec & V2, gp_Vec & V3) const pure virtual
Implemented in HelixCurveAdaptor_CylinderEvaluator.
Data()
const Geom_HelixData& HelixCurveAdaptor::Evaluator::Data () const inline
References myData.
DN()
virtual gp_Vec HelixCurveAdaptor::Evaluator::DN (double U, Standard_Integer N) const pure virtual
Loc()
const gp_XYZ& HelixCurveAdaptor::Evaluator::Loc () const inline protected
References myData, and Geom_HelixData::Position().
Referenced by HelixCurveAdaptor_CylinderEvaluator::D0(), HelixCurveAdaptor_CylinderEvaluator::D1(), and HelixCurveAdaptor_CylinderEvaluator::D2().
VParameter()
double HelixCurveAdaptor::Evaluator::VParameter (double U) const inline
References myVCoef.
Referenced by HelixCurveAdaptor_CylinderEvaluator::D0(), HelixCurveAdaptor_CylinderEvaluator::D1(), and HelixCurveAdaptor_CylinderEvaluator::D2().
XDir()
const gp_XYZ& HelixCurveAdaptor::Evaluator::XDir () const inline protected
References myData, and Geom_HelixData::Position().
Referenced by HelixCurveAdaptor_CylinderEvaluator::D0(), HelixCurveAdaptor_CylinderEvaluator::D1(), and HelixCurveAdaptor_CylinderEvaluator::D2().
YDir()
const gp_XYZ& HelixCurveAdaptor::Evaluator::YDir () const inline protected
References myData, and Geom_HelixData::Position().
Referenced by HelixCurveAdaptor_CylinderEvaluator::D0(), HelixCurveAdaptor_CylinderEvaluator::D1(), and HelixCurveAdaptor_CylinderEvaluator::D2().
ZDir()
const gp_XYZ& HelixCurveAdaptor::Evaluator::ZDir () const inline protected
References myData, and Geom_HelixData::Position().
Referenced by HelixCurveAdaptor_CylinderEvaluator::D0(), HelixCurveAdaptor_CylinderEvaluator::D1(), and HelixCurveAdaptor_CylinderEvaluator::D2().
Member Data Documentation
myData
Geom_HelixData HelixCurveAdaptor::Evaluator::myData protected
Referenced by HelixCurveAdaptor_CylinderEvaluator::D0(), HelixCurveAdaptor_CylinderEvaluator::D1(), HelixCurveAdaptor_CylinderEvaluator::D2(), Data(), Loc(), XDir(), YDir(), and ZDir().
myVCoef
double HelixCurveAdaptor::Evaluator::myVCoef protected
Referenced by HelixCurveAdaptor_CylinderEvaluator::HelixCurveAdaptor_CylinderEvaluator(), HelixCurveAdaptor_CylinderEvaluator::D1(), HelixCurveAdaptor_CylinderEvaluator::D2(), and VParameter().
The documentation for this class was generated from the following file:
src/guiLib/util/HelixCurveAdaptor_p.h