FalconView: Ally3D Class Reference
Ally3D Class Reference
#include <ally3d.h>
Public Slots
void moveCone (double x, double y, double z)
void showMachineLimits ()
void showPath (const QMap< long, Handle(AIS_InteractiveObject)> &path)
void showWorkLimits ()
Public Member Functions
Ally3D (QObject *parent=nullptr)
void setCurSegColor (const QColor &c)
void setFeedColor (const QColor &c)
void setLimitsColor (const QColor &c)
void setOcctViewer (OcctQtViewer *view3D)
void setOldSegColor (const QColor &c)
void setWorkPieceColor (const QColor &c)
Protected Slots
void highlight (const QVariant &line)
void update (const QVariant &line)
Private Member Functions
Handle (AIS_Shape) cone
Private Attributes
Quantity_Color colCurSeg
Quantity_Color colFeed
Quantity_Color colLimits
Quantity_Color colOldSeg
Quantity_Color colWorkPiece
GraphicFactory * facGraph
QMap< long, Handle(AIS_InteractiveObject)>::iterator lastSeg
OcctQtViewer * v3D
QMap< long, Handle(AIS_InteractiveObject)> workPath
Bnd_Box workPiece
Constructor & Destructor Documentation
Ally3D()
Ally3D::Ally3D (QObject * parent = nullptr) explicit
Member Function Documentation
Handle()
Ally3D::Handle (AIS_Shape) private
Referenced by highlight(), showMachineLimits(), showPath(), showWorkLimits(), and update().
highlight
void Ally3D::highlight (const QVariant & line) protected slot
References colCurSeg, colOldSeg, Handle(), lastSeg, v3D, and workPath.
Referenced by setOcctViewer().
moveCone
void Ally3D::moveCone (double x, double y, double z) slot
References v3D.
Referenced by GuiKernel::updateView().
setCurSegColor()
void Ally3D::setCurSegColor (const QColor & c)
References colCurSeg, and convertColor().
Referenced by GuiKernel::initialize().
setFeedColor()
void Ally3D::setFeedColor (const QColor & c)
References colFeed, and convertColor().
Referenced by GuiKernel::initialize().
setLimitsColor()
void Ally3D::setLimitsColor (const QColor & c)
References colLimits, and convertColor().
Referenced by GuiKernel::initialize().
setOcctViewer()
void Ally3D::setOcctViewer (OcctQtViewer * view3D)
References highlight(), update(), v3D, and ValueModel::valueChanged().
Referenced by GuiKernel::initialize().
setOldSegColor()
void Ally3D::setOldSegColor (const QColor & c)
References colOldSeg, and convertColor().
Referenced by GuiKernel::initialize().
setWorkPieceColor()
void Ally3D::setWorkPieceColor (const QColor & c)
References colWorkPiece, and convertColor().
Referenced by GuiKernel::initialize().
showMachineLimits
void Ally3D::showMachineLimits () slot
References colLimits, facGraph, Handle(), GuiCore::machineLimits(), and v3D.
Referenced by showPath().
showPath
void Ally3D::showPath (const QMap< long, Handle(AIS_InteractiveObject)> & path) slot
References colFeed, OcctQtViewer::fitAll(), Handle(), lastSeg, OcctQtViewer::setBounds(), showMachineLimits(), showWorkLimits(), v3D, workPath, and workPiece.
Referenced by GuiKernel::processGCodeFile().
showWorkLimits
void Ally3D::showWorkLimits () slot
References colWorkPiece, facGraph, Handle(), v3D, and workPiece.
Referenced by showPath().
update
void Ally3D::update (const QVariant & line) protected slot
References colCurSeg, colOldSeg, Handle(), lastSeg, v3D, and workPath.
Referenced by setOcctViewer().
Member Data Documentation
colCurSeg
Quantity_Color Ally3D::colCurSeg private
Referenced by highlight(), setCurSegColor(), and update().
colFeed
Quantity_Color Ally3D::colFeed private
Referenced by setFeedColor(), and showPath().
colLimits
Quantity_Color Ally3D::colLimits private
Referenced by setLimitsColor(), and showMachineLimits().
colOldSeg
Quantity_Color Ally3D::colOldSeg private
Referenced by highlight(), setOldSegColor(), and update().
colWorkPiece
Quantity_Color Ally3D::colWorkPiece private
Referenced by setWorkPieceColor(), and showWorkLimits().
facGraph
GraphicFactory* Ally3D::facGraph private
Referenced by showMachineLimits(), and showWorkLimits().
lastSeg
QMap<long, Handle(AIS_InteractiveObject)>::iterator Ally3D::lastSeg private
Referenced by highlight(), showPath(), and update().
v3D
OcctQtViewer* Ally3D::v3D private
Referenced by highlight(), moveCone(), setOcctViewer(), showMachineLimits(), showPath(), showWorkLimits(), and update().
workPath
QMap<long, Handle(AIS_InteractiveObject)> Ally3D::workPath private
Referenced by highlight(), showPath(), and update().
workPiece
Bnd_Box Ally3D::workPiece private
Referenced by showPath(), and showWorkLimits().
The documentation for this class was generated from the following files:
src/guiLib/util/ally3d.h
src/guiLib/util/ally3d.cpp