FalconView: ToolCategory Class Reference
ToolCategory Class Reference
#include <toolcategory.h>
Public Member Functions
ToolCategory (int id, const QString &name, ToolCategory *parent=nullptr)
void appendChild (ToolCategory *child)
ToolCategory * child (int row)
int childCount () const
int columnCount () const
QVariant data (int column) const
void dump ()
ToolCategory * parent ()
int row () const
Private Attributes
QVector< ToolCategory * > children
int id
QString name
Constructor & Destructor Documentation
ToolCategory()
ToolCategory::ToolCategory (int id, const QString & name, ToolCategory * parent = nullptr)
Member Function Documentation
appendChild()
void ToolCategory::appendChild (ToolCategory * child)
References child(), and children.
child()
ToolCategory * ToolCategory::child (int row)
References children, and row().
Referenced by appendChild().
childCount()
int ToolCategory::childCount () const
References children.
columnCount()
int ToolCategory::columnCount () const
data()
QVariant ToolCategory::data (int column) const
References id, and name.
dump()
void ToolCategory::dump ()
References name.
parent()
ToolCategory * ToolCategory::parent ()
row()
int ToolCategory::row () const
References children.
Referenced by child().
Member Data Documentation
children
QVector<ToolCategory*> ToolCategory::children private
Referenced by appendChild(), child(), childCount(), and row().
id
int ToolCategory::id private
Referenced by data().
name
QString ToolCategory::name private
Referenced by data(), and dump().
The documentation for this class was generated from the following files:
src/app/model/toolcategory.h
src/app/model/toolcategory.cpp