FalconView: PluginDialog Class Reference
PluginDialog Class Reference
#include <plugindialog.h>
Public Member Functions
PluginDialog (const QString &path, const QStringList &fileNames, QWidget *parent=nullptr)
Private Member Functions
void populateTreeWidget ()
Private Attributes
QIcon featureIcon
QIcon interfaceIcon
QLabel * label = nullptr
QPushButton * okButton = nullptr
QTreeWidget * treeWidget = nullptr
Constructor & Destructor Documentation
PluginDialog()
PluginDialog::PluginDialog (const QString & path, const QStringList & fileNames, QWidget * parent = nullptr)
References featureIcon, interfaceIcon, label, okButton, populateTreeWidget(), and treeWidget.
Member Function Documentation
populateTreeWidget()
void PluginDialog::populateTreeWidget () private
References featureIcon, interfaceIcon, GuiCore::pluggableMainPages(), GuiCore::statusInfos(), and treeWidget.
Referenced by PluginDialog().
Member Data Documentation
featureIcon
QIcon PluginDialog::featureIcon private
Referenced by PluginDialog(), and populateTreeWidget().
interfaceIcon
QIcon PluginDialog::interfaceIcon private
Referenced by PluginDialog(), and populateTreeWidget().
label
QLabel* PluginDialog::label = nullptr private
Referenced by PluginDialog().
okButton
QPushButton* PluginDialog::okButton = nullptr private
Referenced by PluginDialog().
treeWidget
QTreeWidget* PluginDialog::treeWidget = nullptr private
Referenced by PluginDialog(), and populateTreeWidget().
The documentation for this class was generated from the following files:
src/app/view/plugindialog.h
src/app/view/plugindialog.cpp