FalconView: PluginPageFactory Class Reference
PluginPageFactory Class Reference
#include <pluginpagefactory.h>
Public Member Functions
PluginPageFactory ()
virtual ~PluginPageFactory ()
AbstractCenterWidget * createCenterPage (const QString &name)
AbstractCenterWidget * createDockable (const QString &name, bool flag=false)
AbstractCenterWidget * createNotebookPage (const QString &name)
Private Attributes
Config * cfg
GuiCore * core
ValueManager * vm
Constructor & Destructor Documentation
PluginPageFactory()
PluginPageFactory::PluginPageFactory () explicit
References cfg, core, Core::kernel, GuiCore::view3D(), and vm.
~PluginPageFactory()
PluginPageFactory::~PluginPageFactory () virtual
References cfg, core, and vm.
Member Function Documentation
createCenterPage()
AbstractCenterWidget * PluginPageFactory::createCenterPage (const QString & name)
References Config::cfg, AbstractCenterWidget::initialize(), ValueManager::instance, Core::kernel, AbstractCenterWidget::patch(), and GuiCore::pluggableMainPage().
Referenced by MainWindow::createDockables(), MainWindow::createMainWidgets(), and GuiKernel::setMainWindow().
createDockable()
AbstractCenterWidget * PluginPageFactory::createDockable (const QString & name, bool flag = false)
References Config::cfg, AbstractCenterWidget::initialize(), ValueManager::instance, Core::kernel, AbstractCenterWidget::patch(), and GuiCore::statusInfo().
Referenced by MainWindow::createDockables().
createNotebookPage()
AbstractCenterWidget * PluginPageFactory::createNotebookPage (const QString & name)
References Config::cfg, AbstractCenterWidget::initialize(), ValueManager::instance, Core::kernel, AbstractCenterWidget::patch(), and GuiCore::pluggableNotebookPage().
Referenced by MainWindow::createDockables(), and MainWindow::createMainWidgets().
Member Data Documentation
cfg
Config* PluginPageFactory::cfg private
Referenced by PluginPageFactory(), and ~PluginPageFactory().
core
GuiCore* PluginPageFactory::core private
Referenced by PluginPageFactory(), and ~PluginPageFactory().
vm
ValueManager* PluginPageFactory::vm private
Referenced by PluginPageFactory(), and ~PluginPageFactory().
The documentation for this class was generated from the following files:
src/app/util/pluginpagefactory.h
src/app/util/pluginpagefactory.cpp