FalconView: StatusReader Class Reference
StatusReader Class Reference
#include <statusreader.h>
Public Slots
void update ()
Public Member Functions
StatusReader (PositionCalculator &pc, GCodeInfo &gi)
bool isActive () const
Private Member Functions
void createModels ()
Private Attributes
RCS_STAT_CHANNEL * cStatus
ErrorReader * errReader
GCodeInfo & gi
PositionCalculator & pc
EMC_STAT * status
ValueManager vm
Constructor & Destructor Documentation
StatusReader()
StatusReader::StatusReader (PositionCalculator & pc, GCodeInfo & gi)
References createModels(), cStatus, errReader, and status.
Member Function Documentation
createModels()
void StatusReader::createModels () private
References ValueManager::setValue(), and vm.
Referenced by StatusReader().
isActive()
bool StatusReader::isActive () const
References cStatus.
Referenced by GuiKernel::checkBE(), and GuiKernel::setupBackend().
update
void StatusReader::update () slot
References ErrorReader::check4Error(), cStatus, errReader, gi, pc, ValueManager::setValue(), status, PositionCalculator::update(), GCodeInfo::update(), and vm.
Referenced by GuiKernel::timerEvent().
Member Data Documentation
cStatus
RCS_STAT_CHANNEL* StatusReader::cStatus private
Referenced by StatusReader(), isActive(), and update().
errReader
ErrorReader* StatusReader::errReader private
Referenced by StatusReader(), and update().
gi
GCodeInfo& StatusReader::gi private
Referenced by update().
pc
PositionCalculator& StatusReader::pc private
Referenced by update().
status
EMC_STAT* StatusReader::status private
Referenced by StatusReader(), and update().
vm
ValueManager StatusReader::vm private
Referenced by createModels(), and update().
The documentation for this class was generated from the following files:
src/app/LC/statusreader.h
src/app/LC/statusreader.cpp