FalconView: DynFrame Class Reference
DynFrame Class Reference
#include <dynframe.h>
Public Member Functions
DynFrame (AbstractCenterWidget *cw, bool visualFrame=false, QWidget *parent=nullptr)
AbstractCenterWidget * centerWidget ()
AbstractCenterWidget * centerWidget () const
virtual void closeEvent (QCloseEvent *e) override
QString id () const
void init (const QString &fileName, const QString &name, bool addScrollArea=false)
QString name () const
QAction * viewAction ()
Private Attributes
AbstractCenterWidget * dcw
QFrame * frame
Constructor & Destructor Documentation
DynFrame()
DynFrame::DynFrame (AbstractCenterWidget * cw, bool visualFrame = false, QWidget * parent = nullptr) explicit
References dcw, and frame.
Member Function Documentation
centerWidget() [1/2]
AbstractCenterWidget* DynFrame::centerWidget () inline
References dcw.
Referenced by TestEdit::openFile().
centerWidget() [2/2]
AbstractCenterWidget* DynFrame::centerWidget () const inline
References dcw.
closeEvent()
void DynFrame::closeEvent (QCloseEvent * e) override virtual
References AbstractCenterWidget::closeEvent(), and dcw.
id()
QString DynFrame::id () const
References dcw.
init()
void DynFrame::init (const QString & fileName, const QString & name, bool addScrollArea = false)
References dcw, AbstractCenterWidget::initialize(), and name().
name()
QString DynFrame::name () const
References dcw.
Referenced by CenterView::activatePage(), and init().
viewAction()
QAction * DynFrame::viewAction ()
References dcw, and AbstractCenterWidget::viewAction().
Member Data Documentation
dcw
AbstractCenterWidget* DynFrame::dcw private
Referenced by DynFrame(), centerWidget(), closeEvent(), id(), init(), name(), and viewAction().
frame
QFrame* DynFrame::frame private
Referenced by DynFrame().
The documentation for this class was generated from the following files:
src/lcLib/view/dynframe.h
src/lcLib/view/dynframe.cpp