FalconView: PositionStatus Class Reference
PositionStatus Class Reference
#include <positionstatus.h>
Public Slots
void setAbsolute (QVariant arg=QVariant(true))
void setRelative ()
Signals
void dataChanged (AbstractCenterWidget *w, const QVariant &changed)
Public Member Functions
PositionStatus (QWidget *parent, QString ledOn, QString ledOff)
PositionStatus (QWidget *parent=nullptr)
virtual ~PositionStatus ()
virtual void closeEvent (QCloseEvent *e) override
void setAHomed (QVariant arg=QVariant(true))
void setBHomed (QVariant arg=QVariant(true))
void setCHomed (QVariant arg=QVariant(true))
void setLedStyles (QString onStyle, QString offStyle)
void setUHomed (QVariant arg=QVariant(true))
void setVHomed (QVariant arg=QVariant(true))
void setWHomed (QVariant arg=QVariant(true))
void setXHomed (QVariant arg=QVariant(true))
void setYHomed (QVariant arg=QVariant(true))
void setZHomed (QVariant arg=QVariant(true))
virtual void showEvent (QShowEvent *e) override
QAction * viewAction ()
Protected Member Functions
void connectPos (Ui::PositionForm *frm, const QString &key, Config::GuiElem e)
virtual void connectSignals () override
virtual QWidget * createContent () override
virtual QString fileName () const
virtual void initialize (const QString &name=QString())
virtual void patch (void *pk, void *pc, void *pv, void *pu=nullptr, bool flag=false)
void setActive ()
void setStyles (Ui::PositionForm *frm, const QString &s, const QFont &f, int w)
void updatePos ()
virtual void updateStyles () override
Protected Attributes
Config * cfg
GuiCore * core
ValueManager * vm
Private Attributes
Ui::PositionForm * abs
bool absolute
bool addScrollArea
AxisMask axisMask
Ui::PositionForm * dtg
Ui::PositionMain * frm
QFrame * frmAbs
QFrame * frmRel
QString ledOff
QString ledOn
Ui::PositionForm * rel
QStackedLayout * sl
QString uiFileName
QAction * vAction
Static Private Attributes
static const char * a [] = {"X", "Y", "Z", "A", "B", "C", "U", "V", "W"}
static const char * widthPat = "-10.333,333"
Constructor & Destructor Documentation
PositionStatus() [1/2]
PositionStatus::PositionStatus (QWidget * parent = nullptr)
PositionStatus() [2/2]
PositionStatus::PositionStatus (QWidget * parent, QString ledOn, QString ledOff)
~PositionStatus()
PositionStatus::~PositionStatus () virtual
Member Function Documentation
closeEvent()
void AbstractCenterWidget::closeEvent (QCloseEvent * e) override virtual inherited
Implements PluginPageInterface.
Reimplemented in HelpView, TestEdit, PreViewEditor, ToolManager, SettingsNotebook, FileManager, and LCToolTable.
Referenced by SettingsNotebook::closeEvent(), Dockable::closeEvent(), and CenterPage::closeEvent().
connectPos()
void PositionStatus::connectPos (Ui::PositionForm * frm, const QString & key, Config::GuiElem e) protected
References AbstractCenterWidget::cfg, frm, ValueManager::getModel(), Config::nameOf(), NumLabel::setValue(), ValueModel::valueChanged(), and AbstractCenterWidget::vm.
Referenced by connectSignals().
connectSignals()
void PositionStatus::connectSignals () override protected virtual
Implements PluginPageInterface.
References abs, axisMask, AbstractCenterWidget::cfg, connectPos(), dtg, frm, ValueManager::getModel(), AxisMask::joint4Axis(), Config::nameOf(), rel, setAbsolute(), setAHomed(), setBHomed(), setCHomed(), setUHomed(), setVHomed(), setWHomed(), setXHomed(), setYHomed(), setZHomed(), ValueModel::valueChanged(), and AbstractCenterWidget::vm.
createContent()
QWidget * PositionStatus::createContent () override protected virtual
Reimplemented from AbstractCenterWidget.
References abs, GuiCore::axisMask(), axisMask, AbstractCenterWidget::core, dtg, frm, frmAbs, frmRel, rel, setAHomed(), setBHomed(), setCHomed(), setRelative(), setUHomed(), setVHomed(), setWHomed(), setXHomed(), setYHomed(), setZHomed(), and sl.
dataChanged
void AbstractCenterWidget::dataChanged (AbstractCenterWidget * w, const QVariant & changed) signal inherited
Referenced by SettingsNotebook::addPage(), LCToolTable::keyPressEvent(), and LCToolTable::modelChanged().
fileName()
QString AbstractCenterWidget::fileName () const protected virtual inherited
Reimplemented in SpeedStatus, and CurCodesStatus.
References AbstractCenterWidget::uiFileName.
Referenced by AbstractCenterWidget::createContent().
initialize()
void AbstractCenterWidget::initialize (const QString & name = QString()) protected virtual inherited
References AbstractCenterWidget::cfg, PluginPageInterface::connectSignals(), AbstractCenterWidget::core, AbstractCenterWidget::createContent(), PluginPageInterface::updateStyles(), and AbstractCenterWidget::vm.
Referenced by PluginPageFactory::createCenterPage(), FixtureManager::createContent(), PluginPageFactory::createDockable(), and PluginPageFactory::createNotebookPage().
patch()
void AbstractCenterWidget::patch (void * pk, void * pc, void * pv, void * pu = nullptr, bool flag = false) protected virtual inherited
Reimplemented in SpeedStatus, CurCodesStatus, and PreViewEditor.
References AbstractCenterWidget::cfg, AbstractCenterWidget::core, Core::kernel, and AbstractCenterWidget::vm.
Referenced by PluginPageFactory::createCenterPage(), PluginPageFactory::createDockable(), PluginPageFactory::createNotebookPage(), PreViewEditor::patch(), CurCodesStatus::patch(), and SpeedStatus::patch().
setAbsolute
void PositionStatus::setAbsolute (QVariant arg = QVariant(true)) slot
References abs, absolute, and updatePos().
Referenced by connectSignals(), and setRelative().
setActive()
void PositionStatus::setActive () protected
References abs, axisMask, dtg, frm, AxisMask::hasAAxis(), AxisMask::hasBAxis(), AxisMask::hasCAxis(), AxisMask::hasUAxis(), AxisMask::hasVAxis(), AxisMask::hasWAxis(), AxisMask::hasXAxis(), AxisMask::hasYAxis(), AxisMask::hasZAxis(), and rel.
Referenced by updateStyles().
setAHomed()
void PositionStatus::setAHomed (QVariant arg = QVariant(true))
References frm, ledOff, and ledOn.
Referenced by connectSignals(), and createContent().
setBHomed()
void PositionStatus::setBHomed (QVariant arg = QVariant(true))
References frm, ledOff, and ledOn.
Referenced by connectSignals(), and createContent().
setCHomed()
void PositionStatus::setCHomed (QVariant arg = QVariant(true))
References frm, ledOff, and ledOn.
Referenced by connectSignals(), and createContent().
setLedStyles()
void PositionStatus::setLedStyles (QString onStyle, QString offStyle)
setRelative
void PositionStatus::setRelative () slot
References setAbsolute().
Referenced by createContent().
setStyles()
void PositionStatus::setStyles (Ui::PositionForm * frm, const QString & s, const QFont & f, int w) protected
References frm.
Referenced by updateStyles().
setUHomed()
void PositionStatus::setUHomed (QVariant arg = QVariant(true))
References frm, ledOff, and ledOn.
Referenced by connectSignals(), and createContent().
setVHomed()
void PositionStatus::setVHomed (QVariant arg = QVariant(true))
References frm, ledOff, and ledOn.
Referenced by connectSignals(), and createContent().
setWHomed()
void PositionStatus::setWHomed (QVariant arg = QVariant(true))
References frm, ledOff, and ledOn.
Referenced by connectSignals(), and createContent().
setXHomed()
void PositionStatus::setXHomed (QVariant arg = QVariant(true))
References frm, ledOff, and ledOn.
Referenced by connectSignals(), and createContent().
setYHomed()
void PositionStatus::setYHomed (QVariant arg = QVariant(true))
References frm, ledOff, and ledOn.
Referenced by connectSignals(), and createContent().
setZHomed()
void PositionStatus::setZHomed (QVariant arg = QVariant(true))
References frm, ledOff, and ledOn.
Referenced by connectSignals(), and createContent().
showEvent()
void AbstractCenterWidget::showEvent (QShowEvent * e) override virtual inherited
Implements PluginPageInterface.
Reimplemented in SysEventView, PreViewEditor, ToolManager, FixtureManager, TestEdit, FileManager, and SettingsNotebook.
References AbstractCenterWidget::cfg, AbstractCenterWidget::core, GuiCore::help4Keyword(), and Config::value().
Referenced by SettingsNotebook::showEvent(), PreferencesEditor::showEvent(), FileManager::showEvent(), TestEdit::showEvent(), FixtureManager::showEvent(), ToolManager::showEvent(), and MDIEditor::showEvent().
updatePos()
void PositionStatus::updatePos () protected
References absolute, frmAbs, frmRel, and sl.
Referenced by setAbsolute().
updateStyles()
void PositionStatus::updateStyles () override protected virtual
Implements PluginPageInterface.
References abs, AbstractCenterWidget::cfg, dtg, frm, ValueManager::getValue(), Config::nameOf(), rel, setActive(), setStyles(), AbstractCenterWidget::vm, and widthPat.
viewAction()
QAction * AbstractCenterWidget::viewAction () inherited
References AbstractCenterWidget::vAction.
Referenced by Dockable::viewAction(), and CenterPage::viewAction().
Member Data Documentation
a
const char * PositionStatus::a = {"X", "Y", "Z", "A", "B", "C", "U", "V", "W"} static private
abs
Ui::PositionForm* PositionStatus::abs private
Referenced by connectSignals(), createContent(), setAbsolute(), setActive(), and updateStyles().
absolute
bool PositionStatus::absolute private
Referenced by setAbsolute(), and updatePos().
addScrollArea
bool AbstractCenterWidget::addScrollArea private inherited
Referenced by AbstractCenterWidget::createContent().
axisMask
AxisMask PositionStatus::axisMask private
Referenced by connectSignals(), createContent(), and setActive().
cfg
Config* AbstractCenterWidget::cfg protected inherited
Referenced by PreferencesEditor::changeBackgroundColor(), PreferencesEditor::changeFont(), PreferencesEditor::changeForegroundColor(), LCToolTable::closeEvent(), FileManager::closeEvent(), ToolManager::closeEvent(), MDIEditor::closeEvent(), PreViewEditor::closeEvent(), TestEdit::closeEvent(), connectPos(), TestEdit::connectSignals(), PreferencesEditor::connectSignals(), CurCodesStatus::connectSignals(), connectSignals(), SpeedStatus::connectSignals(), ToolStatus::connectSignals(), LCToolTable::createContent(), FileManager::createContent(), PreferencesEditor::createContent(), ToolManager::createContent(), MDIEditor::createContent(), PreViewEditor::createContent(), SysEventView::createContent(), SettingsNotebook::currentChanged(), SysEventView::eventFilter(), AbstractCenterWidget::initialize(), AbstractCenterWidget::patch(), PreferencesEditor::previewCenterChanged(), HelpView::restoreState(), TestEdit::restoreState(), HelpView::saveState(), PreferencesEditor::setupLabels(), AbstractCenterWidget::showEvent(), SettingsNotebook::showEvent(), PreferencesEditor::statusInsideChanged(), PreferencesEditor::statusShowHelpChanged(), PreferencesEditor::statusToolMgrChanged(), TestEdit::updateStyles(), FixtureManager::updateStyles(), CurCodesStatus::updateStyles(), updateStyles(), SpeedStatus::updateStyles(), and ToolStatus::updateStyles().
core
GuiCore* AbstractCenterWidget::core protected inherited
Referenced by LCToolTable::closeEvent(), LCToolTable::connectSignals(), LCToolTable::createContent(), HelpView::createContent(), FixtureManager::createContent(), ToolManager::createContent(), JogView::createContent(), SysEventView::createContent(), createContent(), SettingsNotebook::currentChanged(), ToolManager::deleteTool(), ToolManager::editTool(), ToolManager::eventFilter(), SysEventView::eventFilter(), SpeedStatus::fastFeedChanged(), SpeedStatus::feedChanged(), AbstractCenterWidget::initialize(), JogView::jog(), JogView::jogVelChanged(), LCToolTable::keyPressEvent(), TestEdit::loadFile(), PathEditor::loadFile(), LCToolTable::modelChanged(), TestEdit::openFile(), AbstractCenterWidget::patch(), TestEdit::reallyLoadFile(), PathEditor::reallyLoadFile(), TestEdit::saveFile(), FixtureEdit::saveFixture(), ToolManager::saveToolChanges(), JogView::setupUi(), AbstractCenterWidget::showEvent(), SettingsNotebook::showEvent(), JogView::sliderChanged(), and SpeedStatus::speedChanged().
dtg
Ui::PositionForm* PositionStatus::dtg private
Referenced by connectSignals(), createContent(), setActive(), and updateStyles().
frm
Ui::PositionMain* PositionStatus::frm private
Referenced by connectPos(), connectSignals(), createContent(), setActive(), setAHomed(), setBHomed(), setCHomed(), setStyles(), setUHomed(), setVHomed(), setWHomed(), setXHomed(), setYHomed(), setZHomed(), and updateStyles().
frmAbs
QFrame* PositionStatus::frmAbs private
Referenced by createContent(), and updatePos().
frmRel
QFrame* PositionStatus::frmRel private
Referenced by createContent(), and updatePos().
ledOff
QString PositionStatus::ledOff private
Referenced by setAHomed(), setBHomed(), setCHomed(), setUHomed(), setVHomed(), setWHomed(), setXHomed(), setYHomed(), and setZHomed().
ledOn
QString PositionStatus::ledOn private
Referenced by setAHomed(), setBHomed(), setCHomed(), setUHomed(), setVHomed(), setWHomed(), setXHomed(), setYHomed(), and setZHomed().
rel
Ui::PositionForm* PositionStatus::rel private
Referenced by connectSignals(), createContent(), setActive(), and updateStyles().
sl
QStackedLayout* PositionStatus::sl private
Referenced by createContent(), and updatePos().
uiFileName
QString AbstractCenterWidget::uiFileName private inherited
Referenced by AbstractCenterWidget::fileName().
vAction
QAction* AbstractCenterWidget::vAction private inherited
Referenced by AbstractCenterWidget::viewAction().
vm
ValueManager* AbstractCenterWidget::vm protected inherited
Referenced by connectPos(), SettingsNotebook::connectSignals(), TestEdit::connectSignals(), JogView::connectSignals(), PathEditor::connectSignals(), PreViewEditor::connectSignals(), CurCodesStatus::connectSignals(), connectSignals(), SpeedStatus::connectSignals(), ToolStatus::connectSignals(), PathEditor::dirtyChanged(), SysEventView::eventFilter(), SpeedStatus::fastFeedChanged(), SpeedStatus::feedChanged(), AbstractCenterWidget::initialize(), TestEdit::loadFile(), PathEditor::loadFile(), AbstractCenterWidget::patch(), FixtureEdit::saveFixture(), JogView::setStepSize(), PreferencesEditor::setupLabels(), JogView::sliderChanged(), SpeedStatus::speedChanged(), TestEdit::updateStyles(), FixtureManager::updateStyles(), CurCodesStatus::updateStyles(), updateStyles(), SpeedStatus::updateStyles(), and ToolStatus::updateStyles().
widthPat
const char * PositionStatus::widthPat = "-10.333,333" static private
Referenced by updateStyles().
The documentation for this class was generated from the following files:
src/statusInfo/Position/positionstatus.h
src/statusInfo/Position/positionstatus.cpp