FalconView: DBConnection Class Reference
DBConnection Class Reference
#include <dbconnection.h>
Public Member Functions
DBConnection (const DBConnection &conn)
DBConnection (const QString &dbName, const QString &dbType="QSQLITE")
bool connect ()
const QString & dbName () const
const QString & dbType () const
Private Attributes
QString name
QString type
Constructor & Destructor Documentation
DBConnection() [1/2]
DBConnection::DBConnection (const QString & dbName, const QString & dbType = "QSQLITE") explicit
References dbName(), and name.
DBConnection() [2/2]
DBConnection::DBConnection (const DBConnection & conn) explicit
Member Function Documentation
connect()
bool DBConnection::connect ()
References name, and type.
Referenced by CategoryTreeModel::CategoryTreeModel(), SysEventModel::SysEventModel(), ToolCategoryModel::ToolCategoryModel(), ToolModel::ToolModel(), FalconViewDB::connect(), and FalconViewDB::createDatabase().
dbName()
const QString& DBConnection::dbName () const inline
References name.
Referenced by DBConnection(), GuiKernel::createDatabase(), GuiKernel::fileName4(), and GuiKernel::initialize().
dbType()
const QString& DBConnection::dbType () const inline
References type.
Referenced by GuiKernel::initialize().
Member Data Documentation
name
QString DBConnection::name private
Referenced by DBConnection(), connect(), and dbName().
type
QString DBConnection::type private
Referenced by connect(), and dbType().
The documentation for this class was generated from the following files:
src/baselib/util/dbconnection.h
src/baselib/util/dbconnection.cpp