FalconView: DirModel Class Reference
DirModel Class Reference
#include <dirmodel.h>
Public Member Functions
DirModel (const QString &baseDir, QObject *parent=nullptr)
~DirModel ()
int columnCount (const QModelIndex &parent=QModelIndex()) const override
QVariant data (const QModelIndex &index, int role) const override
Qt::ItemFlags flags (const QModelIndex &index) const override
DirEntry * getItem (const QModelIndex &index) const
QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const override
QModelIndex index (int row, int column, const QModelIndex &parent=QModelIndex()) const override
bool insertDirectory (const QModelIndex &parentIdx, DirEntry *entry)
QModelIndex parent (const QModelIndex &index) const override
DirEntry * root () const
int rowCount (const QModelIndex &parent=QModelIndex()) const override
bool setData (const QModelIndex &index, const QVariant &value, int role=Qt::EditRole) override
Private Member Functions
void setupModelData (const QString &baseDir, DirEntry *parent)
Private Attributes
DirEntry * rootItem
Constructor & Destructor Documentation
DirModel()
DirModel::DirModel (const QString & baseDir, QObject * parent = nullptr) explicit
References DirEntry::appendChild(), rootItem, and setupModelData().
~DirModel()
DirModel::~DirModel ()
References rootItem.
Member Function Documentation
columnCount()
int DirModel::columnCount (const QModelIndex & parent = QModelIndex()) const override
References DirEntry::columnCount(), parent(), and rootItem.
data()
QVariant DirModel::data (const QModelIndex & index, int role) const override
References DirEntry::data(), and index().
flags()
Qt::ItemFlags DirModel::flags (const QModelIndex & index) const override
References index().
getItem()
DirEntry * DirModel::getItem (const QModelIndex & index) const
References DirEntry::child(), index(), and rootItem.
Referenced by FileManager::createDirectory(), insertDirectory(), parent(), and setData().
headerData()
QVariant DirModel::headerData (int section, Qt::Orientation orientation, int role = Qt::DisplayRole) const override
References DirEntry::data(), and rootItem.
index()
QModelIndex DirModel::index (int row, int column, const QModelIndex & parent = QModelIndex()) const override
References DirEntry::child(), parent(), and rootItem.
Referenced by data(), flags(), getItem(), parent(), and setData().
insertDirectory()
bool DirModel::insertDirectory (const QModelIndex & parentIdx, DirEntry * entry)
References getItem(), DirEntry::parent(), parent(), and DirEntry::path().
Referenced by FileManager::createDirectory().
parent()
QModelIndex DirModel::parent (const QModelIndex & index) const override
References DirEntry::childNumber(), getItem(), index(), DirEntry::parent(), and rootItem.
Referenced by columnCount(), index(), insertDirectory(), rowCount(), and setupModelData().
root()
DirEntry * DirModel::root () const
References DirEntry::child(), and rootItem.
Referenced by FileManager::createDirectory().
rowCount()
int DirModel::rowCount (const QModelIndex & parent = QModelIndex()) const override
References DirEntry::childCount(), parent(), and rootItem.
setData()
bool DirModel::setData (const QModelIndex & index, const QVariant & value, int role = Qt::EditRole) override
References DirEntry::data(), getItem(), index(), DirEntry::path(), and DirEntry::setData().
Referenced by FileManager::renameDirectory().
setupModelData()
void DirModel::setupModelData (const QString & baseDir, DirEntry * parent) private
References DirEntry::appendChild(), and parent().
Referenced by DirModel().
Member Data Documentation
rootItem
DirEntry* DirModel::rootItem private
Referenced by DirModel(), ~DirModel(), columnCount(), getItem(), headerData(), index(), parent(), root(), and rowCount().
The documentation for this class was generated from the following files:
src/baselib/model/dirmodel.h
src/baselib/model/dirmodel.cpp