FalconView: LCInterface Class Reference
LCInterface Class Reference
The outer shell to linuxCNC interpreter.
#include <LCInter.h>
Public Member Functions
LCInterface (CanonIF &cif, LcProperties &lcProperties, ToolTable &toolTable)
virtual ~LCInterface ()
std::pair< QVector3D, QVector3D > machineLimits () const
void parseExt (const QString &fileName)
void parseInline (const QString &fileName)
void setupToolTable ()
Protected Member Functions
void maybeNewLine ()
void maybeNewLine (int seqNum)
int readExec (const QString &line)
Private Attributes
LCInterfaceP * p
Detailed Description
The outer shell to linuxCNC interpreter.
Constructor & Destructor Documentation
LCInterface()
LCInterface::LCInterface (CanonIF & cif, LcProperties & lcProperties, ToolTable & toolTable) explicit
References p, and LCInterfaceP::toolStatus.
~LCInterface()
LCInterface::~LCInterface () virtual
References p.
Member Function Documentation
machineLimits()
std::pair< QVector3D, QVector3D > LCInterface::machineLimits () const
References LCInterfaceP::canon, CanonIF::g5xOffset(), CanonIF::g92Offset(), CanonIF::lcProperties(), p, CanonIF::selectedOffset(), LcProperties::value(), and CanonIF::xyRotation().
maybeNewLine() [1/2]
void LCInterface::maybeNewLine () protected
References p, and LCInterfaceP::pInter.
Referenced by parseInline().
maybeNewLine() [2/2]
void LCInterface::maybeNewLine (int seqNum) protected
References LCInterfaceP::errInter, LineCodes::gCodes, LCInterfaceP::lastSeqNum, lineCodes, LineCodes::mCodes, p, LCInterfaceP::pInter, LineCodes::reset(), and LineCodes::settings.
parseExt()
void LCInterface::parseExt (const QString & fileName)
parseInline()
void LCInterface::parseInline (const QString & fileName)
References LineCodes::gCodes, LCInterfaceP::lcProperties, lineCodes, maybeNewLine(), p, LCInterfaceP::pInter, readExec(), Core::riseError(), unit(), and LcProperties::value().
Referenced by GuiKernel::processGCodeFile().
readExec()
int LCInterface::readExec (const QString & line) protected
References p, LCInterfaceP::pInter, and Core::riseError().
Referenced by parseInline().
setupToolTable()
void LCInterface::setupToolTable ()
References ToolEntry::lineNum(), p, ToolEntry::toCanon(), and LCInterfaceP::toolTable.
Referenced by GuiKernel::initialize().
Member Data Documentation
p
LCInterfaceP* LCInterface::p private
Referenced by LCInterface(), ~LCInterface(), machineLimits(), maybeNewLine(), parseInline(), readExec(), and setupToolTable().
The documentation for this class was generated from the following files:
src/app/LC/LCInter.h
src/app/LC/LCInter.cpp