FalconView: KernelInterface Class Reference
KernelInterface Class Reference abstract
#include <KernelInterface.h>
Public Member Functions
virtual void activatePage (const QString &pageName)=0
virtual int activeGCodes () const =0
virtual int activeMCodes () const =0
virtual QString activePage () const =0
virtual int axisMask () const =0
virtual void beAbortTask ()=0
virtual void beEnableBlockDelete (bool enable)=0
virtual void beEnableFlood (bool enable)=0
virtual void beEnableMist (bool enable)=0
virtual void beEnableOptionalStop (bool enable)=0
virtual void beHomeAxis (int jointNum)=0
virtual void beJogStart (int axis, double speed)=0
virtual void beJogStep (int axis, double stepSize, double speed)=0
virtual void beJogStop (int axis)=0
virtual void beLoadTaskPlan (const QString &gcodeFile)=0
virtual void beLoadToolTable (const QString &toolTableFile)=0
virtual void beSendMDICommand (const QString &command)=0
virtual void beSetAuto (int autoMode, int line)=0
virtual void beSetFeedOverride (double rate)=0
virtual void beSetRapidOverride (double rate)=0
virtual void beSetSpindle (bool enable, int speed, int direction)=0
virtual void beSetSpindleOverride (double rate)=0
virtual void beSetTaskMode (int mode)=0
virtual void beSetTaskState (int state)=0
virtual void beTaskPlanSynch ()=0
virtual bool checkBE ()=0
virtual ConfigManager * config () const =0
virtual ConfigManager * config ()=0
virtual QString curPage () const =0
virtual DBConnection * databaseConnection ()=0
virtual double defaultVelocity (int jointNum) const =0
virtual QString fileName4 (const QString &fileID) const =0
virtual void help4Keyword (const QString &keyWord)=0
virtual void initialize (DBHelper &dbAssist)=0
virtual bool isLatheMode () const =0
virtual bool isSimulator () const =0
virtual const LcProperties & lcProperties () const =0
virtual LcProperties & lcProperties ()=0
virtual QLocale locale () const =0
virtual void logSysEvent (const QString &msg)=0
virtual void logSysEvent (const SysEvent &se)=0
virtual std::pair< QVector3D, QVector3D > machineLimits () const =0
virtual QMainWindow * mainWindow ()=0
virtual double maxVelocity (int jointNum) const =0
virtual void nop () const =0
virtual PluginPageInterface * pluggableMainPage (const QString &pageID) const =0
virtual QList< QString > pluggableMainPages () const =0
virtual PluginPageInterface * pluggableNotebookPage (const QString &pageID) const =0
virtual QList< QString > pluggableNotebookPages () const =0
virtual void processAppArgs (const QStringList &args)=0
virtual void processGCodeFile (const QVariant &fileName)=0
virtual void setAppMode4PageID (const QString &pageID)=0
virtual void setMainWindow (QMainWindow *w)=0
virtual void setupBackend ()=0
virtual QLocale * setupTranslators ()=0
virtual void setViewStack (PageStack *v)=0
virtual void setWindowTitle (const QString &title)=0
virtual void showHelp () const =0
virtual QWidget * stackedPage (const QString &pageName)=0
virtual PluginPageInterface * statusInfo (const QString &infoID) const =0
virtual QList< QString > statusInfos () const =0
virtual Pos9 toolOffset () const =0
virtual ToolTable & toolTable ()=0
virtual ToolTable * toolTableModel ()=0
virtual void updateView (const QVariant &pos)=0
virtual QString version () const =0
virtual OcctQtViewer * view3D ()=0
virtual PageStack * viewStack ()=0
virtual void windowClosing (QCloseEvent *e)=0
Member Function Documentation
activatePage()
virtual void KernelInterface::activatePage (const QString & pageName) pure virtual
Implemented in GuiKernel.
Referenced by GuiCore::activatePage().
activeGCodes()
virtual int KernelInterface::activeGCodes () const pure virtual
Implemented in GuiKernel.
Referenced by GuiCore::activeGCodes().
activeMCodes()
virtual int KernelInterface::activeMCodes () const pure virtual
Implemented in GuiKernel.
Referenced by GuiCore::activeMCodes().
activePage()
virtual QString KernelInterface::activePage () const pure virtual
Implemented in GuiKernel.
Referenced by GuiCore::curPage().
axisMask()
virtual int KernelInterface::axisMask () const pure virtual
Implemented in GuiKernel.
Referenced by Core::axisMask(), and GuiCore::axisMask().
beAbortTask()
virtual void KernelInterface::beAbortTask () pure virtual
Implemented in GuiKernel.
Referenced by GuiCore::beAbortTask().
beEnableBlockDelete()
virtual void KernelInterface::beEnableBlockDelete (bool enable) pure virtual
Implemented in GuiKernel.
Referenced by GuiCore::beEnableBlockDelete().
beEnableFlood()
virtual void KernelInterface::beEnableFlood (bool enable) pure virtual
Implemented in GuiKernel.
Referenced by GuiCore::beEnableFlood().
beEnableMist()
virtual void KernelInterface::beEnableMist (bool enable) pure virtual
Implemented in GuiKernel.
Referenced by GuiCore::beEnableMist().
beEnableOptionalStop()
virtual void KernelInterface::beEnableOptionalStop (bool enable) pure virtual
Implemented in GuiKernel.
Referenced by GuiCore::beEnableOptionalStop().
beHomeAxis()
virtual void KernelInterface::beHomeAxis (int jointNum) pure virtual
Implemented in GuiKernel.
Referenced by GuiCore::beHomeAxis().
beJogStart()
virtual void KernelInterface::beJogStart (int axis, double speed) pure virtual
Implemented in GuiKernel.
Referenced by GuiCore::beJogStart().
beJogStep()
virtual void KernelInterface::beJogStep (int axis, double stepSize, double speed) pure virtual
Implemented in GuiKernel.
Referenced by GuiCore::beJogStep().
beJogStop()
virtual void KernelInterface::beJogStop (int axis) pure virtual
Implemented in GuiKernel.
Referenced by GuiCore::beJogStop().
beLoadTaskPlan()
virtual void KernelInterface::beLoadTaskPlan (const QString & gcodeFile) pure virtual
Implemented in GuiKernel.
Referenced by GuiCore::beLoadTaskPlan().
beLoadToolTable()
virtual void KernelInterface::beLoadToolTable (const QString & toolTableFile) pure virtual
Implemented in GuiKernel.
Referenced by GuiCore::beLoadToolTable().
beSendMDICommand()
virtual void KernelInterface::beSendMDICommand (const QString & command) pure virtual
Implemented in GuiKernel.
Referenced by GuiCore::beSendMDICommand().
beSetAuto()
virtual void KernelInterface::beSetAuto (int autoMode, int line) pure virtual
Implemented in GuiKernel.
Referenced by GuiCore::beSetAuto().
beSetFeedOverride()
virtual void KernelInterface::beSetFeedOverride (double rate) pure virtual
Implemented in GuiKernel.
Referenced by GuiCore::beSetFeedOverride().
beSetRapidOverride()
virtual void KernelInterface::beSetRapidOverride (double rate) pure virtual
Implemented in GuiKernel.
Referenced by GuiCore::beSetRapidOverride().
beSetSpindle()
virtual void KernelInterface::beSetSpindle (bool enable, int speed, int direction) pure virtual
Implemented in GuiKernel.
Referenced by GuiCore::beSetSpindle().
beSetSpindleOverride()
virtual void KernelInterface::beSetSpindleOverride (double rate) pure virtual
Implemented in GuiKernel.
Referenced by GuiCore::beSetSpindleOverride().
beSetTaskMode()
virtual void KernelInterface::beSetTaskMode (int mode) pure virtual
Implemented in GuiKernel.
Referenced by GuiCore::beSetTaskMode().
beSetTaskState()
virtual void KernelInterface::beSetTaskState (int state) pure virtual
Implemented in GuiKernel.
Referenced by GuiCore::beSetTaskState().
beTaskPlanSynch()
virtual void KernelInterface::beTaskPlanSynch () pure virtual
Implemented in GuiKernel.
Referenced by GuiCore::beTaskPlanSynch().
checkBE()
virtual bool KernelInterface::checkBE () pure virtual
Implemented in GuiKernel.
Referenced by GuiCore::checkBE().
config() [1/2]
virtual ConfigManager* KernelInterface::config () const pure virtual
Implemented in GuiKernel.
Referenced by Config::Config(), and Core::showHelpAtPageChange().
config() [2/2]
virtual ConfigManager* KernelInterface::config () pure virtual
Implemented in GuiKernel.
curPage()
virtual QString KernelInterface::curPage () const pure virtual
Implemented in GuiKernel.
databaseConnection()
virtual DBConnection* KernelInterface::databaseConnection () pure virtual
Implemented in GuiKernel.
Referenced by Core::databaseConnection().
defaultVelocity()
virtual double KernelInterface::defaultVelocity (int jointNum) const pure virtual
Implemented in GuiKernel.
Referenced by GuiCore::defaultVelocity().
fileName4()
virtual QString KernelInterface::fileName4 (const QString & fileID) const pure virtual
Implemented in GuiKernel.
Referenced by Core::fileName4().
help4Keyword()
virtual void KernelInterface::help4Keyword (const QString & keyWord) pure virtual
Implemented in GuiKernel.
Referenced by GuiCore::help4Keyword().
initialize()
virtual void KernelInterface::initialize (DBHelper & dbAssist) pure virtual
Implemented in GuiKernel.
Referenced by Core::Core().
isLatheMode()
virtual bool KernelInterface::isLatheMode () const pure virtual
Implemented in GuiKernel.
Referenced by GuiCore::isLatheMode().
isSimulator()
virtual bool KernelInterface::isSimulator () const pure virtual
Implemented in GuiKernel.
Referenced by Core::isSimulator().
lcProperties() [1/2]
virtual const LcProperties& KernelInterface::lcProperties () const pure virtual
Implemented in GuiKernel.
lcProperties() [2/2]
virtual LcProperties& KernelInterface::lcProperties () pure virtual
Implemented in GuiKernel.
Referenced by GuiCore::lcProperties().
locale()
virtual QLocale KernelInterface::locale () const pure virtual
Implemented in GuiKernel.
Referenced by Core::languagePrefix(), and Core::locale().
logSysEvent() [1/2]
virtual void KernelInterface::logSysEvent (const QString & msg) pure virtual
Implemented in GuiKernel.
Referenced by Core::riseError(), and GuiCore::riseError().
logSysEvent() [2/2]
virtual void KernelInterface::logSysEvent (const SysEvent & se) pure virtual
Implemented in GuiKernel.
machineLimits()
virtual std::pair<QVector3D, QVector3D> KernelInterface::machineLimits () const pure virtual
Implemented in GuiKernel.
Referenced by GuiCore::machineLimits().
mainWindow()
virtual QMainWindow* KernelInterface::mainWindow () pure virtual
Implemented in GuiKernel.
Referenced by GuiCore::mainWindow(), and GuiCore::riseError().
maxVelocity()
virtual double KernelInterface::maxVelocity (int jointNum) const pure virtual
Implemented in GuiKernel.
Referenced by GuiCore::maxVelocity().
nop()
virtual void KernelInterface::nop () const pure virtual
Implemented in GuiKernel.
pluggableMainPage()
virtual PluginPageInterface* KernelInterface::pluggableMainPage (const QString & pageID) const pure virtual
Implemented in GuiKernel.
Referenced by GuiCore::pluggableMainPage().
pluggableMainPages()
virtual QList<QString> KernelInterface::pluggableMainPages () const pure virtual
Implemented in GuiKernel.
Referenced by GuiCore::pluggableMainPages().
pluggableNotebookPage()
virtual PluginPageInterface* KernelInterface::pluggableNotebookPage (const QString & pageID) const pure virtual
Implemented in GuiKernel.
Referenced by GuiCore::pluggableNotebookPage().
pluggableNotebookPages()
virtual QList<QString> KernelInterface::pluggableNotebookPages () const pure virtual
Implemented in GuiKernel.
Referenced by GuiCore::pluggableNotebookPages().
processAppArgs()
virtual void KernelInterface::processAppArgs (const QStringList & args) pure virtual
Implemented in GuiKernel.
processGCodeFile()
virtual void KernelInterface::processGCodeFile (const QVariant & fileName) pure virtual
Implemented in GuiKernel.
setAppMode4PageID()
virtual void KernelInterface::setAppMode4PageID (const QString & pageID) pure virtual
Implemented in GuiKernel.
Referenced by GuiCore::setAppMode4PageID().
setMainWindow()
virtual void KernelInterface::setMainWindow (QMainWindow * w) pure virtual
Implemented in GuiKernel.
Referenced by GuiCore::setMainWindow().
setupBackend()
virtual void KernelInterface::setupBackend () pure virtual
Implemented in GuiKernel.
setupTranslators()
virtual QLocale* KernelInterface::setupTranslators () pure virtual
Implemented in GuiKernel.
setViewStack()
virtual void KernelInterface::setViewStack (PageStack * v) pure virtual
Implemented in GuiKernel.
Referenced by GuiCore::setViewStack().
setWindowTitle()
virtual void KernelInterface::setWindowTitle (const QString & title) pure virtual
Implemented in GuiKernel.
Referenced by GuiCore::setWindowTitle().
showHelp()
virtual void KernelInterface::showHelp () const pure virtual
Implemented in GuiKernel.
Referenced by GuiCore::showHelp().
stackedPage()
virtual QWidget* KernelInterface::stackedPage (const QString & pageName) pure virtual
Implemented in GuiKernel.
Referenced by GuiCore::stackedPage().
statusInfo()
virtual PluginPageInterface* KernelInterface::statusInfo (const QString & infoID) const pure virtual
Implemented in GuiKernel.
Referenced by GuiCore::statusInfo().
statusInfos()
virtual QList<QString> KernelInterface::statusInfos () const pure virtual
Implemented in GuiKernel.
Referenced by GuiCore::statusInfos().
toolOffset()
virtual Pos9 KernelInterface::toolOffset () const pure virtual
Implemented in GuiKernel.
toolTable()
virtual ToolTable& KernelInterface::toolTable () pure virtual
Implemented in GuiKernel.
Referenced by GuiCore::toolTable().
toolTableModel()
virtual ToolTable* KernelInterface::toolTableModel () pure virtual
Implemented in GuiKernel.
Referenced by GuiCore::toolTableModel().
updateView()
virtual void KernelInterface::updateView (const QVariant & pos) pure virtual
Implemented in GuiKernel.
version()
virtual QString KernelInterface::version () const pure virtual
Implemented in GuiKernel.
view3D()
virtual OcctQtViewer* KernelInterface::view3D () pure virtual
Implemented in GuiKernel.
Referenced by GuiCore::view3D().
viewStack()
virtual PageStack* KernelInterface::viewStack () pure virtual
Implemented in GuiKernel.
Referenced by GuiCore::viewStack().
windowClosing()
virtual void KernelInterface::windowClosing (QCloseEvent * e) pure virtual
Implemented in GuiKernel.
Referenced by GuiCore::windowClosing().
The documentation for this class was generated from the following file:
src/baselib/control/KernelInterface.h