FalconView: GCodeEditor Class Reference
GCodeEditor Class Reference
#include <gcodeeditor.h>
Public Member Functions
GCodeEditor (QWidget *parent=nullptr)
virtual ~GCodeEditor ()
void highlightCurrentLine ()
int lineNumberAreaWidth ()
bool loadFile (QVariant fileName)
int numLines () const
void paintLineNumbers (QPaintEvent *event)
Protected Member Functions
void resizeEvent (QResizeEvent *event) override
Private Slots
void updateLineNumberArea (const QRect &rect, int dy)
void updateLineNumberAreaWidth (int newBlockCount)
Private Attributes
QWidget * lineNumberArea
Constructor & Destructor Documentation
GCodeEditor()
GCodeEditor::GCodeEditor (QWidget * parent = nullptr) explicit
References highlightCurrentLine(), lineNumberArea, updateLineNumberArea(), and updateLineNumberAreaWidth().
~GCodeEditor()
GCodeEditor::~GCodeEditor () virtual
Member Function Documentation
highlightCurrentLine()
void GCodeEditor::highlightCurrentLine ()
References ValueManager::getValue().
Referenced by GCodeEditor().
lineNumberAreaWidth()
int GCodeEditor::lineNumberAreaWidth ()
Referenced by resizeEvent(), LineNumberArea::sizeHint(), and updateLineNumberAreaWidth().
loadFile()
bool GCodeEditor::loadFile (QVariant fileName)
References Core::riseError().
Referenced by TestEdit::reallyLoadFile().
numLines()
int GCodeEditor::numLines () const inline
Referenced by TestEdit::showEvent().
paintLineNumbers()
void GCodeEditor::paintLineNumbers (QPaintEvent * event)
References ValueManager::getValue(), and lineNumberArea.
Referenced by LineNumberArea::paintEvent().
resizeEvent()
void GCodeEditor::resizeEvent (QResizeEvent * event) override protected
References lineNumberArea, and lineNumberAreaWidth().
updateLineNumberArea
void GCodeEditor::updateLineNumberArea (const QRect & rect, int dy) private slot
References lineNumberArea, and updateLineNumberAreaWidth().
Referenced by GCodeEditor().
updateLineNumberAreaWidth
void GCodeEditor::updateLineNumberAreaWidth (int newBlockCount) private slot
References lineNumberAreaWidth().
Referenced by GCodeEditor(), and updateLineNumberArea().
Member Data Documentation
lineNumberArea
QWidget* GCodeEditor::lineNumberArea private
Referenced by GCodeEditor(), paintLineNumbers(), resizeEvent(), and updateLineNumberArea().
The documentation for this class was generated from the following files:
src/guiLib/view/gcodeeditor.h
src/guiLib/view/gcodeeditor.cpp