FalconView: MultiStateToolButton Class Reference
MultiStateToolButton Class Reference
#include <multistatetoolbutton.h>
Public Member Functions
MultiStateToolButton (ValueModel *vm, const QIcon &s0Icon, const QIcon &s1Icon, const QIcon &s2Icon, QWidget *parent=nullptr)
Protected Slots
void stateChanged (const QVariant &state)
Private Attributes
ValueModel * model
const QIcon & s0Icon
const QIcon & s1Icon
const QIcon & s2Icon
Constructor & Destructor Documentation
MultiStateToolButton()
MultiStateToolButton::MultiStateToolButton (ValueModel * vm, const QIcon & s0Icon, const QIcon & s1Icon, const QIcon & s2Icon, QWidget * parent = nullptr)
References model, stateChanged(), and ValueModel::valueChanged().
Member Function Documentation
stateChanged
void MultiStateToolButton::stateChanged (const QVariant & state) protected slot
References ValueModel::dump(), ValueManager::getModel(), s0Icon, s1Icon, and s2Icon.
Referenced by MultiStateToolButton().
Member Data Documentation
model
ValueModel* MultiStateToolButton::model private
Referenced by MultiStateToolButton().
s0Icon
const QIcon& MultiStateToolButton::s0Icon private
Referenced by stateChanged().
s1Icon
const QIcon& MultiStateToolButton::s1Icon private
Referenced by stateChanged().
s2Icon
const QIcon& MultiStateToolButton::s2Icon private
Referenced by stateChanged().
The documentation for this class was generated from the following files:
src/app/control/multistatetoolbutton.h
src/app/control/multistatetoolbutton.cpp