FalconView: Core Class Reference
Core Class Reference
#include <core.h>
Public Member Functions
Core ()
Core (QApplication &app, const QString &appName, DBHelper &dbAssist, const QString &group="SRD")
virtual ~Core ()=default
int axisMask () const
DBConnection * databaseConnection ()
QString fileName4 (const QString &fileID) const
bool isSimulator () const
QString languagePrefix () const
QLocale locale () const
bool move2Backup (const QString &fileName)
virtual void riseError (const QString &msg)
void setAppMode (ApplicationMode m)
void showAllButCenter (bool visible)
bool showHelpAtPageChange () const
Static Public Member Functions
static void setKernelCreator (KernelCreator *kc)
Protected Member Functions
Core (void *p)
Static Protected Attributes
static int checked = -1
static KernelCreator * kc = nullptr
static KernelInterface * kernel = nullptr
Constructor & Destructor Documentation
Core() [1/3]
Core::Core () explicit
References kernel.
Core() [2/3]
Core::Core (QApplication & app, const QString & appName, DBHelper & dbAssist, const QString & group = "SRD") explicit
References KernelInterface::initialize(), kc, kernel, and KernelCreator::kernel().
~Core()
virtual Core::~Core () virtual default
Core() [3/3]
Core::Core (void * p) explicit protected
References kernel.
Member Function Documentation
axisMask()
int Core::axisMask () const
References KernelInterface::axisMask(), and kernel.
Referenced by GET_EXTERNAL_AXIS_MASK().
databaseConnection()
DBConnection * Core::databaseConnection ()
References KernelInterface::databaseConnection(), and kernel.
Referenced by ToolManager::createContent(), and SysEventView::createContent().
fileName4()
QString Core::fileName4 (const QString & fileID) const
References KernelInterface::fileName4(), and kernel.
Referenced by HelpView::createContent().
isSimulator()
bool Core::isSimulator () const
References KernelInterface::isSimulator(), and kernel.
languagePrefix()
QString Core::languagePrefix () const
References kernel, and KernelInterface::locale().
Referenced by ToolManager::createContent(), and HelpEngine::wrapPage().
locale()
QLocale Core::locale () const
References kernel, and KernelInterface::locale().
Referenced by JogView::jogVelChanged(), and JogView::sliderChanged().
move2Backup()
bool Core::move2Backup (const QString & fileName)
Referenced by TestEdit::saveFile().
riseError()
void Core::riseError (const QString & msg) virtual
Reimplemented in GuiCore.
References kernel, KernelInterface::logSysEvent(), and ValueManager::setValue().
Referenced by SysEventModel::append(), GCodeEditor::loadFile(), LCInterface::parseInline(), and LCInterface::readExec().
setAppMode()
void Core::setAppMode (ApplicationMode m)
References ValueManager::setValue().
Referenced by TestEdit::loadFile(), TestEdit::openFile(), and PathEditor::reallyLoadFile().
setKernelCreator()
void Core::setKernelCreator (KernelCreator * kc) static
References kc.
showAllButCenter()
void Core::showAllButCenter (bool visible)
References ValueManager::setValue().
Referenced by ToolManager::editTool(), ToolManager::eventFilter(), LCToolTable::keyPressEvent(), LCToolTable::modelChanged(), ToolManager::saveToolChanges(), and ToolTable::setData().
showHelpAtPageChange()
bool Core::showHelpAtPageChange () const
References KernelInterface::config(), kernel, and ConfigManager::value().
Member Data Documentation
checked
int Core::checked = -1 static protected
kc
KernelCreator * Core::kc = nullptr static protected
Referenced by Core(), setKernelCreator(), and GuiCore::setKernelCreator().
kernel
KernelInterface * Core::kernel = nullptr static protected
Referenced by Config::Config(), Core(), GuiCore::GuiCore(), PluginPageFactory::PluginPageFactory(), GuiCore::activatePage(), GuiCore::activeGCodes(), GuiCore::activeMCodes(), axisMask(), GuiCore::axisMask(), GuiCore::beAbortTask(), GuiCore::beEnableBlockDelete(), GuiCore::beEnableFlood(), GuiCore::beEnableMist(), GuiCore::beEnableOptionalStop(), GuiCore::beHomeAxis(), GuiCore::beJogStart(), GuiCore::beJogStep(), GuiCore::beJogStop(), GuiCore::beLoadTaskPlan(), GuiCore::beLoadToolTable(), GuiCore::beSendMDICommand(), GuiCore::beSetAuto(), GuiCore::beSetFeedOverride(), GuiCore::beSetRapidOverride(), GuiCore::beSetSpindle(), GuiCore::beSetSpindleOverride(), GuiCore::beSetTaskMode(), GuiCore::beSetTaskState(), GuiCore::beTaskPlanSynch(), GuiCore::checkBE(), PluginPageFactory::createCenterPage(), PluginPageFactory::createDockable(), PluginPageFactory::createNotebookPage(), GuiCore::curPage(), databaseConnection(), GuiCore::defaultVelocity(), fileName4(), GuiCore::help4Keyword(), GuiCore::isLatheMode(), isSimulator(), languagePrefix(), GuiCore::lcProperties(), locale(), GuiCore::machineLimits(), GuiCore::mainWindow(), GuiCore::maxVelocity(), AbstractCenterWidget::patch(), GuiCore::pluggableMainPage(), GuiCore::pluggableMainPages(), GuiCore::pluggableNotebookPage(), GuiCore::pluggableNotebookPages(), riseError(), GuiCore::riseError(), GuiCore::setAppMode4PageID(), GuiCore::setMainWindow(), GuiCore::setViewStack(), GuiCore::setWindowTitle(), GuiCore::showHelp(), showHelpAtPageChange(), GuiCore::stackedPage(), GuiCore::statusInfo(), GuiCore::statusInfos(), GuiCore::toolTable(), GuiCore::toolTableModel(), GuiCore::view3D(), GuiCore::viewStack(), and GuiCore::windowClosing().
The documentation for this class was generated from the following files:
src/baselib/control/core.h
src/baselib/control/core.cpp