FalconView: Config Class Reference
Config Class Reference
#include <configacc.h>
Public Types
enum GuiElem {
ActCodes , CurSeg , DroAbs , DroDtg ,
DroRel , DroTitle , EdLinNum , Feed ,
Filename , GCode , Speed , ToolDesc ,
ToolNum , ToolNext , LineHL , FixPrompt ,
FixTitle , FixDisabledTitle , FixEdit , RapidMove ,
WorkMove , OldSeg , WorkPiece , WorkLimit ,
LastKey
}
Public Member Functions
Config ()
void beginGroup (const QString &name)
void endGroup ()
QColor getBackground (GuiElem key) const
QFont getFont (GuiElem key) const
QColor getForeground (GuiElem key) const
QString nameOf (GuiElem key) const
int numGuiElements () const
void setBackground (GuiElem key, const QColor &color)
void setFont (GuiElem key, const QFont &font)
void setForeground (GuiElem key, const QColor &color)
void setValue (const QString &key, const QVariant &value)
QVariant value (const QString &key, const QVariant &defaultValue=QVariant()) const
Private Member Functions
Config (void *p)
Static Private Attributes
static ConfigManager * cfg = nullptr
Member Enumeration Documentation
GuiElem
enum Config::GuiElem
Enumerator
ActCodes
CurSeg
DroAbs
DroDtg
DroRel
DroTitle
EdLinNum
Feed
Filename
GCode
Speed
ToolDesc
ToolNum
ToolNext
LineHL
FixPrompt
FixTitle
FixDisabledTitle
FixEdit
RapidMove
WorkMove
OldSeg
WorkPiece
WorkLimit
LastKey
Constructor & Destructor Documentation
Config() [1/2]
Config::Config () explicit
References cfg, KernelInterface::config(), and Core::kernel.
Config() [2/2]
Config::Config (void * p) explicit private
References cfg.
Member Function Documentation
beginGroup()
void Config::beginGroup (const QString & name)
References cfg, and ConfigManager::settings.
Referenced by LCToolTable::closeEvent(), FileManager::closeEvent(), ToolManager::closeEvent(), MDIEditor::closeEvent(), PreViewEditor::closeEvent(), TestEdit::closeEvent(), LCToolTable::createContent(), FileManager::createContent(), ToolManager::createContent(), MDIEditor::createContent(), PreViewEditor::createContent(), SysEventView::createContent(), SysEventView::eventFilter(), MainWindow::restoreAll(), HelpView::restoreState(), TestEdit::restoreState(), and HelpView::saveState().
endGroup()
void Config::endGroup ()
References cfg, and ConfigManager::settings.
Referenced by LCToolTable::closeEvent(), FileManager::closeEvent(), ToolManager::closeEvent(), MDIEditor::closeEvent(), PreViewEditor::closeEvent(), TestEdit::closeEvent(), HelpDockable::closeEvent(), LCToolTable::createContent(), FileManager::createContent(), ToolManager::createContent(), MDIEditor::createContent(), PreViewEditor::createContent(), SysEventView::createContent(), SysEventView::eventFilter(), MainWindow::restoreAll(), TestEdit::restoreState(), and HelpDockable::showHelp().
getBackground()
QColor Config::getBackground (GuiElem key) const
References cfg, and ConfigManager::getBackground().
Referenced by PreferencesEditor::changeBackgroundColor().
getFont()
QFont Config::getFont (GuiElem key) const
References cfg, and ConfigManager::getFont().
Referenced by PreferencesEditor::changeFont().
getForeground()
QColor Config::getForeground (GuiElem key) const
References cfg, and ConfigManager::getForeground().
Referenced by PreferencesEditor::changeForegroundColor().
nameOf()
QString Config::nameOf (GuiElem key) const
References cfg, and ConfigManager::geToString().
Referenced by PositionStatus::connectPos(), TestEdit::connectSignals(), CurCodesStatus::connectSignals(), PositionStatus::connectSignals(), SpeedStatus::connectSignals(), ToolStatus::connectSignals(), PreferencesEditor::createContent(), PreferencesEditor::setupLabels(), TestEdit::updateStyles(), FixtureManager::updateStyles(), CurCodesStatus::updateStyles(), PositionStatus::updateStyles(), SpeedStatus::updateStyles(), and ToolStatus::updateStyles().
numGuiElements()
int Config::numGuiElements () const inline
References LastKey.
Referenced by PreferencesEditor::createContent().
setBackground()
void Config::setBackground (GuiElem key, const QColor & color)
References cfg, and ConfigManager::setBackground().
Referenced by PreferencesEditor::changeBackgroundColor().
setFont()
void Config::setFont (GuiElem key, const QFont & font)
References cfg, and ConfigManager::setFont().
Referenced by PreferencesEditor::changeFont().
setForeground()
void Config::setForeground (GuiElem key, const QColor & color)
References cfg, and ConfigManager::setForeground().
Referenced by PreferencesEditor::changeForegroundColor().
setValue()
void Config::setValue (const QString & key, const QVariant & value)
References cfg, ConfigManager::setValue(), and value().
Referenced by LCToolTable::closeEvent(), FileManager::closeEvent(), ToolManager::closeEvent(), MDIEditor::closeEvent(), PreViewEditor::closeEvent(), TestEdit::closeEvent(), HelpDockable::closeEvent(), SysEventView::eventFilter(), PreferencesEditor::previewCenterChanged(), HelpView::saveState(), PreferencesEditor::statusInsideChanged(), PreferencesEditor::statusShowHelpChanged(), and PreferencesEditor::statusToolMgrChanged().
value()
QVariant Config::value (const QString & key, const QVariant & defaultValue = QVariant()) const
References cfg, and ConfigManager::value().
Referenced by PreferencesEditor::connectSignals(), LCToolTable::createContent(), FileManager::createContent(), ToolManager::createContent(), MDIEditor::createContent(), PreViewEditor::createContent(), SysEventView::createContent(), SettingsNotebook::currentChanged(), MainWindow::initialize(), TestMain::initialize(), MainWindow::restoreAll(), HelpView::restoreState(), TestEdit::restoreState(), PreferencesEditor::setupLabels(), setValue(), AbstractCenterWidget::showEvent(), SettingsNotebook::showEvent(), and HelpDockable::showHelp().
Member Data Documentation
cfg
ConfigManager * Config::cfg = nullptr static private
Referenced by Config(), beginGroup(), PluginPageFactory::createCenterPage(), PluginPageFactory::createDockable(), PluginPageFactory::createNotebookPage(), endGroup(), getBackground(), getFont(), getForeground(), nameOf(), setBackground(), setFont(), setForeground(), setValue(), and value().
The documentation for this class was generated from the following files:
src/baselib/model/configacc.h
src/baselib/model/configacc.cpp