FalconView: FalconViewDB Class Reference
FalconViewDB Class Reference
#include <falconviewdb.h>
Public Member Functions
bool connect (const QString &name)
virtual DBConnection * createDatabase (const QString &path)
virtual void createSampleData (DBConnection &conn)
DBConnection * dbConnection ()
Protected Member Functions
QVariant::Type colType4 (const QString &columnName) const
void createCategory (QSqlTableModel &model, QSqlField &fId, QSqlField &fProfile, QSqlField &fName, const QString &category)
void createSysEventSamples (DBConnection &conn)
void createToolSampleData (DBConnection &conn)
QString xml2Sql (const QString &name) const
Protected Attributes
DBConnection * conn
Private Attributes
QMap< QString, int > toolCategories
Member Function Documentation
colType4()
QVariant::Type FalconViewDB::colType4 (const QString & columnName) const protected
Referenced by createToolSampleData().
connect()
bool FalconViewDB::connect (const QString & name) virtual
Implements DBHelper.
References DBHelper::conn, and DBConnection::connect().
createCategory()
void FalconViewDB::createCategory (QSqlTableModel & model, QSqlField & fId, QSqlField & fProfile, QSqlField & fName, const QString & category) protected
References toolCategories.
Referenced by createToolSampleData().
createDatabase()
DBConnection * FalconViewDB::createDatabase (const QString & path) virtual
Implements DBHelper.
References DBHelper::conn, DBConnection::connect(), and SysEventModel::createTable().
createSampleData()
void FalconViewDB::createSampleData (DBConnection & conn) virtual
Implements DBHelper.
References DBHelper::conn, createSysEventSamples(), and createToolSampleData().
createSysEventSamples()
void FalconViewDB::createSysEventSamples (DBConnection & conn) protected
References TimeStamp::rtSequence().
Referenced by createSampleData().
createToolSampleData()
void FalconViewDB::createToolSampleData (DBConnection & conn) protected
References colType4(), createCategory(), toolCategories, and xml2Sql().
Referenced by createSampleData().
dbConnection()
DBConnection* DBHelper::dbConnection () inline inherited
References DBHelper::conn.
Referenced by GuiKernel::createDatabase(), and GuiKernel::initialize().
xml2Sql()
QString FalconViewDB::xml2Sql (const QString & name) const protected
Referenced by createToolSampleData().
Member Data Documentation
conn
DBConnection* DBHelper::conn protected inherited
Referenced by connect(), createDatabase(), createSampleData(), and DBHelper::dbConnection().
toolCategories
QMap<QString, int> FalconViewDB::toolCategories private
Referenced by createCategory(), and createToolSampleData().
The documentation for this class was generated from the following files:
src/app/model/falconviewdb.h
src/app/model/falconviewdb.cpp