FalconView: HelpDockable Class Reference
HelpDockable Class Reference
#include <helpdockable.h>
Public Member Functions
HelpDockable (HelpView *view, QWidget *parent=nullptr)
void help4Keyword (const QString &keyWord)
void showHelp ()
Protected Member Functions
void closeEvent (QCloseEvent *event) override
void keyPressEvent (QKeyEvent *event) override
Protected Attributes
HelpView * hv
Constructor & Destructor Documentation
HelpDockable()
HelpDockable::HelpDockable (HelpView * view, QWidget * parent = nullptr)
References hv.
Member Function Documentation
closeEvent()
void HelpDockable::closeEvent (QCloseEvent * event) override protected
References HelpView::closeEvent(), Config::endGroup(), hv, and Config::setValue().
help4Keyword()
void HelpDockable::help4Keyword (const QString & keyWord)
References HelpView::help4Keyword(), hv, and showHelp().
Referenced by GuiKernel::help4Keyword().
keyPressEvent()
void HelpDockable::keyPressEvent (QKeyEvent * event) override protected
showHelp()
void HelpDockable::showHelp ()
References Config::endGroup(), hv, HelpView::restoreState(), and Config::value().
Referenced by help4Keyword(), and GuiKernel::showHelp().
Member Data Documentation
hv
HelpView* HelpDockable::hv protected
Referenced by HelpDockable(), closeEvent(), help4Keyword(), and showHelp().
The documentation for this class was generated from the following files:
src/guiLib/view/helpdockable.h
src/guiLib/view/helpdockable.cpp