FalconView: DynCenterWidget Class Reference
DynCenterWidget Class Reference abstract
#include <dyncenterwidget.h>
Signals
void dataChanged (DynCenterWidget *w, const QVariant &changed)
Public Member Functions
virtual void closeEvent (QCloseEvent *e) override
void initialize ()
virtual void keyPressEvent (QKeyEvent *e) override
virtual void keyReleaseEvent (QKeyEvent *e) override
virtual void showEvent (QShowEvent *e) override
QAction * viewAction ()
Protected Member Functions
DynCenterWidget (const QString &fileName, const QString &name, bool addScrollArea=false, QWidget *parent=nullptr)
virtual void connectSignals ()=0
virtual QWidget * createContent ()
virtual void updateStyles ()=0
Private Attributes
bool addScrollArea
QString fileName
QAction * vAction
Detailed Description
loads widgets from uiFile and allows late initialization at page usage
Constructor & Destructor Documentation
DynCenterWidget()
DynCenterWidget::DynCenterWidget (const QString & fileName, const QString & name, bool addScrollArea = false, QWidget * parent = nullptr) protected
loads widgets from uiFile and allows late initialization at page usage
Member Function Documentation
closeEvent()
void DynCenterWidget::closeEvent (QCloseEvent * e) override virtual
Reimplemented in HelpView, TestEdit, ToolManager, SettingsNotebook, PreViewEditor, LCToolTable, and FileManager.
Referenced by SettingsNotebook::closeEvent(), DynDockable::closeEvent(), and DynFrame::closeEvent().
connectSignals()
virtual void DynCenterWidget::connectSignals () protected pure virtual
Implemented in ToolManager, ToolStatus, SpeedStatus, PositionStatus, CurCodesStatus, SettingsNotebook, TestEdit, SysEventView, PreViewEditor, PreferencesEditor, PathEditor, MDIEditor, LCToolTable, JogView, HelpView, FixtureManager, FileManager, FixtureEdit, and CenterView.
Referenced by initialize().
createContent()
QWidget * DynCenterWidget::createContent () protected virtual
Reimplemented in ToolManager, ToolStatus, SpeedStatus, PositionStatus, CurCodesStatus, SettingsNotebook, TestEdit, SysEventView, PreViewEditor, PreferencesEditor, MDIEditor, LCToolTable, JogView, HelpView, FixtureManager, FileManager, FixtureEdit, and CenterView.
References addScrollArea, and fileName.
Referenced by MDIEditor::createContent(), PreferencesEditor::createContent(), TestEdit::createContent(), CurCodesStatus::createContent(), SpeedStatus::createContent(), ToolStatus::createContent(), and initialize().
dataChanged
void DynCenterWidget::dataChanged (DynCenterWidget * w, const QVariant & changed) signal
Referenced by SettingsNotebook::addPage(), LCToolTable::keyPressEvent(), and LCToolTable::modelChanged().
initialize()
void DynCenterWidget::initialize ()
References connectSignals(), createContent(), and updateStyles().
Referenced by SettingsNotebook::addPage(), FixtureManager::createContent(), PreViewEditor::createContent(), PreViewEditor::createDecorations(), DynDockable::init(), and DynFrame::init().
keyPressEvent()
void DynCenterWidget::keyPressEvent (QKeyEvent * e) override virtual
Reimplemented in LCToolTable, JogView, FixtureManager, SettingsNotebook, and CenterView.
Referenced by FixtureEdit::eventFilter(), DynDockable::keyPressEvent(), DynFrame::keyPressEvent(), SettingsNotebook::keyPressEvent(), FixtureManager::keyPressEvent(), JogView::keyPressEvent(), and LCToolTable::keyPressEvent().
keyReleaseEvent()
void DynCenterWidget::keyReleaseEvent (QKeyEvent * e) override virtual
Reimplemented in LCToolTable, FileManager, FixtureEdit, and CenterView.
Referenced by DynDockable::keyReleaseEvent(), DynFrame::keyReleaseEvent(), FixtureEdit::keyReleaseEvent(), and LCToolTable::keyReleaseEvent().
showEvent()
void DynCenterWidget::showEvent (QShowEvent * e) override virtual
Reimplemented in ToolManager, TestEdit, SysEventView, PreViewEditor, FixtureManager, FileManager, and SettingsNotebook.
References Core::help4Keyword().
Referenced by PreferencesEditor::showEvent(), SettingsNotebook::showEvent(), FileManager::showEvent(), FixtureManager::showEvent(), TestEdit::showEvent(), and ToolManager::showEvent().
updateStyles()
virtual void DynCenterWidget::updateStyles () protected pure virtual
Implemented in ToolManager, ToolStatus, SpeedStatus, PositionStatus, CurCodesStatus, SettingsNotebook, TestEdit, SysEventView, PreferencesEditor, MDIEditor, LCToolTable, JogView, HelpView, FixtureManager, FileManager, FixtureEdit, and CenterView.
Referenced by initialize().
viewAction()
QAction * DynCenterWidget::viewAction ()
References vAction.
Referenced by DynDockable::viewAction(), and DynFrame::viewAction().
Member Data Documentation
addScrollArea
bool DynCenterWidget::addScrollArea private
Referenced by createContent().
fileName
QString DynCenterWidget::fileName private
Referenced by createContent().
vAction
QAction* DynCenterWidget::vAction private
Referenced by viewAction().
The documentation for this class was generated from the following files:
corelib/dyncenterwidget.h
corelib/dyncenterwidget.cpp