FalconView: MainWindow Class Reference
MainWindow Class Reference
#include <mainwindow.h>
Public Member Functions
MainWindow (QWidget *parent=nullptr)
~MainWindow ()
void initialize ()
void setAppMode (ApplicationMode am)
SettingsNotebook * settingsNotebook () const
Protected Slots
void appModeChanged (const QVariant &appMode)
void autoPause ()
void autoStart ()
void autoStop ()
void floodToggle ()
void hitPowerBtn ()
void homeAxis ()
void mistToggle ()
void setSingleStep (bool singleStep)
void showErrMessages ()
void startSpindleCCW ()
void startSpindleCW ()
void stopSpindle ()
void testTools ()
void toggleAbsolute (const QVariant &absolute)
void toggleAllButCenter ()
Protected Member Functions
void about ()
void addDockable (Qt::DockWidgetArea area, Dockable *dockable)
void closeEvent (QCloseEvent *event) override
void createActions ()
void createConnections ()
void createDockables ()
void createMainWidgets ()
void createToolBars ()
void createValueModels ()
void keyPressEvent (QKeyEvent *event) override
void keyReleaseEvent (QKeyEvent *event) override
void restoreAll ()
void setupMenu ()
void tellStates () const
Private Attributes
QAction * autoMode
QToolBar * autoTB
QAction * cfgMode
QList< Dockable * > dockables
QAction * editMode
QAction * flood
QAction * homeAll
QAction * jogMode
int line
MDIEditor * mdi
QAction * mdiMode
QAction * mist
QToolBar * modeTB
QAction * msgMode
QAction * offsets
QAction * pauseAction
QAction * power
QToolBar * powerTB
PluginPageFactory * ppFactory
bool previewIsCenter
PreViewEditor * pw
QAction * singleStep
SettingsNotebook * snb
QAction * spindleLeft
QAction * spindleOff
QAction * spindleRight
QAction * startAction
bool statusInPreview
QAction * stopAction
QToolBar * switchTB
QAction * testEditMode
QAction * tools
QToolBar * topTB
QAction * touchMode
Ui::MainWindow * ui
QAction * wheelMode
Constructor & Destructor Documentation
MainWindow()
MainWindow::MainWindow (QWidget * parent = nullptr)
~MainWindow()
MainWindow::~MainWindow ()
Member Function Documentation
about()
void MainWindow::about () protected
References OcctQtViewer::getGlInfo(), and GuiCore::view3D().
Referenced by createConnections().
addDockable()
void MainWindow::addDockable (Qt::DockWidgetArea area, Dockable * dockable) protected
References dockables, and ui.
Referenced by createDockables().
appModeChanged
void MainWindow::appModeChanged (const QVariant & appMode) protected slot
References GuiCore::activatePage(), Auto, Edit, ErrMessages, Manual, MDI, SelectFile, Settings, Touch, Wheel, and XEdit.
Referenced by createConnections().
autoPause
void MainWindow::autoPause () protected slot
References GuiCore::beSetAuto(), PreViewEditor::curLine(), ValueManager::getValue(), and pw.
Referenced by createConnections().
autoStart
void MainWindow::autoStart () protected slot
References MDIEditor::append(), Auto, GuiCore::beSendMDICommand(), GuiCore::beSetAuto(), GuiCore::beSetTaskMode(), GuiCore::beTaskPlanSynch(), MDIEditor::command(), PreViewEditor::curLine(), PreViewEditor::currentRow(), ValueManager::getValue(), mdi, MDI, pw, and GuiCore::riseError().
Referenced by createConnections().
autoStop
void MainWindow::autoStop () protected slot
References GuiCore::beAbortTask(), GuiCore::beSetTaskMode(), and GuiCore::beTaskPlanSynch().
Referenced by createConnections().
closeEvent()
void MainWindow::closeEvent (QCloseEvent * event) override protected
References GuiCore::windowClosing().
createActions()
void MainWindow::createActions () protected
References Auto, autoMode, cfgMode, Edit, editMode, flood, ValueManager::getModel(), homeAll, jogMode, Manual, MDI, mdiMode, mist, msgMode, pauseAction, power, Settings, singleStep, spindleLeft, spindleOff, spindleRight, startAction, stopAction, testEditMode, tools, Touch, touchMode, ui, Wheel, wheelMode, and XEdit.
Referenced by initialize().
createConnections()
void MainWindow::createConnections () protected
References about(), appModeChanged(), Auto, autoMode, autoPause(), autoStart(), autoStop(), OcctQtViewer::backView(), cfgMode, Edit, editMode, flood, floodToggle(), OcctQtViewer::frontView(), ValueManager::getModel(), hitPowerBtn(), homeAll, homeAxis(), OcctQtViewer::isoView(), jogMode, OcctQtViewer::leftView(), Manual, MDI, mdiMode, mist, mistToggle(), msgMode, pauseAction, power, OcctQtViewer::rightView(), setAppMode(), setSingleStep(), Settings, showErrMessages(), singleStep, spindleLeft, spindleOff, spindleRight, startAction, startSpindleCCW(), startSpindleCW(), stopAction, stopSpindle(), testEditMode, testTools(), toggleAbsolute(), toggleAllButCenter(), tools, OcctQtViewer::topView(), Touch, touchMode, ui, ValueModel::valueChanged(), Wheel, wheelMode, and XEdit.
Referenced by initialize().
createDockables()
void MainWindow::createDockables () protected
References addDockable(), SettingsNotebook::addPage(), PageStack::addPage(), OcctQtViewer::addPlugin(), PluginPageFactory::createCenterPage(), PluginPageFactory::createDockable(), PluginPageFactory::createNotebookPage(), mdi, GuiCore::pluggableMainPages(), GuiCore::pluggableNotebookPages(), ppFactory, previewIsCenter, pw, GuiCore::setViewStack(), snb, GuiCore::statusInfos(), statusInPreview, and GuiCore::view3D().
Referenced by initialize().
createMainWidgets()
void MainWindow::createMainWidgets () protected
References SettingsNotebook::addPage(), PageStack::addPage(), PluginPageFactory::createCenterPage(), PluginPageFactory::createNotebookPage(), mdi, GuiCore::pluggableMainPages(), GuiCore::pluggableNotebookPages(), ppFactory, previewIsCenter, pw, GuiCore::setViewStack(), snb, and GuiCore::view3D().
Referenced by initialize().
createToolBars()
void MainWindow::createToolBars () protected
References autoMode, autoTB, cfgMode, editMode, flood, homeAll, jogMode, mdiMode, mist, modeTB, msgMode, pauseAction, power, powerTB, singleStep, spindleLeft, spindleOff, spindleRight, startAction, stopAction, switchTB, testEditMode, tools, topTB, touchMode, ui, and wheelMode.
Referenced by initialize().
createValueModels()
void MainWindow::createValueModels () protected
References ValueManager::setValue(), and ui.
Referenced by initialize().
floodToggle
void MainWindow::floodToggle () protected slot
References GuiCore::beEnableMist(), ValueManager::getModel(), and ValueModel::getValue().
Referenced by createConnections().
hitPowerBtn
void MainWindow::hitPowerBtn () protected slot
References GuiCore::beSetTaskState().
Referenced by createConnections().
homeAxis
void MainWindow::homeAxis () protected slot
References GuiCore::beHomeAxis().
Referenced by createConnections().
initialize()
void MainWindow::initialize ()
References Auto, createActions(), createConnections(), createDockables(), createMainWidgets(), createToolBars(), createValueModels(), ppFactory, previewIsCenter, restoreAll(), setAppMode(), setupMenu(), statusInPreview, tellStates(), ui, and Config::value().
Referenced by main().
keyPressEvent()
void MainWindow::keyPressEvent (QKeyEvent * event) override protected
References Auto, Edit, homeAll, Manual, MDI, modeTB, Settings, ValueManager::setValue(), showErrMessages(), GuiCore::showHelp(), startAction, stopAction, Touch, Wheel, and XEdit.
keyReleaseEvent()
void MainWindow::keyReleaseEvent (QKeyEvent * event) override protected
mistToggle
void MainWindow::mistToggle () protected slot
References GuiCore::beEnableMist(), ValueManager::getModel(), and ValueModel::getValue().
Referenced by createConnections().
restoreAll()
void MainWindow::restoreAll () protected
References Config::beginGroup(), Config::endGroup(), and Config::value().
Referenced by initialize().
setAppMode()
void MainWindow::setAppMode (ApplicationMode am)
References ValueManager::setValue().
Referenced by createConnections(), initialize(), and showErrMessages().
setSingleStep
void MainWindow::setSingleStep (bool singleStep) protected slot
References ValueManager::setValue().
Referenced by createConnections().
settingsNotebook()
SettingsNotebook* MainWindow::settingsNotebook () const inline
References snb.
setupMenu()
void MainWindow::setupMenu () protected
References autoMode, cfgMode, editMode, jogMode, mdiMode, msgMode, testEditMode, touchMode, ui, and wheelMode.
Referenced by initialize().
showErrMessages
void MainWindow::showErrMessages () protected slot
References GuiCore::curPage(), ErrMessages, setAppMode(), and ValueManager::setValue().
Referenced by createConnections(), and keyPressEvent().
startSpindleCCW
void MainWindow::startSpindleCCW () protected slot
References GuiCore::beSetSpindle(), and ValueManager::getValue().
Referenced by createConnections().
startSpindleCW
void MainWindow::startSpindleCW () protected slot
References GuiCore::beSetSpindle(), and ValueManager::getValue().
Referenced by createConnections().
stopSpindle
void MainWindow::stopSpindle () protected slot
References GuiCore::beSetSpindle(), and ValueManager::getValue().
Referenced by createConnections().
tellStates()
void MainWindow::tellStates () const protected
References ValueModel::dump(), and ValueManager::getModel().
Referenced by initialize().
testTools
void MainWindow::testTools () protected slot
References SettingsNotebook::dump(), CenterPage::name(), PageStack::page(), PageStack::pages(), snb, and GuiCore::viewStack().
Referenced by createConnections().
toggleAbsolute
void MainWindow::toggleAbsolute (const QVariant & absolute) protected slot
References ValueManager::setValue().
Referenced by createConnections().
toggleAllButCenter
void MainWindow::toggleAllButCenter () protected slot
References autoTB, dockables, ValueManager::getModel(), ValueModel::getValue(), modeTB, powerTB, statusInPreview, switchTB, and topTB.
Referenced by createConnections().
Member Data Documentation
autoMode
QAction* MainWindow::autoMode private
Referenced by createActions(), createConnections(), createToolBars(), and setupMenu().
autoTB
QToolBar* MainWindow::autoTB private
Referenced by createToolBars(), and toggleAllButCenter().
cfgMode
QAction* MainWindow::cfgMode private
Referenced by createActions(), createConnections(), createToolBars(), and setupMenu().
dockables
QList<Dockable*> MainWindow::dockables private
Referenced by addDockable(), and toggleAllButCenter().
editMode
QAction* MainWindow::editMode private
Referenced by createActions(), createConnections(), createToolBars(), and setupMenu().
flood
QAction* MainWindow::flood private
Referenced by createActions(), createConnections(), and createToolBars().
homeAll
QAction* MainWindow::homeAll private
Referenced by createActions(), createConnections(), createToolBars(), and keyPressEvent().
jogMode
QAction* MainWindow::jogMode private
Referenced by createActions(), createConnections(), createToolBars(), and setupMenu().
line
int MainWindow::line private
mdi
MDIEditor* MainWindow::mdi private
Referenced by autoStart(), createDockables(), and createMainWidgets().
mdiMode
QAction* MainWindow::mdiMode private
Referenced by createActions(), createConnections(), createToolBars(), and setupMenu().
mist
QAction* MainWindow::mist private
Referenced by createActions(), createConnections(), and createToolBars().
modeTB
QToolBar* MainWindow::modeTB private
Referenced by createToolBars(), keyPressEvent(), and toggleAllButCenter().
msgMode
QAction* MainWindow::msgMode private
Referenced by createActions(), createConnections(), createToolBars(), and setupMenu().
offsets
QAction* MainWindow::offsets private
pauseAction
QAction* MainWindow::pauseAction private
Referenced by createActions(), createConnections(), and createToolBars().
power
QAction* MainWindow::power private
Referenced by createActions(), createConnections(), and createToolBars().
powerTB
QToolBar* MainWindow::powerTB private
Referenced by createToolBars(), and toggleAllButCenter().
ppFactory
PluginPageFactory* MainWindow::ppFactory private
Referenced by createDockables(), createMainWidgets(), and initialize().
previewIsCenter
bool MainWindow::previewIsCenter private
Referenced by createDockables(), createMainWidgets(), and initialize().
pw
PreViewEditor* MainWindow::pw private
Referenced by autoPause(), autoStart(), createDockables(), and createMainWidgets().
singleStep
QAction* MainWindow::singleStep private
Referenced by createActions(), createConnections(), and createToolBars().
snb
SettingsNotebook* MainWindow::snb private
Referenced by createDockables(), createMainWidgets(), settingsNotebook(), and testTools().
spindleLeft
QAction* MainWindow::spindleLeft private
Referenced by createActions(), createConnections(), and createToolBars().
spindleOff
QAction* MainWindow::spindleOff private
Referenced by createActions(), createConnections(), and createToolBars().
spindleRight
QAction* MainWindow::spindleRight private
Referenced by createActions(), createConnections(), and createToolBars().
startAction
QAction* MainWindow::startAction private
Referenced by createActions(), createConnections(), createToolBars(), and keyPressEvent().
statusInPreview
bool MainWindow::statusInPreview private
Referenced by createDockables(), initialize(), and toggleAllButCenter().
stopAction
QAction* MainWindow::stopAction private
Referenced by createActions(), createConnections(), createToolBars(), and keyPressEvent().
switchTB
QToolBar* MainWindow::switchTB private
Referenced by createToolBars(), and toggleAllButCenter().
testEditMode
QAction* MainWindow::testEditMode private
Referenced by createActions(), createConnections(), createToolBars(), and setupMenu().
tools
QAction* MainWindow::tools private
Referenced by createActions(), createConnections(), and createToolBars().
topTB
QToolBar* MainWindow::topTB private
Referenced by createToolBars(), and toggleAllButCenter().
touchMode
QAction* MainWindow::touchMode private
Referenced by createActions(), createConnections(), createToolBars(), and setupMenu().
ui
Ui::MainWindow* MainWindow::ui private
Referenced by addDockable(), createActions(), createConnections(), createToolBars(), createValueModels(), initialize(), and setupMenu().
wheelMode
QAction* MainWindow::wheelMode private
Referenced by createActions(), createConnections(), createToolBars(), and setupMenu().
The documentation for this class was generated from the following files:
src/app/control/mainwindow.h
src/app/control/mainwindow.cpp