FalconView: SysEvent Class Reference
SysEvent Class Reference
#include <sysevent.h>
Public Types
enum EventType {
No_Error , OperatorError , OperatorText , OperatorDisplay ,
SystemError , NMLError , NMLText , NMLDisplay ,
NMLEvent
}
Public Member Functions
SysEvent (const QString &what, EventType et=SystemError)
SysEvent (const SysEvent &o)
SysEvent (EventType et, const QString &what, const QDateTime &when)
SysEvent (EventType et, const QString &what, QObject *parent=nullptr)
SysEvent (EventType et=No_Error)
SysEvent & operator= (const SysEvent &o)
EventType type () const
const QString & what () const
long when () const
Static Public Member Functions
static QString toString (EventType t)
Private Attributes
EventType et
QString msg
long ts
Member Enumeration Documentation
EventType
enum SysEvent::EventType
Enumerator
No_Error
OperatorError
OperatorText
OperatorDisplay
SystemError
NMLError
NMLText
NMLDisplay
NMLEvent
Constructor & Destructor Documentation
SysEvent() [1/5]
SysEvent::SysEvent (EventType et = No_Error) explicit
References TimeStamp::rtSequence(), and ts.
SysEvent() [2/5]
SysEvent::SysEvent (const QString & what, EventType et = SystemError) explicit
SysEvent() [3/5]
SysEvent::SysEvent (EventType et, const QString & what, QObject * parent = nullptr) explicit
SysEvent() [4/5]
SysEvent::SysEvent (EventType et, const QString & what, const QDateTime & when) explicit
SysEvent() [5/5]
SysEvent::SysEvent (const SysEvent & o) explicit
Member Function Documentation
operator=()
SysEvent & SysEvent::operator= (const SysEvent & o)
References et, msg, and ts.
toString()
QString SysEvent::toString (EventType t) static
References NMLDisplay, NMLError, NMLEvent, NMLText, No_Error, OperatorDisplay, OperatorError, OperatorText, and SystemError.
Referenced by SysEventModel::data(), GuiCore::riseError(), and GuiKernel::timerEvent().
type()
EventType SysEvent::type () const inline
References et.
Referenced by SysEventModel::append(), GuiKernel::logSysEvent(), GuiCore::riseError(), and GuiKernel::timerEvent().
what()
const QString& SysEvent::what () const inline
References msg.
Referenced by SysEventModel::append(), GuiKernel::logSysEvent(), GuiCore::riseError(), and GuiKernel::timerEvent().
when()
long SysEvent::when () const inline
References ts.
Referenced by SysEventModel::append(), and GuiKernel::logSysEvent().
Member Data Documentation
et
EventType SysEvent::et private
Referenced by operator=(), and type().
msg
QString SysEvent::msg private
Referenced by operator=(), and what().
ts
long SysEvent::ts private
Referenced by SysEvent(), operator=(), and when().
The documentation for this class was generated from the following files:
src/baselib/model/sysevent.h
src/baselib/model/sysevent.cpp