FalconView: CommandWriter Class Reference
CommandWriter Class Reference
#include <commandwriter.h>
Public Slots
void abortTask ()
void enableBlockDelete (bool enable)
void enableFlood (bool enable)
void enableMist (bool enable)
void enableOptionalStop (bool enable)
void homeAxis (int jointNum)
void jogStart (int axis, double speed)
void jogStep (int axis, double stepSize, double speed)
void jogStop (int axis)
void loadTaskPlan (const QString &gcodeFile)
void loadToolTable (const QString &toolTableFile)
void sendMDICommand (const QString &command)
void setAuto (int autoMode, int line)
void setFeedOverride (double rate)
void setRapidOverride (double rate)
void setSpindle (bool enable, int speed, int direction)
void setSpindleOverride (double rate)
void setTaskMode (int mode)
void setTaskState (int state)
void taskPlanSynch ()
Signals
void systemEvent (const SysEvent &se)
Public Member Functions
CommandWriter (QObject *parent=nullptr)
bool isActive ()
Protected Member Functions
int sendCommand (RCS_CMD_MSG &msg)
void sleep (double seconds)
Private Attributes
RCS_CMD_CHANNEL * cCmd
RCS_STAT_CHANNEL * cStat
EMC_STAT * status
Static Private Attributes
static const double EMC_COMMAND_DELAY = 0.01
static const int EMC_COMMAND_TIMEOUT = 5.0
Constructor & Destructor Documentation
CommandWriter()
CommandWriter::CommandWriter (QObject * parent = nullptr) explicit
References cCmd, cStat, and status.
Member Function Documentation
abortTask
void CommandWriter::abortTask () slot
References sendCommand(), and systemEvent().
Referenced by GuiKernel::setupBackend().
enableBlockDelete
void CommandWriter::enableBlockDelete (bool enable) slot
References sendCommand(), and systemEvent().
Referenced by GuiKernel::setupBackend().
enableFlood
void CommandWriter::enableFlood (bool enable) slot
References sendCommand(), and systemEvent().
Referenced by GuiKernel::setupBackend().
enableMist
void CommandWriter::enableMist (bool enable) slot
References sendCommand(), and systemEvent().
Referenced by GuiKernel::setupBackend().
enableOptionalStop
void CommandWriter::enableOptionalStop (bool enable) slot
References sendCommand(), and systemEvent().
Referenced by GuiKernel::setupBackend().
homeAxis
void CommandWriter::homeAxis (int jointNum) slot
References sendCommand(), and systemEvent().
Referenced by GuiKernel::setupBackend().
isActive()
bool CommandWriter::isActive ()
References cCmd, and cStat.
Referenced by GuiKernel::checkBE(), and GuiKernel::setupBackend().
jogStart
void CommandWriter::jogStart (int axis, double speed) slot
References sendCommand(), and systemEvent().
Referenced by GuiKernel::setupBackend().
jogStep
void CommandWriter::jogStep (int axis, double stepSize, double speed) slot
References sendCommand(), and systemEvent().
Referenced by GuiKernel::setupBackend().
jogStop
void CommandWriter::jogStop (int axis) slot
References sendCommand(), and systemEvent().
Referenced by GuiKernel::setupBackend().
loadTaskPlan
void CommandWriter::loadTaskPlan (const QString & gcodeFile) slot
References sendCommand(), and systemEvent().
Referenced by GuiKernel::setupBackend().
loadToolTable
void CommandWriter::loadToolTable (const QString & toolTableFile) slot
References sendCommand(), and systemEvent().
Referenced by GuiKernel::setupBackend().
sendCommand()
int CommandWriter::sendCommand (RCS_CMD_MSG & msg) protected
References cCmd, cStat, EMC_COMMAND_DELAY, EMC_COMMAND_TIMEOUT, sleep(), and status.
Referenced by abortTask(), enableBlockDelete(), enableFlood(), enableMist(), enableOptionalStop(), homeAxis(), jogStart(), jogStep(), jogStop(), loadTaskPlan(), loadToolTable(), sendMDICommand(), setAuto(), setFeedOverride(), setRapidOverride(), setSpindle(), setSpindleOverride(), setTaskMode(), setTaskState(), and taskPlanSynch().
sendMDICommand
void CommandWriter::sendMDICommand (const QString & command) slot
References sendCommand(), and systemEvent().
Referenced by GuiKernel::setupBackend().
setAuto
void CommandWriter::setAuto (int autoMode, int line) slot
References sendCommand(), and systemEvent().
Referenced by GuiKernel::setupBackend().
setFeedOverride
void CommandWriter::setFeedOverride (double rate) slot
References sendCommand(), and systemEvent().
Referenced by GuiKernel::setupBackend().
setRapidOverride
void CommandWriter::setRapidOverride (double rate) slot
References sendCommand(), and systemEvent().
Referenced by GuiKernel::setupBackend().
setSpindle
void CommandWriter::setSpindle (bool enable, int speed, int direction) slot
References sendCommand(), and systemEvent().
Referenced by GuiKernel::setupBackend().
setSpindleOverride
void CommandWriter::setSpindleOverride (double rate) slot
References sendCommand(), and systemEvent().
Referenced by GuiKernel::setupBackend().
setTaskMode
void CommandWriter::setTaskMode (int mode) slot
References sendCommand(), and systemEvent().
Referenced by GuiKernel::setupBackend().
setTaskState
void CommandWriter::setTaskState (int state) slot
References sendCommand(), and systemEvent().
Referenced by GuiKernel::setupBackend().
sleep()
void CommandWriter::sleep (double seconds) protected
Referenced by sendCommand().
systemEvent
void CommandWriter::systemEvent (const SysEvent & se) signal
Referenced by abortTask(), enableBlockDelete(), enableFlood(), enableMist(), enableOptionalStop(), homeAxis(), jogStart(), jogStep(), jogStop(), loadTaskPlan(), loadToolTable(), sendMDICommand(), setAuto(), setFeedOverride(), setRapidOverride(), setSpindle(), setSpindleOverride(), setTaskMode(), setTaskState(), and taskPlanSynch().
taskPlanSynch
void CommandWriter::taskPlanSynch () slot
References sendCommand(), and systemEvent().
Referenced by GuiKernel::setupBackend().
Member Data Documentation
cCmd
RCS_CMD_CHANNEL* CommandWriter::cCmd private
Referenced by CommandWriter(), isActive(), and sendCommand().
cStat
RCS_STAT_CHANNEL* CommandWriter::cStat private
Referenced by CommandWriter(), isActive(), and sendCommand().
EMC_COMMAND_DELAY
const double CommandWriter::EMC_COMMAND_DELAY = 0.01 static private
Referenced by sendCommand().
EMC_COMMAND_TIMEOUT
const int CommandWriter::EMC_COMMAND_TIMEOUT = 5.0 static private
Referenced by sendCommand().
status
EMC_STAT* CommandWriter::status private
Referenced by CommandWriter(), and sendCommand().
The documentation for this class was generated from the following files:
src/app/LC/commandwriter.h
src/app/LC/commandwriter.cpp