FalconView: CanonIF Class Reference
CanonIF Class Reference
The data-storage counterpart of linuxcnc interpreter. linuxcnc interpreter uses capitalized c-functions to interact with external world.
#include <canonif.h>
Public Member Functions
CanonIF ()
CanonIF (LcProperties &lcProperties, ToolTable &toolTable)
CANON_PLANE activePlane () const
int activeSpindle () const
void appendShape (int lineNum, Handle(AIS_InteractiveObject) shape)
void changeTool (int ttIndex)
double convert (double v)
CANON_POSITION endPoint () const
Quantity_Color feedColor () const
double feedRate () const
CANON_POSITION g5xOffset (int i=0) const
CANON_POSITION g92Offset () const
GraphicFactory graphicFactory () const
bool isAdaptiveFeedEnabled () const
bool isFeedHoldActive () const
bool isFeedOverrideEnabled () const
bool isFloodActive () const
bool isMistActive () const
bool isSpeedOverrideEnabled (int spindle) const
int lastSlot () const
LcProperties & lcProperties () const
double lengthUnits () const
CANON_UNITS machineUnits () const
CANON_MOTION_MODE motionMode () const
double motionTolerance () const
double naiveTolerance () const
int nextSlot () const
QString parameterFilename () const
double posA () const
double posB () const
double posC () const
double posU () const
double posV () const
double posW () const
double posX () const
double posY () const
double posZ () const
int selectedOffset () const
void selectPlane (CANON_PLANE pl)
void selectTool (int tool)
void setEndPoint (const CANON_POSITION &p)
void setEndPoint (double x, double y, double z, double a, double b, double c, double u, double v, double w)
void setFeedColor (const QColor &c)
void setG5xOffset (int i, double x, double y, double z, double a, double b, double c, double u, double v, double w)
void setG92Offset (double x, double y, double z, double a, double b, double c, double u, double v, double w)
void setLengthUnits (CANON_UNITS u)
void setMotionMode (CANON_MOTION_MODE mode, double tol)
void setSpindleMode (int spindle, double mode)
void setToolOffset (EmcPose offset)
void setTraverseColor (const QColor &c)
void setXYRotation (double r)
CANON_DIRECTION spindleDir (int spindle) const
double spindleSpeed (int spindle) const
CANON_TOOL_TABLE toolEntry (int ttIndex)
CANON_POSITION toolOffset () const
QMap< long, Handle(AIS_InteractiveObject)> & toolPath ()
Quantity_Color traverseColor () const
double traverseRate () const
double xyRotation () const
Static Private Attributes
static CanonIFSettings * p = nullptr
Detailed Description
The data-storage counterpart of linuxcnc interpreter. linuxcnc interpreter uses capitalized c-functions to interact with external world.
Constructor & Destructor Documentation
CanonIF() [1/2]
CanonIF::CanonIF (LcProperties & lcProperties, ToolTable & toolTable)
References p.
CanonIF() [2/2]
CanonIF::CanonIF ()
References p.
Member Function Documentation
activePlane()
CANON_PLANE CanonIF::activePlane () const
References CanonIFSettings::canon, and p.
Referenced by ARC_FEED(), and GET_EXTERNAL_PLANE().
activeSpindle()
int CanonIF::activeSpindle () const
References CanonIFSettings::canon, and p.
appendShape()
void CanonIF::appendShape (int lineNum, Handle(AIS_InteractiveObject) shape)
References p, and CanonIFSettings::toolPath.
Referenced by ARC_FEED(), STRAIGHT_FEED(), and STRAIGHT_TRAVERSE().
changeTool()
void CanonIF::changeTool (int ttIndex)
References CanonIFSettings::changeTool(), and p.
Referenced by CHANGE_TOOL().
convert()
double CanonIF::convert (double v)
endPoint()
CANON_POSITION CanonIF::endPoint () const
References CanonIFSettings::canon, and p.
Referenced by arc(), ARC_FEED(), RIGID_TAP(), STRAIGHT_FEED(), and STRAIGHT_TRAVERSE().
feedColor()
Quantity_Color CanonIF::feedColor () const
References CanonIFSettings::colFeed, and p.
Referenced by ARC_FEED(), and STRAIGHT_FEED().
feedRate()
double CanonIF::feedRate () const
References CanonIFSettings::canon, and p.
Referenced by GET_EXTERNAL_FEED_RATE().
g5xOffset()
CANON_POSITION CanonIF::g5xOffset (int i = 0) const
References CanonIFSettings::g5xOffset(), and p.
Referenced by LCInterface::machineLimits(), and GuiKernel::machineLimits().
g92Offset()
CANON_POSITION CanonIF::g92Offset () const
References CanonIFSettings::canon, and p.
Referenced by LCInterface::machineLimits(), and GuiKernel::machineLimits().
graphicFactory()
GraphicFactory CanonIF::graphicFactory () const
References CanonIFSettings::gf, and p.
Referenced by ARC_FEED(), STRAIGHT_FEED(), and STRAIGHT_TRAVERSE().
isAdaptiveFeedEnabled()
bool CanonIF::isAdaptiveFeedEnabled () const
References CanonIFSettings::adaptiveFeed, and p.
Referenced by GET_EXTERNAL_ADAPTIVE_FEED_ENABLE().
isFeedHoldActive()
bool CanonIF::isFeedHoldActive () const
References CanonIFSettings::feedHold, and p.
Referenced by GET_EXTERNAL_FEED_HOLD_ENABLE().
isFeedOverrideEnabled()
bool CanonIF::isFeedOverrideEnabled () const
References CanonIFSettings::feedOverride, and p.
Referenced by GET_EXTERNAL_FEED_OVERRIDE_ENABLE().
isFloodActive()
bool CanonIF::isFloodActive () const
References CanonIFSettings::floodActive, and p.
Referenced by GET_EXTERNAL_FLOOD().
isMistActive()
bool CanonIF::isMistActive () const
References CanonIFSettings::mistActive, and p.
Referenced by GET_EXTERNAL_MIST().
isSpeedOverrideEnabled()
bool CanonIF::isSpeedOverrideEnabled (int spindle) const
References CanonIFSettings::isSpeedOverrideEnabled(), and p.
Referenced by GET_EXTERNAL_SPINDLE_OVERRIDE_ENABLE().
lastSlot()
int CanonIF::lastSlot () const
References CanonIFSettings::changer, p, and StupidToolChangerIF::slot4ToolInSpindle().
Referenced by GET_EXTERNAL_TOOL_SLOT().
lcProperties()
LcProperties & CanonIF::lcProperties () const
References p, and CanonIFSettings::properties.
Referenced by LCInterface::machineLimits().
lengthUnits()
double CanonIF::lengthUnits () const
References CanonIFSettings::lengthUnits(), and p.
Referenced by FROM_PROG_LEN(), GET_EXTERNAL_LENGTH_UNITS(), and TO_PROG_LEN().
machineUnits()
CANON_UNITS CanonIF::machineUnits () const
References CanonIFSettings::machineUnits, and p.
Referenced by GET_EXTERNAL_LENGTH_UNIT_TYPE().
motionMode()
CANON_MOTION_MODE CanonIF::motionMode () const
References CanonIFSettings::canon, and p.
Referenced by ARC_FEED(), and GET_EXTERNAL_MOTION_CONTROL_MODE().
motionTolerance()
double CanonIF::motionTolerance () const
References CanonIFSettings::canon, and p.
Referenced by GET_EXTERNAL_MOTION_CONTROL_TOLERANCE().
naiveTolerance()
double CanonIF::naiveTolerance () const
References CanonIFSettings::canon, and p.
Referenced by ARC_FEED(), and GET_EXTERNAL_MOTION_CONTROL_NAIVECAM_TOLERANCE().
nextSlot()
int CanonIF::nextSlot () const
References CanonIFSettings::changer, StupidToolChangerIF::nextTool(), and p.
Referenced by GET_EXTERNAL_SELECTED_TOOL_SLOT().
parameterFilename()
QString CanonIF::parameterFilename () const
References p, LcProperties::parameterFileName(), and CanonIFSettings::properties.
posA()
double CanonIF::posA () const
References CanonIFSettings::canon, and p.
Referenced by GET_EXTERNAL_POSITION_A().
posB()
double CanonIF::posB () const
References CanonIFSettings::canon, and p.
Referenced by GET_EXTERNAL_POSITION_B().
posC()
double CanonIF::posC () const
References CanonIFSettings::canon, and p.
Referenced by GET_EXTERNAL_POSITION_C().
posU()
double CanonIF::posU () const
References CanonIFSettings::canon, and p.
Referenced by GET_EXTERNAL_POSITION_U().
posV()
double CanonIF::posV () const
References CanonIFSettings::canon, and p.
Referenced by GET_EXTERNAL_POSITION_V().
posW()
double CanonIF::posW () const
References CanonIFSettings::canon, and p.
Referenced by GET_EXTERNAL_POSITION_W().
posX()
double CanonIF::posX () const
References CanonIFSettings::canon, and p.
Referenced by GET_EXTERNAL_POSITION_X().
posY()
double CanonIF::posY () const
References CanonIFSettings::canon, and p.
Referenced by GET_EXTERNAL_POSITION_Y().
posZ()
double CanonIF::posZ () const
References CanonIFSettings::canon, and p.
Referenced by GET_EXTERNAL_POSITION_Z().
selectedOffset()
int CanonIF::selectedOffset () const
References p, and CanonIFSettings::selectedOffset.
Referenced by LCInterface::machineLimits().
selectPlane()
void CanonIF::selectPlane (CANON_PLANE pl)
References p, and CanonIFSettings::selectPlane().
Referenced by SELECT_PLANE().
selectTool()
void CanonIF::selectTool (int tool)
References CanonIFSettings::changer, p, and StupidToolChangerIF::selectNextTool().
Referenced by SELECT_TOOL().
setEndPoint() [1/2]
void CanonIF::setEndPoint (const CANON_POSITION & p)
References p, and CanonIFSettings::setEndPoint().
setEndPoint() [2/2]
void CanonIF::setEndPoint (double x, double y, double z, double a, double b, double c, double u, double v, double w)
References p, and CanonIFSettings::setEndPoint().
Referenced by ARC_FEED(), CANON_UPDATE_END_POINT(), RIGID_TAP(), STRAIGHT_FEED(), and STRAIGHT_TRAVERSE().
setFeedColor()
void CanonIF::setFeedColor (const QColor & c)
References p, and CanonIFSettings::setFeedColor().
Referenced by GuiKernel::initialize().
setG5xOffset()
void CanonIF::setG5xOffset (int i, double x, double y, double z, double a, double b, double c, double u, double v, double w)
References p, and CanonIFSettings::setG5xOffset().
Referenced by SET_G5X_OFFSET().
setG92Offset()
void CanonIF::setG92Offset (double x, double y, double z, double a, double b, double c, double u, double v, double w)
References p, and CanonIFSettings::setG92Offset().
Referenced by SET_G92_OFFSET().
setLengthUnits()
void CanonIF::setLengthUnits (CANON_UNITS u)
References p, and CanonIFSettings::setJobUnits().
Referenced by USE_LENGTH_UNITS().
setMotionMode()
void CanonIF::setMotionMode (CANON_MOTION_MODE mode, double tol)
References p, and CanonIFSettings::setMotionMode().
setSpindleMode()
void CanonIF::setSpindleMode (int spindle, double mode)
References p, and CanonIFSettings::setSpindleMode().
Referenced by SET_SPINDLE_MODE().
setToolOffset()
void CanonIF::setToolOffset (EmcPose offset)
References p, and CanonIFSettings::setToolOffset().
Referenced by USE_TOOL_LENGTH_OFFSET().
setTraverseColor()
void CanonIF::setTraverseColor (const QColor & c)
References p, and CanonIFSettings::setTraverseColor().
Referenced by GuiKernel::initialize().
setXYRotation()
void CanonIF::setXYRotation (double r)
References p, and CanonIFSettings::setXYRotation().
Referenced by SET_XY_ROTATION().
spindleDir()
CANON_DIRECTION CanonIF::spindleDir (int spindle) const
References p, and CanonIFSettings::spindleDir().
Referenced by GET_EXTERNAL_SPINDLE().
spindleSpeed()
double CanonIF::spindleSpeed (int spindle) const
References p, and CanonIFSettings::spindleSpeed().
Referenced by GET_EXTERNAL_SPEED().
toolEntry()
CANON_TOOL_TABLE CanonIF::toolEntry (int ttIndex)
References CanonIFSettings::canonTool(), and p.
Referenced by GET_EXTERNAL_TOOL_TABLE().
toolOffset()
CANON_POSITION CanonIF::toolOffset () const
References CanonIFSettings::canon, and p.
Referenced by GET_EXTERNAL_TOOL_LENGTH_AOFFSET(), GET_EXTERNAL_TOOL_LENGTH_BOFFSET(), GET_EXTERNAL_TOOL_LENGTH_COFFSET(), GET_EXTERNAL_TOOL_LENGTH_UOFFSET(), GET_EXTERNAL_TOOL_LENGTH_VOFFSET(), GET_EXTERNAL_TOOL_LENGTH_WOFFSET(), GET_EXTERNAL_TOOL_LENGTH_XOFFSET(), GET_EXTERNAL_TOOL_LENGTH_YOFFSET(), and GET_EXTERNAL_TOOL_LENGTH_ZOFFSET().
toolPath()
QMap< long, Handle(AIS_InteractiveObject)> & CanonIF::toolPath ()
References p, and CanonIFSettings::toolPath.
Referenced by GuiKernel::processGCodeFile().
traverseColor()
Quantity_Color CanonIF::traverseColor () const
References CanonIFSettings::colTraverse, and p.
Referenced by STRAIGHT_TRAVERSE().
traverseRate()
double CanonIF::traverseRate () const
References CanonIFSettings::iTraverseRate, and p.
Referenced by GET_EXTERNAL_TRAVERSE_RATE().
xyRotation()
double CanonIF::xyRotation () const
References CanonIFSettings::canon, and p.
Referenced by LCInterface::machineLimits(), rotate_and_offset(), rotate_and_offset_pos(), and rotate_and_offset_xyz().
Member Data Documentation
p
CanonIFSettings * CanonIF::p = nullptr static private
Referenced by CanonIF(), activePlane(), activeSpindle(), appendShape(), changeTool(), endPoint(), feedColor(), feedRate(), g5xOffset(), g92Offset(), graphicFactory(), isAdaptiveFeedEnabled(), isFeedHoldActive(), isFeedOverrideEnabled(), isFloodActive(), isMistActive(), isSpeedOverrideEnabled(), lastSlot(), lcProperties(), lengthUnits(), machineUnits(), motionMode(), motionTolerance(), naiveTolerance(), nextSlot(), parameterFilename(), posA(), posB(), posC(), posU(), posV(), posW(), posX(), posY(), posZ(), selectedOffset(), selectPlane(), selectTool(), setEndPoint(), setFeedColor(), setG5xOffset(), setG92Offset(), setLengthUnits(), setMotionMode(), setSpindleMode(), setToolOffset(), setTraverseColor(), setXYRotation(), spindleDir(), spindleSpeed(), toolEntry(), toolOffset(), toolPath(), traverseColor(), traverseRate(), and xyRotation().
The documentation for this class was generated from the following files:
src/app/LC/canonif.h
src/app/LC/canonif.cpp