FalconView: ToolEntry Class Reference
ToolEntry Class Reference
The ToolEntry class entry of linuxcnc tooltable file.
#include <toolentry.h>
Public Member Functions
ToolEntry (const ToolEntry &other)
ToolEntry (const ToolEntry *p=nullptr)
ToolEntry (int num, double length, double x, double diameter, int quadrant, double frontAngle, double backAngle, const QString &description, int slot, int lineNum)
ToolEntry (ToolEntry &&other)
~ToolEntry ()
double backAngle () const
QString description () const
double diameter () const
void dump () const
double frontAngle () const
QPixmap icon () const
double length () const
int lineNum () const
int number () const
ToolEntry & operator= (const ToolEntry &other)
int quadrant () const
void setBackAngle (double a)
void setDescription (const QString &s)
void setDiameter (double d)
void setFrontAngle (double a)
void setLength (double l)
void setPixmap (const QPixmap &icon)
void setQuadrant (int q)
void setSlot (int slot)
void setToolType (const QString &tt)
void setXOffset (double o)
int slot () const
void toCanon (CANON_TOOL_TABLE *) const
QString toLine () const
QString toolType () const
double xOffset () const
Private Attributes
PToolEntry * p
Detailed Description
The ToolEntry class entry of linuxcnc tooltable file.
Constructor & Destructor Documentation
ToolEntry() [1/4]
ToolEntry::ToolEntry (const ToolEntry * p = nullptr)
ToolEntry() [2/4]
ToolEntry::ToolEntry (int num, double length, double x, double diameter, int quadrant, double frontAngle, double backAngle, const QString & description, int slot, int lineNum)
ToolEntry() [3/4]
ToolEntry::ToolEntry (const ToolEntry & other)
ToolEntry() [4/4]
ToolEntry::ToolEntry (ToolEntry && other)
~ToolEntry()
ToolEntry::~ToolEntry ()
References p.
Member Function Documentation
backAngle()
double ToolEntry::backAngle () const
References PToolEntry::canon, and p.
Referenced by PToolEntry::PToolEntry(), ToolTable::data(), and dump().
description()
QString ToolEntry::description () const
References PToolEntry::desc, and p.
Referenced by ToolTable::data(), and dump().
diameter()
double ToolEntry::diameter () const
References PToolEntry::canon, and p.
Referenced by PToolEntry::PToolEntry(), ToolTable::data(), and dump().
dump()
void ToolEntry::dump () const
References backAngle(), description(), diameter(), frontAngle(), length(), lineNum(), number(), quadrant(), slot(), and xOffset().
frontAngle()
double ToolEntry::frontAngle () const
References PToolEntry::canon, and p.
Referenced by PToolEntry::PToolEntry(), ToolTable::data(), and dump().
icon()
QPixmap ToolEntry::icon () const
References p, and PToolEntry::pm.
Referenced by ToolTable::data().
length()
double ToolEntry::length () const
References PToolEntry::canon, and p.
Referenced by PToolEntry::PToolEntry(), ToolTable::data(), and dump().
lineNum()
int ToolEntry::lineNum () const
References p, and PToolEntry::serial.
Referenced by dump(), and LCInterface::setupToolTable().
number()
int ToolEntry::number () const
References PToolEntry::canon, and p.
Referenced by PToolEntry::PToolEntry(), ToolTable::data(), and dump().
operator=()
ToolEntry & ToolEntry::operator= (const ToolEntry & other)
References p.
quadrant()
int ToolEntry::quadrant () const
References PToolEntry::canon, and p.
Referenced by PToolEntry::PToolEntry(), ToolTable::data(), and dump().
setBackAngle()
void ToolEntry::setBackAngle (double a)
References PToolEntry::canon, PToolEntry::dirty, and p.
Referenced by ToolTable::setData().
setDescription()
void ToolEntry::setDescription (const QString & s)
References PToolEntry::desc, PToolEntry::dirty, and p.
Referenced by ToolTable::setData().
setDiameter()
void ToolEntry::setDiameter (double d)
References PToolEntry::canon, PToolEntry::dirty, and p.
Referenced by ToolTable::setData().
setFrontAngle()
void ToolEntry::setFrontAngle (double a)
References PToolEntry::canon, PToolEntry::dirty, and p.
Referenced by ToolTable::setData().
setLength()
void ToolEntry::setLength (double l)
References PToolEntry::canon, PToolEntry::dirty, and p.
Referenced by ToolTable::setData().
setPixmap()
void ToolEntry::setPixmap (const QPixmap & icon)
References p, and PToolEntry::pm.
Referenced by ToolTable::processLine().
setQuadrant()
void ToolEntry::setQuadrant (int q)
References PToolEntry::canon, PToolEntry::dirty, and p.
Referenced by ToolTable::setData().
setSlot()
void ToolEntry::setSlot (int slot)
References PToolEntry::canon, p, and slot().
Referenced by ToolTable::setData().
setToolType()
void ToolEntry::setToolType (const QString & tt)
References PToolEntry::dirty, p, and PToolEntry::tt.
Referenced by ToolTable::processLine().
setXOffset()
void ToolEntry::setXOffset (double o)
References PToolEntry::canon, PToolEntry::dirty, and p.
Referenced by ToolTable::setData().
slot()
int ToolEntry::slot () const
References PToolEntry::canon, and p.
Referenced by PToolEntry::PToolEntry(), ToolTable::data(), dump(), and setSlot().
toCanon()
void ToolEntry::toCanon (CANON_TOOL_TABLE * pCTT) const
References PToolEntry::canon, and p.
Referenced by CanonIFSettings::canonTool(), CanonIFSettings::changeTool(), and LCInterface::setupToolTable().
toLine()
QString ToolEntry::toLine () const
References PToolEntry::canon, PToolEntry::desc, p, and PToolEntry::tt.
toolType()
QString ToolEntry::toolType () const
References p, and PToolEntry::tt.
xOffset()
double ToolEntry::xOffset () const
References PToolEntry::canon, and p.
Referenced by ToolTable::data(), and dump().
Member Data Documentation
p
PToolEntry* ToolEntry::p private
Referenced by ~ToolEntry(), backAngle(), description(), diameter(), frontAngle(), icon(), length(), lineNum(), number(), operator=(), quadrant(), setBackAngle(), setDescription(), setDiameter(), setFrontAngle(), setLength(), setPixmap(), setQuadrant(), setSlot(), setToolType(), setXOffset(), slot(), toCanon(), toLine(), toolType(), and xOffset().
The documentation for this class was generated from the following files:
src/app/LC/toolentry.h
src/app/LC/toolentry.cpp