FalconView: GuiCore Class Reference
GuiCore Class Reference
#include <guicore.h>
Public Member Functions
GuiCore ()
GuiCore (QApplication &app, const QString &appName, DBHelper &dbAssist, const QString &group="SRD")
virtual ~GuiCore ()=default
void activatePage (const QString &pageName)
int activeGCodes () const
int activeMCodes () const
int axisMask () const
void beAbortTask ()
void beEnableBlockDelete (bool enable)
void beEnableFlood (bool enable)
void beEnableMist (bool enable)
void beEnableOptionalStop (bool enable)
void beHomeAxis (int jointNum)
void beJogStart (int axis, double speed)
void beJogStep (int axis, double stepSize, double speed)
void beJogStop (int axis)
void beLoadTaskPlan (const QString &gcodeFile)
void beLoadToolTable (const QString &toolTableFile)
void beSendMDICommand (const QString &command)
void beSetAuto (int autoMode, int line)
void beSetFeedOverride (double rate)
void beSetRapidOverride (double rate)
void beSetSpindle (bool enable, int speed, int direction)
void beSetSpindleOverride (double rate)
void beSetTaskMode (int mode)
void beSetTaskState (int state)
void beTaskPlanSynch ()
bool checkBE ()
QString curPage () const
DBConnection * databaseConnection ()
double defaultVelocity (int jointNum=0) const
QString fileName4 (const QString &fileID) const
void help4Keyword (const QString &keyWord)
QString helpFilename () const
bool isLatheMode () const
bool isSimulator () const
QString languagePrefix () const
LcProperties & lcProperties ()
QLocale locale () const
std::pair< QVector3D, QVector3D > machineLimits () const
QMainWindow * mainWindow ()
double maxVelocity (int jointNum=0) const
bool move2Backup (const QString &fileName)
PluginPageInterface * pluggableMainPage (const QString &pageID)
QList< QString > pluggableMainPages ()
PluginPageInterface * pluggableNotebookPage (const QString &pageID)
QList< QString > pluggableNotebookPages ()
void riseError (const QString &msg)
void setAppMode (ApplicationMode m)
void setAppMode4PageID (const QString &pageID)
void setMainWindow (QMainWindow *w)
void setViewStack (PageStack *v)
void setWindowTitle (const QString &title)
void showAllButCenter (bool visible)
void showHelp () const
bool showHelpAtPageChange () const
QWidget * stackedPage (const QString &pageName)
PluginPageInterface * statusInfo (const QString &infoID)
QList< QString > statusInfos ()
Pos9 toolOffset () const
ToolTable & toolTable ()
ToolTable * toolTableModel ()
OcctQtViewer * view3D ()
PageStack * viewStack ()
void windowClosing (QCloseEvent *e)
Static Public Member Functions
static void setKernelCreator (KernelCreator *kc)
Static Protected Attributes
static int checked = -1
static KernelCreator * kc = nullptr
static KernelInterface * kernel = nullptr
Private Member Functions
GuiCore (void *p)
Constructor & Destructor Documentation
GuiCore() [1/3]
GuiCore::GuiCore () explicit
References Core::kernel.
GuiCore() [2/3]
GuiCore::GuiCore (QApplication & app, const QString & appName, DBHelper & dbAssist, const QString & group = "SRD") explicit
~GuiCore()
virtual GuiCore::~GuiCore () virtual default
GuiCore() [3/3]
GuiCore::GuiCore (void * p) explicit private
Member Function Documentation
activatePage()
void GuiCore::activatePage (const QString & pageName)
References KernelInterface::activatePage(), and Core::kernel.
Referenced by MainWindow::appModeChanged().
activeGCodes()
int GuiCore::activeGCodes () const
References KernelInterface::activeGCodes(), and Core::kernel.
Referenced by GCodeInfo::update().
activeMCodes()
int GuiCore::activeMCodes () const
References KernelInterface::activeMCodes(), and Core::kernel.
Referenced by GCodeInfo::update().
axisMask()
int GuiCore::axisMask () const
References KernelInterface::axisMask(), and Core::kernel.
Referenced by FixtureManager::createContent(), PositionStatus::createContent(), and JogView::setupUi().
beAbortTask()
void GuiCore::beAbortTask ()
References KernelInterface::beAbortTask(), and Core::kernel.
Referenced by MainWindow::autoStop().
beEnableBlockDelete()
void GuiCore::beEnableBlockDelete (bool enable)
References KernelInterface::beEnableBlockDelete(), and Core::kernel.
beEnableFlood()
void GuiCore::beEnableFlood (bool enable)
References KernelInterface::beEnableFlood(), and Core::kernel.
beEnableMist()
void GuiCore::beEnableMist (bool enable)
References KernelInterface::beEnableMist(), and Core::kernel.
Referenced by MainWindow::floodToggle(), and MainWindow::mistToggle().
beEnableOptionalStop()
void GuiCore::beEnableOptionalStop (bool enable)
References KernelInterface::beEnableOptionalStop(), and Core::kernel.
beHomeAxis()
void GuiCore::beHomeAxis (int jointNum)
References KernelInterface::beHomeAxis(), and Core::kernel.
Referenced by MainWindow::homeAxis().
beJogStart()
void GuiCore::beJogStart (int axis, double speed)
References KernelInterface::beJogStart(), and Core::kernel.
Referenced by JogView::jog().
beJogStep()
void GuiCore::beJogStep (int axis, double stepSize, double speed)
References KernelInterface::beJogStep(), and Core::kernel.
Referenced by JogView::jog().
beJogStop()
void GuiCore::beJogStop (int axis)
References KernelInterface::beJogStop(), and Core::kernel.
Referenced by JogView::jog().
beLoadTaskPlan()
void GuiCore::beLoadTaskPlan (const QString & gcodeFile)
References KernelInterface::beLoadTaskPlan(), and Core::kernel.
Referenced by PathEditor::loadFile().
beLoadToolTable()
void GuiCore::beLoadToolTable (const QString & toolTableFile)
References KernelInterface::beLoadToolTable(), and Core::kernel.
beSendMDICommand()
void GuiCore::beSendMDICommand (const QString & command)
References KernelInterface::beSendMDICommand(), and Core::kernel.
Referenced by MainWindow::autoStart().
beSetAuto()
void GuiCore::beSetAuto (int autoMode, int line)
References KernelInterface::beSetAuto(), and Core::kernel.
Referenced by MainWindow::autoPause(), and MainWindow::autoStart().
beSetFeedOverride()
void GuiCore::beSetFeedOverride (double rate)
References KernelInterface::beSetFeedOverride(), and Core::kernel.
Referenced by SpeedStatus::feedChanged().
beSetRapidOverride()
void GuiCore::beSetRapidOverride (double rate)
References KernelInterface::beSetRapidOverride(), and Core::kernel.
Referenced by SpeedStatus::fastFeedChanged().
beSetSpindle()
void GuiCore::beSetSpindle (bool enable, int speed, int direction)
References KernelInterface::beSetSpindle(), and Core::kernel.
Referenced by MainWindow::startSpindleCCW(), MainWindow::startSpindleCW(), and MainWindow::stopSpindle().
beSetSpindleOverride()
void GuiCore::beSetSpindleOverride (double rate)
References KernelInterface::beSetSpindleOverride(), and Core::kernel.
Referenced by SpeedStatus::speedChanged().
beSetTaskMode()
void GuiCore::beSetTaskMode (int mode)
References KernelInterface::beSetTaskMode(), and Core::kernel.
Referenced by MainWindow::autoStart(), and MainWindow::autoStop().
beSetTaskState()
void GuiCore::beSetTaskState (int state)
References KernelInterface::beSetTaskState(), and Core::kernel.
Referenced by MainWindow::hitPowerBtn().
beTaskPlanSynch()
void GuiCore::beTaskPlanSynch ()
References KernelInterface::beTaskPlanSynch(), and Core::kernel.
Referenced by MainWindow::autoStart(), and MainWindow::autoStop().
checkBE()
bool GuiCore::checkBE ()
References KernelInterface::checkBE(), and Core::kernel.
Referenced by SpeedStatus::fastFeedChanged(), SpeedStatus::feedChanged(), PathEditor::loadFile(), main(), and SpeedStatus::speedChanged().
curPage()
QString GuiCore::curPage () const
References KernelInterface::activePage(), and Core::kernel.
Referenced by MainWindow::showErrMessages().
databaseConnection()
DBConnection * Core::databaseConnection () inherited
References KernelInterface::databaseConnection(), and Core::kernel.
Referenced by ToolManager::createContent(), and SysEventView::createContent().
defaultVelocity()
double GuiCore::defaultVelocity (int jointNum = 0) const
References KernelInterface::defaultVelocity(), and Core::kernel.
Referenced by JogView::createContent().
fileName4()
QString Core::fileName4 (const QString & fileID) const inherited
References KernelInterface::fileName4(), and Core::kernel.
Referenced by HelpView::createContent().
help4Keyword()
void GuiCore::help4Keyword (const QString & keyWord)
References KernelInterface::help4Keyword(), and Core::kernel.
Referenced by SettingsNotebook::currentChanged(), AbstractCenterWidget::showEvent(), and SettingsNotebook::showEvent().
helpFilename()
QString GuiCore::helpFilename () const
isLatheMode()
bool GuiCore::isLatheMode () const
References KernelInterface::isLatheMode(), and Core::kernel.
Referenced by LCToolTable::closeEvent(), and LCToolTable::createContent().
isSimulator()
bool Core::isSimulator () const inherited
References KernelInterface::isSimulator(), and Core::kernel.
languagePrefix()
QString Core::languagePrefix () const inherited
References Core::kernel, and KernelInterface::locale().
Referenced by ToolManager::createContent(), and HelpEngine::wrapPage().
lcProperties()
LcProperties & GuiCore::lcProperties ()
References Core::kernel, and KernelInterface::lcProperties().
locale()
QLocale Core::locale () const inherited
References Core::kernel, and KernelInterface::locale().
Referenced by JogView::jogVelChanged(), and JogView::sliderChanged().
machineLimits()
std::pair< QVector3D, QVector3D > GuiCore::machineLimits () const
References Core::kernel, and KernelInterface::machineLimits().
Referenced by Ally3D::showMachineLimits().
mainWindow()
QMainWindow * GuiCore::mainWindow ()
References Core::kernel, and KernelInterface::mainWindow().
maxVelocity()
double GuiCore::maxVelocity (int jointNum = 0) const
References Core::kernel, and KernelInterface::maxVelocity().
Referenced by JogView::createContent().
move2Backup()
bool Core::move2Backup (const QString & fileName) inherited
Referenced by TestEdit::saveFile().
pluggableMainPage()
PluginPageInterface * GuiCore::pluggableMainPage (const QString & pageID)
References Core::kernel, and KernelInterface::pluggableMainPage().
Referenced by TestMain::checkPlugins(), and PluginPageFactory::createCenterPage().
pluggableMainPages()
QList< QString > GuiCore::pluggableMainPages ()
References Core::kernel, and KernelInterface::pluggableMainPages().
Referenced by MainWindow::createDockables(), MainWindow::createMainWidgets(), and PluginDialog::populateTreeWidget().
pluggableNotebookPage()
PluginPageInterface * GuiCore::pluggableNotebookPage (const QString & pageID)
References Core::kernel, and KernelInterface::pluggableNotebookPage().
Referenced by PluginPageFactory::createNotebookPage().
pluggableNotebookPages()
QList< QString > GuiCore::pluggableNotebookPages ()
References Core::kernel, and KernelInterface::pluggableNotebookPages().
Referenced by MainWindow::createDockables(), and MainWindow::createMainWidgets().
riseError()
void GuiCore::riseError (const QString & msg) virtual
Reimplemented from Core.
References Core::kernel, KernelInterface::logSysEvent(), KernelInterface::mainWindow(), ValueManager::setValue(), SysEvent::toString(), SysEvent::type(), and SysEvent::what().
Referenced by MainWindow::autoStart(), ToolManager::deleteTool(), TestEdit::loadFile(), TestEdit::reallyLoadFile(), TestEdit::saveFile(), and ToolManager::saveToolChanges().
setAppMode()
void Core::setAppMode (ApplicationMode m) inherited
References ValueManager::setValue().
Referenced by TestEdit::loadFile(), TestEdit::openFile(), and PathEditor::reallyLoadFile().
setAppMode4PageID()
void GuiCore::setAppMode4PageID (const QString & pageID)
References Core::kernel, and KernelInterface::setAppMode4PageID().
Referenced by SysEventView::eventFilter().
setKernelCreator()
void GuiCore::setKernelCreator (KernelCreator * kc) static
References Core::kc.
Referenced by main().
setMainWindow()
void GuiCore::setMainWindow (QMainWindow * w)
References Core::kernel, and KernelInterface::setMainWindow().
Referenced by main().
setViewStack()
void GuiCore::setViewStack (PageStack * v)
References Core::kernel, and KernelInterface::setViewStack().
Referenced by MainWindow::createDockables(), and MainWindow::createMainWidgets().
setWindowTitle()
void GuiCore::setWindowTitle (const QString & title)
References Core::kernel, and KernelInterface::setWindowTitle().
Referenced by PageStack::activatePage(), and SettingsNotebook::currentChanged().
showAllButCenter()
void Core::showAllButCenter (bool visible) inherited
References ValueManager::setValue().
Referenced by ToolManager::editTool(), ToolManager::eventFilter(), LCToolTable::keyPressEvent(), LCToolTable::modelChanged(), ToolManager::saveToolChanges(), and ToolTable::setData().
showHelp()
void GuiCore::showHelp () const
References Core::kernel, and KernelInterface::showHelp().
Referenced by MainWindow::keyPressEvent().
showHelpAtPageChange()
bool Core::showHelpAtPageChange () const inherited
References KernelInterface::config(), Core::kernel, and ConfigManager::value().
stackedPage()
QWidget * GuiCore::stackedPage (const QString & pageName)
References Core::kernel, and KernelInterface::stackedPage().
Referenced by TestEdit::openFile().
statusInfo()
PluginPageInterface * GuiCore::statusInfo (const QString & infoID)
References Core::kernel, and KernelInterface::statusInfo().
Referenced by PluginPageFactory::createDockable().
statusInfos()
QList< QString > GuiCore::statusInfos ()
References Core::kernel, and KernelInterface::statusInfos().
Referenced by MainWindow::createDockables(), and PluginDialog::populateTreeWidget().
toolOffset()
Pos9 GuiCore::toolOffset () const
Referenced by FixtureEdit::saveFixture().
toolTable()
ToolTable & GuiCore::toolTable ()
References Core::kernel, and KernelInterface::toolTable().
toolTableModel()
ToolTable * GuiCore::toolTableModel ()
References Core::kernel, and KernelInterface::toolTableModel().
Referenced by LCToolTable::connectSignals(), and LCToolTable::createContent().
view3D()
OcctQtViewer * GuiCore::view3D ()
References Core::kernel, and KernelInterface::view3D().
Referenced by PluginPageFactory::PluginPageFactory(), MainWindow::about(), MainWindow::createDockables(), and MainWindow::createMainWidgets().
viewStack()
PageStack * GuiCore::viewStack ()
References Core::kernel, and KernelInterface::viewStack().
Referenced by MainWindow::testTools().
windowClosing()
void GuiCore::windowClosing (QCloseEvent * e)
References Core::kernel, and KernelInterface::windowClosing().
Referenced by MainWindow::closeEvent().
Member Data Documentation
checked
int Core::checked = -1 static protected inherited
kc
KernelCreator * Core::kc = nullptr static protected inherited
Referenced by Core::Core(), Core::setKernelCreator(), and setKernelCreator().
kernel
KernelInterface * Core::kernel = nullptr static protected inherited
Referenced by Config::Config(), Core::Core(), GuiCore(), PluginPageFactory::PluginPageFactory(), activatePage(), activeGCodes(), activeMCodes(), Core::axisMask(), axisMask(), beAbortTask(), beEnableBlockDelete(), beEnableFlood(), beEnableMist(), beEnableOptionalStop(), beHomeAxis(), beJogStart(), beJogStep(), beJogStop(), beLoadTaskPlan(), beLoadToolTable(), beSendMDICommand(), beSetAuto(), beSetFeedOverride(), beSetRapidOverride(), beSetSpindle(), beSetSpindleOverride(), beSetTaskMode(), beSetTaskState(), beTaskPlanSynch(), checkBE(), PluginPageFactory::createCenterPage(), PluginPageFactory::createDockable(), PluginPageFactory::createNotebookPage(), curPage(), Core::databaseConnection(), defaultVelocity(), Core::fileName4(), help4Keyword(), isLatheMode(), Core::isSimulator(), Core::languagePrefix(), lcProperties(), Core::locale(), machineLimits(), mainWindow(), maxVelocity(), AbstractCenterWidget::patch(), pluggableMainPage(), pluggableMainPages(), pluggableNotebookPage(), pluggableNotebookPages(), Core::riseError(), riseError(), setAppMode4PageID(), setMainWindow(), setViewStack(), setWindowTitle(), showHelp(), Core::showHelpAtPageChange(), stackedPage(), statusInfo(), statusInfos(), toolTable(), toolTableModel(), view3D(), viewStack(), and windowClosing().
The documentation for this class was generated from the following files:
src/guiLib/control/guicore.h
src/guiLib/control/guicore.cpp