FalconView: GuiKernel Class Reference
GuiKernel Class Reference
#include <guikernel.h>
Signals
void abortTask ()
void enableBlockDelete (bool enable)
void enableFlood (bool enable)
void enableMist (bool enable)
void enableOptionalStop (bool enable)
void homeAxis (int jointNum)
void jogStart (int axis, double speed)
void jogStep (int axis, double stepSize, double speed)
void jogStop (int axis)
void loadTaskPlan (const QString &gcodeFile)
void loadToolTable (const QString &toolTableFile)
void sendMDICommand (const QString &command)
void setAuto (int autoMode, int line)
void setFeedOverride (double rate)
void setRapidOverride (double rate)
void setSpindle (bool enable, int speed, int direction)
void setSpindleOverride (double rate)
void setTaskMode (int mode)
void setTaskState (int state)
void taskPlanSynch ()
Public Member Functions
virtual void activatePage (const QString &pageName) override
virtual int activeGCodes () const override
virtual int activeMCodes () const override
virtual QString activePage () const override
virtual int axisMask () const override
virtual void beAbortTask ()
virtual void beEnableBlockDelete (bool enable)
virtual void beEnableFlood (bool enable)
virtual void beEnableMist (bool enable)
virtual void beEnableOptionalStop (bool enable)
virtual void beHomeAxis (int jointNum)
virtual void beJogStart (int axis, double speed)
virtual void beJogStep (int axis, double stepSize, double speed)
virtual void beJogStop (int axis)
virtual void beLoadTaskPlan (const QString &gcodeFile)
virtual void beLoadToolTable (const QString &toolTableFile)
virtual void beSendMDICommand (const QString &command)
virtual void beSetAuto (int autoMode, int line)
virtual void beSetFeedOverride (double rate)
virtual void beSetRapidOverride (double rate)
virtual void beSetSpindle (bool enable, int speed, int direction)
virtual void beSetSpindleOverride (double rate)
virtual void beSetTaskMode (int mode)
virtual void beSetTaskState (int state)
virtual void beTaskPlanSynch ()
virtual bool checkBE () override
virtual ConfigManager * config () const override
virtual ConfigManager * config () override
virtual DBConnection * createDatabase (DBHelper &dbAssist)
virtual QString curPage () const override
virtual DBConnection * databaseConnection () override
virtual double defaultVelocity (int jointNum=0) const override
virtual QString fileName4 (const QString &fileID) const override
virtual void help4Keyword (const QString &keyWord) override
virtual void initialize (DBHelper &dbAssist) override
virtual bool isLatheMode () const override
virtual bool isSimulator () const override
virtual const LcProperties & lcProperties () const override
virtual LcProperties & lcProperties () override
virtual QLocale locale () const override
virtual void logSysEvent (const QString &msg) override
virtual void logSysEvent (const SysEvent &se) override
virtual std::pair< QVector3D, QVector3D > machineLimits () const override
virtual QMainWindow * mainWindow () override
virtual double maxVelocity (int jointNum=0) const override
virtual void nop () const override
virtual PluginPageInterface * pluggableMainPage (const QString &pageID) const override
virtual QList< QString > pluggableMainPages () const override
virtual PluginPageInterface * pluggableNotebookPage (const QString &pageID) const override
virtual QList< QString > pluggableNotebookPages () const override
virtual void processGCodeFile (const QVariant &fileName) override
virtual void setAppMode4PageID (const QString &pageID) override
virtual void setMainWindow (QMainWindow *w) override
virtual void setupBackend () override
virtual QLocale * setupTranslators () override
virtual void setViewStack (PageStack *v) override
virtual void setWindowTitle (const QString &title) override
virtual void showHelp () const override
virtual QWidget * stackedPage (const QString &pageName) override
virtual PluginPageInterface * statusInfo (const QString &infoID) const override
virtual QList< QString > statusInfos () const override
virtual void timerEvent (QTimerEvent *e)
virtual Pos9 toolOffset () const override
virtual ToolTable & toolTable () override
virtual ToolTable * toolTableModel () override
virtual void updateView (const QVariant &pos) override
virtual QString version () const override
virtual OcctQtViewer * view3D () override
virtual PageStack * viewStack () override
virtual void windowClosing (QCloseEvent *e) override
Protected Member Functions
GuiKernel (int maxGCodes, int maxMCodes, QApplication &app, const QString &appName, const QString &groupID)
virtual ~GuiKernel ()=default
virtual void processAppArgs (const QStringList &args) override
virtual void usage ()
Private Attributes
Ally3D * ally3D
QApplication & app
QString appName
QThread backendCommThread
CanonIF * canonIF
PageStack * centerView
ConfigManager * cfg
int checked
CommandWriter * commandWriter
DBConnection * conn
QLocale * curLocale
GCodeInfo gcodeInfo
QString groupID
HelpDockable * help
QString helpFileName
QString iniFileName
QString langDir
LCInterface * lcIF
LcProperties * lcProps
QMap< QString, PluginPageInterface * > mainPages
const int maxGCodes
AxisMask * mAxis
const int maxMCodes
QMap< QString, PluginPageInterface * > nbPages
QString nc_files
QString pluginDir
PositionCalculator positionCalculator
bool simulator
QMap< QString, PluginPageInterface * > statInfos
StatusReader * statusReader
SysEventModel * sysEvents
QBasicTimer timer
ToolTable * tt
OcctQtViewer * v3D
QMainWindow * wMain
Constructor & Destructor Documentation
GuiKernel()
GuiKernel::GuiKernel (int maxGCodes, int maxMCodes, QApplication & app, const QString & appName, const QString & groupID) explicit protected
~GuiKernel()
virtual GuiKernel::~GuiKernel () protected virtual default
Member Function Documentation
abortTask
void GuiKernel::abortTask () signal
Referenced by beAbortTask(), and setupBackend().
activatePage()
void GuiKernel::activatePage (const QString & pageName) override virtual
Implements KernelInterface.
References PageStack::activatePage(), and centerView.
activeGCodes()
int GuiKernel::activeGCodes () const override virtual
Implements KernelInterface.
References maxGCodes.
activeMCodes()
int GuiKernel::activeMCodes () const override virtual
Implements KernelInterface.
References maxMCodes.
activePage()
QString GuiKernel::activePage () const override virtual
Implements KernelInterface.
References PageStack::activePage(), and centerView.
axisMask()
int GuiKernel::axisMask () const override virtual
Implements KernelInterface.
References AxisMask::mask(), and mAxis.
beAbortTask()
void GuiKernel::beAbortTask () virtual
Implements KernelInterface.
References abortTask().
beEnableBlockDelete()
void GuiKernel::beEnableBlockDelete (bool enable) virtual
Implements KernelInterface.
References enableBlockDelete().
beEnableFlood()
void GuiKernel::beEnableFlood (bool enable) virtual
Implements KernelInterface.
References enableFlood().
beEnableMist()
void GuiKernel::beEnableMist (bool enable) virtual
Implements KernelInterface.
References enableMist().
beEnableOptionalStop()
void GuiKernel::beEnableOptionalStop (bool enable) virtual
Implements KernelInterface.
References enableOptionalStop().
beHomeAxis()
void GuiKernel::beHomeAxis (int jointNum) virtual
Implements KernelInterface.
References homeAxis().
beJogStart()
void GuiKernel::beJogStart (int axis, double speed) virtual
Implements KernelInterface.
References jogStart().
beJogStep()
void GuiKernel::beJogStep (int axis, double stepSize, double speed) virtual
Implements KernelInterface.
References jogStep().
beJogStop()
void GuiKernel::beJogStop (int axis) virtual
Implements KernelInterface.
References jogStop().
beLoadTaskPlan()
void GuiKernel::beLoadTaskPlan (const QString & gcodeFile) virtual
Implements KernelInterface.
References loadTaskPlan().
beLoadToolTable()
void GuiKernel::beLoadToolTable (const QString & toolTableFile) virtual
Implements KernelInterface.
References loadToolTable().
beSendMDICommand()
void GuiKernel::beSendMDICommand (const QString & command) virtual
Implements KernelInterface.
References sendMDICommand().
beSetAuto()
void GuiKernel::beSetAuto (int autoMode, int line) virtual
Implements KernelInterface.
References setAuto().
beSetFeedOverride()
void GuiKernel::beSetFeedOverride (double rate) virtual
Implements KernelInterface.
References setFeedOverride().
beSetRapidOverride()
void GuiKernel::beSetRapidOverride (double rate) virtual
Implements KernelInterface.
References setRapidOverride().
beSetSpindle()
void GuiKernel::beSetSpindle (bool enable, int speed, int direction) virtual
Implements KernelInterface.
References setSpindle().
beSetSpindleOverride()
void GuiKernel::beSetSpindleOverride (double rate) virtual
Implements KernelInterface.
References setSpindleOverride().
beSetTaskMode()
void GuiKernel::beSetTaskMode (int mode) virtual
Implements KernelInterface.
References setTaskMode().
beSetTaskState()
void GuiKernel::beSetTaskState (int state) virtual
Implements KernelInterface.
References setTaskState().
beTaskPlanSynch()
void GuiKernel::beTaskPlanSynch () virtual
Implements KernelInterface.
References taskPlanSynch().
checkBE()
bool GuiKernel::checkBE () override virtual
Implements KernelInterface.
References checked, commandWriter, CommandWriter::isActive(), StatusReader::isActive(), ValueManager::setValue(), and statusReader.
config() [1/2]
ConfigManager * GuiKernel::config () const override virtual
Implements KernelInterface.
References cfg.
config() [2/2]
ConfigManager * GuiKernel::config () override virtual
Implements KernelInterface.
References cfg.
createDatabase()
DBConnection * GuiKernel::createDatabase (DBHelper & dbAssist) virtual
References conn, DBHelper::createDatabase(), DBHelper::createSampleData(), DBHelper::dbConnection(), and DBConnection::dbName().
Referenced by initialize().
curPage()
QString GuiKernel::curPage () const override virtual
Implements KernelInterface.
References PageStack::activePage(), and centerView.
databaseConnection()
DBConnection * GuiKernel::databaseConnection () override virtual
Implements KernelInterface.
References conn.
defaultVelocity()
double GuiKernel::defaultVelocity (int jointNum = 0) const override virtual
Implements KernelInterface.
References lcProperties(), and LcProperties::value().
enableBlockDelete
void GuiKernel::enableBlockDelete (bool enable) signal
Referenced by beEnableBlockDelete(), and setupBackend().
enableFlood
void GuiKernel::enableFlood (bool enable) signal
Referenced by beEnableFlood(), and setupBackend().
enableMist
void GuiKernel::enableMist (bool enable) signal
Referenced by beEnableMist(), and setupBackend().
enableOptionalStop
void GuiKernel::enableOptionalStop (bool enable) signal
Referenced by beEnableOptionalStop(), and setupBackend().
fileName4()
QString GuiKernel::fileName4 (const QString & fileID) const override virtual
Implements KernelInterface.
References conn, DBConnection::dbName(), helpFileName, iniFileName, langDir, lcProps, nc_files, pluginDir, and LcProperties::toolTableFileName().
Referenced by initialize().
help4Keyword()
void GuiKernel::help4Keyword (const QString & keyWord) override virtual
Implements KernelInterface.
References help, and HelpDockable::help4Keyword().
homeAxis
void GuiKernel::homeAxis (int jointNum) signal
Referenced by beHomeAxis(), and setupBackend().
initialize()
void GuiKernel::initialize (DBHelper & dbAssist) override virtual
====================================================
====================================================
====================================================
====================================================
Implements KernelInterface.
References AxisMask::activeAxis(), ally3D, app, canonIF, cfg, commandWriter, conn, DBHelper::connect(), createDatabase(), curLocale, DBHelper::dbConnection(), DBConnection::dbName(), DBConnection::dbType(), fileName4(), gcodeInfo, ConfigManager::getForeground(), LcProperties::getPath(), helpFileName, isLatheMode(), langDir, lcIF, lcProperties(), lcProps, mainPages, mAxis, nbPages, nc_files, pluginDir, positionCalculator, processAppArgs(), processGCodeFile(), Ally3D::setCurSegColor(), CanonIF::setFeedColor(), Ally3D::setFeedColor(), ToolTable::setLatheMode(), Ally3D::setLimitsColor(), Ally3D::setOcctViewer(), Ally3D::setOldSegColor(), CanonIF::setTraverseColor(), AxisMask::setup(), setupBackend(), LCInterface::setupToolTable(), setupTranslators(), ConfigManager::setValue(), Ally3D::setWorkPieceColor(), simulator, statInfos, statusReader, sysEvents, LcProperties::toolTableFileName(), tt, updateView(), v3D, LcProperties::value(), ConfigManager::value(), and ValueModel::valueChanged().
isLatheMode()
bool GuiKernel::isLatheMode () const override virtual
Implements KernelInterface.
References lcProps, and LcProperties::value().
Referenced by initialize().
isSimulator()
bool GuiKernel::isSimulator () const override virtual
Implements KernelInterface.
jogStart
void GuiKernel::jogStart (int axis, double speed) signal
Referenced by beJogStart(), and setupBackend().
jogStep
void GuiKernel::jogStep (int axis, double stepSize, double speed) signal
Referenced by beJogStep(), and setupBackend().
jogStop
void GuiKernel::jogStop (int axis) signal
Referenced by beJogStop(), and setupBackend().
lcProperties() [1/2]
const LcProperties & GuiKernel::lcProperties () const override virtual
Implements KernelInterface.
References lcProps.
lcProperties() [2/2]
LcProperties & GuiKernel::lcProperties () override virtual
Implements KernelInterface.
References lcProps.
Referenced by defaultVelocity(), initialize(), and maxVelocity().
loadTaskPlan
void GuiKernel::loadTaskPlan (const QString & gcodeFile) signal
Referenced by beLoadTaskPlan(), and setupBackend().
loadToolTable
void GuiKernel::loadToolTable (const QString & toolTableFile) signal
Referenced by beLoadToolTable(), and setupBackend().
locale()
QLocale GuiKernel::locale () const override virtual
Implements KernelInterface.
References curLocale.
logSysEvent() [1/2]
void GuiKernel::logSysEvent (const QString & msg) override virtual
Implements KernelInterface.
References SysEventModel::append(), sysEvents, SysEvent::type(), SysEvent::what(), and SysEvent::when().
logSysEvent() [2/2]
void GuiKernel::logSysEvent (const SysEvent & se) override virtual
Implements KernelInterface.
References SysEventModel::append(), sysEvents, SysEvent::type(), SysEvent::what(), and SysEvent::when().
machineLimits()
std::pair< QVector3D, QVector3D > GuiKernel::machineLimits () const override virtual
Implements KernelInterface.
References canonIF, CanonIF::g5xOffset(), CanonIF::g92Offset(), lcProps, and LcProperties::value().
mainWindow()
QMainWindow * GuiKernel::mainWindow () override virtual
Implements KernelInterface.
References wMain.
Referenced by windowClosing().
maxVelocity()
double GuiKernel::maxVelocity (int jointNum = 0) const override virtual
Implements KernelInterface.
References lcProperties(), and LcProperties::value().
nop()
void GuiKernel::nop () const override virtual
Implements KernelInterface.
Referenced by setupBackend().
pluggableMainPage()
PluginPageInterface * GuiKernel::pluggableMainPage (const QString & pageID) const override virtual
Implements KernelInterface.
References mainPages.
pluggableMainPages()
QList< QString > GuiKernel::pluggableMainPages () const override virtual
Implements KernelInterface.
References mainPages.
pluggableNotebookPage()
PluginPageInterface * GuiKernel::pluggableNotebookPage (const QString & pageID) const override virtual
Implements KernelInterface.
References nbPages.
pluggableNotebookPages()
QList< QString > GuiKernel::pluggableNotebookPages () const override virtual
Implements KernelInterface.
References nbPages.
processAppArgs()
void GuiKernel::processAppArgs (const QStringList & args) override protected virtual
Implements KernelInterface.
References helpFileName, iniFileName, langDir, pluginDir, and usage().
Referenced by initialize().
processGCodeFile()
void GuiKernel::processGCodeFile (const QVariant & fileName) override virtual
Implements KernelInterface.
References ally3D, canonIF, lcIF, LCInterface::parseInline(), Ally3D::showPath(), and CanonIF::toolPath().
Referenced by initialize().
sendMDICommand
void GuiKernel::sendMDICommand (const QString & command) signal
Referenced by beSendMDICommand(), and setupBackend().
setAppMode4PageID()
void GuiKernel::setAppMode4PageID (const QString & pageID) override virtual
Implements KernelInterface.
References Auto, Edit, ErrMessages, Manual, MDI, SelectFile, Settings, ValueManager::setValue(), Touch, Wheel, and XEdit.
setAuto
void GuiKernel::setAuto (int autoMode, int line) signal
Referenced by beSetAuto(), and setupBackend().
setFeedOverride
void GuiKernel::setFeedOverride (double rate) signal
Referenced by beSetFeedOverride(), and setupBackend().
setMainWindow()
void GuiKernel::setMainWindow (QMainWindow * w) override virtual
Implements KernelInterface.
References PluginPageFactory::createCenterPage(), help, and wMain.
setRapidOverride
void GuiKernel::setRapidOverride (double rate) signal
Referenced by beSetRapidOverride(), and setupBackend().
setSpindle
void GuiKernel::setSpindle (bool enable, int speed, int direction) signal
Referenced by beSetSpindle(), and setupBackend().
setSpindleOverride
void GuiKernel::setSpindleOverride (double rate) signal
Referenced by beSetSpindleOverride(), and setupBackend().
setTaskMode
void GuiKernel::setTaskMode (int mode) signal
Referenced by beSetTaskMode(), and setupBackend().
setTaskState
void GuiKernel::setTaskState (int state) signal
Referenced by beSetTaskState(), and setupBackend().
setupBackend()
void GuiKernel::setupBackend () override virtual
Implements KernelInterface.
References abortTask(), CommandWriter::abortTask(), backendCommThread, commandWriter, enableBlockDelete(), CommandWriter::enableBlockDelete(), enableFlood(), CommandWriter::enableFlood(), enableMist(), CommandWriter::enableMist(), enableOptionalStop(), CommandWriter::enableOptionalStop(), homeAxis(), CommandWriter::homeAxis(), CommandWriter::isActive(), StatusReader::isActive(), jogStart(), CommandWriter::jogStart(), jogStep(), CommandWriter::jogStep(), jogStop(), CommandWriter::jogStop(), loadTaskPlan(), CommandWriter::loadTaskPlan(), loadToolTable(), CommandWriter::loadToolTable(), nop(), sendMDICommand(), CommandWriter::sendMDICommand(), setAuto(), CommandWriter::setAuto(), setFeedOverride(), CommandWriter::setFeedOverride(), setRapidOverride(), CommandWriter::setRapidOverride(), setSpindle(), CommandWriter::setSpindle(), setSpindleOverride(), CommandWriter::setSpindleOverride(), setTaskMode(), CommandWriter::setTaskMode(), setTaskState(), CommandWriter::setTaskState(), statusReader, taskPlanSynch(), CommandWriter::taskPlanSynch(), and timer.
Referenced by initialize().
setupTranslators()
QLocale * GuiKernel::setupTranslators () override virtual
Implements KernelInterface.
References app, curLocale, and langDir.
Referenced by initialize().
setViewStack()
void GuiKernel::setViewStack (PageStack * v) override virtual
Implements KernelInterface.
References centerView.
setWindowTitle()
void GuiKernel::setWindowTitle (const QString & title) override virtual
Implements KernelInterface.
References wMain.
showHelp()
void GuiKernel::showHelp () const override virtual
Implements KernelInterface.
References help, and HelpDockable::showHelp().
stackedPage()
QWidget * GuiKernel::stackedPage (const QString & pageName) override virtual
Implements KernelInterface.
References centerView, and PageStack::page().
statusInfo()
PluginPageInterface * GuiKernel::statusInfo (const QString & infoID) const override virtual
Implements KernelInterface.
References statInfos.
statusInfos()
QList< QString > GuiKernel::statusInfos () const override virtual
Implements KernelInterface.
References statInfos.
taskPlanSynch
void GuiKernel::taskPlanSynch () signal
Referenced by beTaskPlanSynch(), and setupBackend().
timerEvent()
void GuiKernel::timerEvent (QTimerEvent * e) virtual
References SysEventModel::append(), ValueManager::setValue(), statusReader, sysEvents, timer, SysEvent::toString(), SysEvent::type(), StatusReader::update(), and SysEvent::what().
toolOffset()
Pos9 GuiKernel::toolOffset () const override virtual
Implements KernelInterface.
toolTable()
ToolTable & GuiKernel::toolTable () override virtual
Implements KernelInterface.
References tt.
toolTableModel()
ToolTable * GuiKernel::toolTableModel () override virtual
Implements KernelInterface.
References tt.
updateView()
void GuiKernel::updateView (const QVariant & pos) override virtual
Implements KernelInterface.
References ally3D, and Ally3D::moveCone().
Referenced by initialize().
usage()
void GuiKernel::usage () protected virtual
References version().
Referenced by processAppArgs().
version()
QString GuiKernel::version () const override virtual
Implements KernelInterface.
Referenced by usage().
view3D()
OcctQtViewer * GuiKernel::view3D () override virtual
Implements KernelInterface.
References v3D.
viewStack()
PageStack * GuiKernel::viewStack () override virtual
Implements KernelInterface.
References centerView.
windowClosing()
void GuiKernel::windowClosing (QCloseEvent * e) override virtual
Implements KernelInterface.
References centerView, cfg, mainWindow(), ConfigManager::settings, ConfigManager::setValue(), and PageStack::windowClosing().
Member Data Documentation
ally3D
Ally3D* GuiKernel::ally3D private
Referenced by initialize(), processGCodeFile(), and updateView().
app
QApplication& GuiKernel::app private
Referenced by initialize(), and setupTranslators().
appName
QString GuiKernel::appName private
backendCommThread
QThread GuiKernel::backendCommThread private
Referenced by setupBackend().
canonIF
CanonIF* GuiKernel::canonIF private
Referenced by initialize(), machineLimits(), and processGCodeFile().
centerView
PageStack* GuiKernel::centerView private
Referenced by activatePage(), activePage(), curPage(), setViewStack(), stackedPage(), viewStack(), and windowClosing().
cfg
ConfigManager* GuiKernel::cfg private
Referenced by config(), initialize(), and windowClosing().
checked
int GuiKernel::checked private
Referenced by checkBE().
commandWriter
CommandWriter* GuiKernel::commandWriter private
Referenced by checkBE(), initialize(), and setupBackend().
conn
DBConnection* GuiKernel::conn private
Referenced by createDatabase(), databaseConnection(), fileName4(), and initialize().
curLocale
QLocale* GuiKernel::curLocale private
Referenced by initialize(), locale(), and setupTranslators().
gcodeInfo
GCodeInfo GuiKernel::gcodeInfo private
Referenced by initialize().
groupID
QString GuiKernel::groupID private
help
HelpDockable* GuiKernel::help private
Referenced by help4Keyword(), setMainWindow(), and showHelp().
helpFileName
QString GuiKernel::helpFileName private
Referenced by fileName4(), initialize(), and processAppArgs().
iniFileName
QString GuiKernel::iniFileName private
Referenced by fileName4(), and processAppArgs().
langDir
QString GuiKernel::langDir private
Referenced by fileName4(), initialize(), processAppArgs(), and setupTranslators().
lcIF
LCInterface* GuiKernel::lcIF private
Referenced by initialize(), and processGCodeFile().
lcProps
LcProperties* GuiKernel::lcProps private
Referenced by fileName4(), initialize(), isLatheMode(), lcProperties(), and machineLimits().
mainPages
QMap<QString, PluginPageInterface*> GuiKernel::mainPages private
Referenced by initialize(), pluggableMainPage(), and pluggableMainPages().
maxGCodes
const int GuiKernel::maxGCodes private
Referenced by activeGCodes().
mAxis
AxisMask* GuiKernel::mAxis private
Referenced by axisMask(), and initialize().
maxMCodes
const int GuiKernel::maxMCodes private
Referenced by activeMCodes().
nbPages
QMap<QString, PluginPageInterface*> GuiKernel::nbPages private
Referenced by initialize(), pluggableNotebookPage(), and pluggableNotebookPages().
nc_files
QString GuiKernel::nc_files private
Referenced by fileName4(), and initialize().
pluginDir
QString GuiKernel::pluginDir private
Referenced by fileName4(), initialize(), and processAppArgs().
positionCalculator
PositionCalculator GuiKernel::positionCalculator private
Referenced by initialize().
simulator
bool GuiKernel::simulator private
Referenced by initialize().
statInfos
QMap<QString, PluginPageInterface*> GuiKernel::statInfos private
Referenced by initialize(), statusInfo(), and statusInfos().
statusReader
StatusReader* GuiKernel::statusReader private
Referenced by checkBE(), initialize(), setupBackend(), and timerEvent().
sysEvents
SysEventModel* GuiKernel::sysEvents private
Referenced by initialize(), logSysEvent(), and timerEvent().
timer
QBasicTimer GuiKernel::timer private
Referenced by setupBackend(), and timerEvent().
tt
ToolTable* GuiKernel::tt private
Referenced by initialize(), toolTable(), and toolTableModel().
v3D
OcctQtViewer* GuiKernel::v3D private
Referenced by initialize(), and view3D().
wMain
QMainWindow* GuiKernel::wMain private
Referenced by mainWindow(), setMainWindow(), and setWindowTitle().
The documentation for this class was generated from the following files:
src/app/control/guikernel.h
src/app/control/guikernel.cpp