FalconView: AxisMask Class Reference
AxisMask Class Reference
#include <axismask.h>
Public Member Functions
AxisMask (const AxisMask &other)
AxisMask (const QString &iniValue)
AxisMask (int mask)
virtual ~AxisMask ()
int activeAxis () const
void dump () const
bool hasAAxis () const
bool hasAxis (int axis) const
bool hasBAxis () const
bool hasCAxis () const
bool hasUAxis () const
bool hasVAxis () const
bool hasWAxis () const
bool hasXAxis () const
bool hasYAxis () const
bool hasZAxis () const
int joint4Axis (int axis) const
int mask () const
AxisMask & operator= (const AxisMask &other)
void setup (const QString &axisLetters)
Protected Member Functions
void calcActive ()
void checkHomed (int axis, QVariant value)
void parseIni (const QString &iniValue)
Private Attributes
bool axisHomed [9]
int axisMask
bool axisSeen [9]
int cntActive
int joint2Axis [9]
Static Private Attributes
static const char axisLetters [] = "XYZABCUVW"
Constructor & Destructor Documentation
AxisMask() [1/3]
AxisMask::AxisMask (const AxisMask & other) explicit
References axisSeen, and joint2Axis.
AxisMask() [2/3]
AxisMask::AxisMask (int mask) explicit
References axisSeen, cntActive, and mask().
AxisMask() [3/3]
AxisMask::AxisMask (const QString & iniValue) explicit
References axisSeen, joint2Axis, and parseIni().
~AxisMask()
AxisMask::~AxisMask () virtual
Member Function Documentation
activeAxis()
int AxisMask::activeAxis () const inline
References cntActive.
Referenced by GuiKernel::initialize().
calcActive()
void AxisMask::calcActive () protected
References axisMask, axisSeen, checkHomed(), cntActive, ValueManager::getModel(), ValueManager::getValue(), joint2Axis, and ValueModel::valueChanged().
Referenced by setup().
checkHomed()
void AxisMask::checkHomed (int axis, QVariant value) protected
References axisHomed, axisSeen, and ValueManager::setValue().
Referenced by calcActive().
dump()
void AxisMask::dump () const
References hasAAxis(), hasBAxis(), hasCAxis(), hasUAxis(), hasVAxis(), hasWAxis(), hasXAxis(), hasYAxis(), hasZAxis(), and joint2Axis.
hasAAxis()
bool AxisMask::hasAAxis () const inline
References axisSeen.
Referenced by dump(), PositionStatus::setActive(), FixtureEdit::setupUi(), and JogView::setupUi().
hasAxis()
bool AxisMask::hasAxis (int axis) const
References axisSeen.
hasBAxis()
bool AxisMask::hasBAxis () const inline
References axisSeen.
Referenced by dump(), PositionStatus::setActive(), FixtureEdit::setupUi(), and JogView::setupUi().
hasCAxis()
bool AxisMask::hasCAxis () const inline
References axisSeen.
Referenced by dump(), PositionStatus::setActive(), FixtureEdit::setupUi(), and JogView::setupUi().
hasUAxis()
bool AxisMask::hasUAxis () const inline
References axisSeen.
Referenced by dump(), PositionStatus::setActive(), FixtureEdit::setupUi(), and JogView::setupUi().
hasVAxis()
bool AxisMask::hasVAxis () const inline
References axisSeen.
Referenced by dump(), PositionStatus::setActive(), FixtureEdit::setupUi(), and JogView::setupUi().
hasWAxis()
bool AxisMask::hasWAxis () const inline
References axisSeen.
Referenced by dump(), PositionStatus::setActive(), FixtureEdit::setupUi(), and JogView::setupUi().
hasXAxis()
bool AxisMask::hasXAxis () const inline
References axisSeen.
Referenced by dump(), PositionStatus::setActive(), FixtureEdit::setupUi(), and JogView::setupUi().
hasYAxis()
bool AxisMask::hasYAxis () const inline
References axisSeen.
Referenced by dump(), PositionStatus::setActive(), FixtureEdit::setupUi(), and JogView::setupUi().
hasZAxis()
bool AxisMask::hasZAxis () const inline
References axisSeen.
Referenced by dump(), PositionStatus::setActive(), FixtureEdit::setupUi(), and JogView::setupUi().
joint4Axis()
int AxisMask::joint4Axis (int axis) const
References joint2Axis.
Referenced by PositionStatus::connectSignals().
mask()
int AxisMask::mask () const inline
References axisMask.
Referenced by AxisMask(), and GuiKernel::axisMask().
operator=()
AxisMask & AxisMask::operator= (const AxisMask & other)
References axisMask, axisSeen, cntActive, and joint2Axis.
parseIni()
void AxisMask::parseIni (const QString & iniValue) protected
References setup().
Referenced by AxisMask().
setup()
void AxisMask::setup (const QString & axisLetters)
References axisLetters, axisSeen, calcActive(), and joint2Axis.
Referenced by GuiKernel::initialize(), and parseIni().
Member Data Documentation
axisHomed
bool AxisMask::axisHomed[9] private
Referenced by checkHomed().
axisLetters
const char AxisMask::axisLetters = "XYZABCUVW" static private
Referenced by setup().
axisMask
int AxisMask::axisMask private
Referenced by calcActive(), mask(), and operator=().
axisSeen
bool AxisMask::axisSeen[9] private
Referenced by AxisMask(), calcActive(), checkHomed(), hasAAxis(), hasAxis(), hasBAxis(), hasCAxis(), hasUAxis(), hasVAxis(), hasWAxis(), hasXAxis(), hasYAxis(), hasZAxis(), operator=(), and setup().
cntActive
int AxisMask::cntActive private
Referenced by AxisMask(), activeAxis(), calcActive(), and operator=().
joint2Axis
int AxisMask::joint2Axis[9] private
Referenced by AxisMask(), calcActive(), dump(), joint4Axis(), operator=(), and setup().
The documentation for this class was generated from the following files:
src/baselib/util/axismask.h
src/baselib/util/axismask.cpp