FalconView: ToolTable Class Reference
ToolTable Class Reference
The ToolTable class parse and hold tooltable of linuxcnc.
#include <tooltable.h>
Public Member Functions
ToolTable (const ToolTable &&other)
ToolTable (LcProperties &lcProps, const QString &fileName=QString())
ToolTable (LcProperties &lcProps, QFile &file)
virtual ~ToolTable ()
QList< ToolEntry * >::Iterator begin ()
QList< ToolEntry * >::ConstIterator begin () const
int columnCount (const QModelIndex &parent) const override
const ToolEntry & current () const
QVariant data (const QModelIndex &index, int role) const override
void dump ()
QList< ToolEntry * >::Iterator end ()
QList< ToolEntry * >::ConstIterator end () const
int entries () const
QString fileName () const
Qt::ItemFlags flags (const QModelIndex &index) const override
QVariant headerData (int section, Qt::Orientation orientation, int role) const override
ToolTable & operator= (const ToolTable &&other)
int rowCount (const QModelIndex &parent) const override
bool save ()
void setCurrent (int lineNum)
bool setData (const QModelIndex &index, const QVariant &value, int role=Qt::EditRole) override
void setDirty (bool dirty=true)
void setLatheMode (bool latheMode)
const ToolEntry * tool (int num) const
const ToolEntry * tool4Slot (int num) const
Protected Member Functions
void addTool (const ToolEntry &tool)
void processFile (QFile &file)
void processLine (int lineNum, const QString &line)
Private Attributes
ToolEntry curTool
bool dirty
QString fn
bool latheMode
LcProperties & lcProperties
QMap< int, ToolEntry * > mappedTools
QFileInfo toolImageDir
QList< ToolEntry * > tools
Detailed Description
The ToolTable class parse and hold tooltable of linuxcnc.
Constructor & Destructor Documentation
ToolTable() [1/3]
ToolTable::ToolTable (LcProperties & lcProps, const QString & fileName = QString()) explicit
References fileName(), and processFile().
ToolTable() [2/3]
ToolTable::ToolTable (LcProperties & lcProps, QFile & file) explicit
References processFile().
ToolTable() [3/3]
ToolTable::ToolTable (const ToolTable && other) explicit
~ToolTable()
ToolTable::~ToolTable () virtual
Member Function Documentation
addTool()
void ToolTable::addTool (const ToolEntry & tool) protected
begin() [1/2]
QList<ToolEntry*>::Iterator ToolTable::begin () inline
References tools.
begin() [2/2]
QList<ToolEntry*>::ConstIterator ToolTable::begin () const inline
References tools.
columnCount()
int ToolTable::columnCount (const QModelIndex & parent) const override
References latheMode.
current()
const ToolEntry& ToolTable::current () const inline
References curTool.
Referenced by CanonIFSettings::changeTool().
data()
QVariant ToolTable::data (const QModelIndex & index, int role) const override
References ToolEntry::backAngle(), ToolEntry::description(), ToolEntry::diameter(), ToolEntry::frontAngle(), ToolEntry::icon(), latheMode, ToolEntry::length(), ToolEntry::number(), ToolEntry::quadrant(), ToolEntry::slot(), tools, and ToolEntry::xOffset().
dump()
void ToolTable::dump ()
References mappedTools, and tools.
end() [1/2]
QList<ToolEntry*>::Iterator ToolTable::end () inline
References tools.
end() [2/2]
QList<ToolEntry*>::ConstIterator ToolTable::end () const inline
References tools.
entries()
int ToolTable::entries () const
References tools.
fileName()
QString ToolTable::fileName () const inline
References fn.
Referenced by ToolTable().
flags()
Qt::ItemFlags ToolTable::flags (const QModelIndex & index) const override
headerData()
QVariant ToolTable::headerData (int section, Qt::Orientation orientation, int role) const override
References latheMode.
operator=()
ToolTable & ToolTable::operator= (const ToolTable && other)
References curTool, fn, mappedTools, and tools.
processFile()
void ToolTable::processFile (QFile & file) protected
References fn, lcProperties, processLine(), LcProperties::toolImageDir(), and toolImageDir.
Referenced by ToolTable().
processLine()
void ToolTable::processLine (int lineNum, const QString & line) protected
References mappedTools, ToolEntry::setPixmap(), ToolEntry::setToolType(), toolImageDir, and tools.
Referenced by processFile().
rowCount()
int ToolTable::rowCount (const QModelIndex & parent) const override
References tools.
save()
bool ToolTable::save ()
References fn, and tools.
Referenced by LCToolTable::keyPressEvent().
setCurrent()
void ToolTable::setCurrent (int lineNum)
References curTool, and tools.
Referenced by CanonIFSettings::changeTool().
setData()
bool ToolTable::setData (const QModelIndex & index, const QVariant & value, int role = Qt::EditRole) override
References latheMode, ToolEntry::setBackAngle(), ToolEntry::setDescription(), ToolEntry::setDiameter(), ToolEntry::setFrontAngle(), ToolEntry::setLength(), ToolEntry::setQuadrant(), ToolEntry::setSlot(), ToolEntry::setXOffset(), Core::showAllButCenter(), and tools.
setDirty()
void ToolTable::setDirty (bool dirty = true)
References dirty.
Referenced by LCToolTable::keyPressEvent(), and LCToolTable::modelChanged().
setLatheMode()
void ToolTable::setLatheMode (bool latheMode) inline
References latheMode.
Referenced by GuiKernel::initialize().
tool()
const ToolEntry * ToolTable::tool (int num) const
References mappedTools.
Referenced by CanonIFSettings::canonTool().
tool4Slot()
const ToolEntry * ToolTable::tool4Slot (int num) const
References tools.
Member Data Documentation
curTool
ToolEntry ToolTable::curTool private
Referenced by current(), operator=(), and setCurrent().
dirty
bool ToolTable::dirty private
Referenced by setDirty().
fn
QString ToolTable::fn private
Referenced by fileName(), operator=(), processFile(), and save().
latheMode
bool ToolTable::latheMode private
Referenced by columnCount(), data(), headerData(), setData(), and setLatheMode().
lcProperties
LcProperties& ToolTable::lcProperties private
Referenced by processFile().
mappedTools
QMap<int, ToolEntry*> ToolTable::mappedTools private
Referenced by dump(), operator=(), processLine(), and tool().
toolImageDir
QFileInfo ToolTable::toolImageDir private
Referenced by processFile(), and processLine().
tools
QList<ToolEntry*> ToolTable::tools private
Referenced by begin(), data(), dump(), end(), entries(), operator=(), processLine(), rowCount(), save(), setCurrent(), setData(), and tool4Slot().
The documentation for this class was generated from the following files:
src/app/LC/tooltable.h
src/app/LC/tooltable.cpp