FalconView: GCodeInfo Class Reference
GCodeInfo Class Reference
#include <gcodeinfo.h>
Public Member Functions
GCodeInfo ()
void update (int *activeGCodes, int *activeMCodes, const QString &fileName, int curLine)
Protected Attributes
ValueManager vm
Constructor & Destructor Documentation
GCodeInfo()
GCodeInfo::GCodeInfo ()
References ValueManager::setValue(), and vm.
Member Function Documentation
update()
void GCodeInfo::update (int * activeGCodes, int * activeMCodes, const QString & fileName, int curLine)
References GuiCore::activeGCodes(), GuiCore::activeMCodes(), ValueManager::setValue(), and vm.
Referenced by StatusReader::update().
Member Data Documentation
vm
ValueManager GCodeInfo::vm protected
Referenced by GCodeInfo(), and update().
The documentation for this class was generated from the following files:
src/guiLib/view/gcodeinfo.h
src/guiLib/view/gcodeinfo.cpp