FalconView: HelpKeywordWidget Class Reference
HelpKeywordWidget Class Reference
#include <helpkeywordwidget.h>
Public Member Functions
HelpKeywordWidget (QWidget *parent=nullptr)
virtual ~HelpKeywordWidget ()
void parse (const QByteArray &ba, QMap< QString, QString > &keyWords)
void setIcon (const QIcon &icon)
void sourceChanged (const QUrl &src)
Protected Member Functions
void processChildren (const QDomElement &e, QMap< QString, QString > &keyWords)
Private Attributes
QIcon icon
Constructor & Destructor Documentation
HelpKeywordWidget()
HelpKeywordWidget::HelpKeywordWidget (QWidget * parent = nullptr) explicit
~HelpKeywordWidget()
HelpKeywordWidget::~HelpKeywordWidget () virtual
Member Function Documentation
parse()
void HelpKeywordWidget::parse (const QByteArray & ba, QMap< QString, QString > & keyWords)
References processChildren().
Referenced by HelpEngine::HelpEngine().
processChildren()
void HelpKeywordWidget::processChildren (const QDomElement & e, QMap< QString, QString > & keyWords) protected
References icon.
Referenced by parse().
setIcon()
void HelpKeywordWidget::setIcon (const QIcon & icon)
References icon.
Referenced by HelpEngine::HelpEngine().
sourceChanged()
void HelpKeywordWidget::sourceChanged (const QUrl & src)
Referenced by HelpView::sourceChanged().
Member Data Documentation
icon
QIcon HelpKeywordWidget::icon private
Referenced by processChildren(), and setIcon().
The documentation for this class was generated from the following files:
src/guiLib/view/helpkeywordwidget.h
src/guiLib/view/helpkeywordwidget.cpp