FalconView: CanonIF::IFSettings Class Reference
CanonIF::IFSettings Class Reference
Private Member Functions
IFSettings (LcProperties &lcProperties, ToolTable &toolTable)
void changeTool (int ttIndex)
CANON_POSITION g5xOffset (int i) const
bool isSpeedOverrideEnabled (int) const
double lengthUnits () const
CanonIF::IFSettings::lengthUnits.
void selectPlane (CANON_PLANE p)
void setCurSegColor (const QColor &c)
void setEndPoint (const CANON_POSITION &p)
void setFeedColor (const QColor &c)
void setG5xOffset (int i, const CANON_POSITION &p)
void setG92Offset (const CANON_POSITION &p)
void setJobUnits (CANON_UNITS u)
void setLimitsColor (const QColor &c)
void setMotionMode (CANON_MOTION_MODE mode, double tolerance)
void setOldSegColor (const QColor &c)
void setSpindleMode (int spindle, double css_max)
void setToolOffset (EmcPose offset)
void setTraverseColor (const QColor &c)
void setWorkPieceColor (const QColor &c)
void setXYRotation (double r)
CANON_DIRECTION spindleDir (int spindle) const
double spindleSpeed (int spindle) const
CANON_TOOL_TABLE toolEntry (int ttIndex) const
Private Attributes
bool adaptiveFeed
CanonConfig_t canon
StupidToolChangerIF changer
Quantity_Color colCurSeg
Quantity_Color colFeed
Quantity_Color colLimits
Quantity_Color colOldSeg
Quantity_Color colTraverse
Quantity_Color colWorkPiece
bool feedHold
bool feedOverride
bool floodActive
CANON_POSITION g5xOffsets [9]
GraphicFactory gf
double iTraverseRate
CANON_UNITS machineUnits
bool mistActive
LcProperties & properties
int selectedOffset
bool speedOverride
QMultiMap< long, Handle(AIS_InteractiveObject)> toolPath
ToolTable & toolTable
Constructor & Destructor Documentation
IFSettings()
CanonIF::IFSettings::IFSettings (LcProperties & lcProperties, ToolTable & toolTable) private
References LcProperties::baseDir(), canon, iTraverseRate, machineUnits, properties, and LcProperties::value().
Member Function Documentation
changeTool()
void CanonIF::IFSettings::changeTool (int ttIndex) private
References ToolEntry::toCanon().
Referenced by CanonIF::changeTool().
g5xOffset()
CANON_POSITION CanonIF::IFSettings::g5xOffset (int i) const private
Referenced by CanonIF::g5xOffset().
isSpeedOverrideEnabled()
bool CanonIF::IFSettings::isSpeedOverrideEnabled (int) const inline private
References speedOverride.
Referenced by CanonIF::isSpeedOverrideEnabled().
lengthUnits()
double CanonIF::IFSettings::lengthUnits () const private
CanonIF::IFSettings::lengthUnits.
Returns
factor to convert jobUnits into machineUnits
References CanonIF::machineUnits().
Referenced by CanonIF::lengthUnits().
selectPlane()
void CanonIF::IFSettings::selectPlane (CANON_PLANE p) inline private
References canon.
Referenced by CanonIF::selectPlane().
setCurSegColor()
void CanonIF::IFSettings::setCurSegColor (const QColor & c) private
References convertColor().
Referenced by CanonIF::setCurSegColor().
setEndPoint()
void CanonIF::IFSettings::setEndPoint (const CANON_POSITION & p) private
Referenced by CanonIF::setEndPoint().
setFeedColor()
void CanonIF::IFSettings::setFeedColor (const QColor & c) private
References convertColor().
Referenced by CanonIF::setFeedColor().
setG5xOffset()
void CanonIF::IFSettings::setG5xOffset (int i, const CANON_POSITION & p) private
References CanonIF::selectedOffset().
Referenced by CanonIF::setG5xOffset().
setG92Offset()
void CanonIF::IFSettings::setG92Offset (const CANON_POSITION & p) inline private
References canon.
Referenced by CanonIF::setG92Offset().
setJobUnits()
void CanonIF::IFSettings::setJobUnits (CANON_UNITS u) inline private
References canon.
Referenced by CanonIF::setLengthUnits().
setLimitsColor()
void CanonIF::IFSettings::setLimitsColor (const QColor & c) private
References convertColor().
Referenced by CanonIF::setLimitsColor().
setMotionMode()
void CanonIF::IFSettings::setMotionMode (CANON_MOTION_MODE mode, double tolerance) private
Referenced by CanonIF::setMotionMode().
setOldSegColor()
void CanonIF::IFSettings::setOldSegColor (const QColor & c) private
References convertColor().
Referenced by CanonIF::setOldSegColor().
setSpindleMode()
void CanonIF::IFSettings::setSpindleMode (int spindle, double css_max) inline private
References canon.
Referenced by CanonIF::setSpindleMode().
setToolOffset()
void CanonIF::IFSettings::setToolOffset (EmcPose offset) inline private
References canon.
Referenced by CanonIF::setToolOffset().
setTraverseColor()
void CanonIF::IFSettings::setTraverseColor (const QColor & c) private
References convertColor().
Referenced by CanonIF::setTraverseColor().
setWorkPieceColor()
void CanonIF::IFSettings::setWorkPieceColor (const QColor & c) private
References convertColor().
Referenced by CanonIF::setWorkPieceColor().
setXYRotation()
void CanonIF::IFSettings::setXYRotation (double r) inline private
References canon.
Referenced by CanonIF::setXYRotation().
spindleDir()
CANON_DIRECTION CanonIF::IFSettings::spindleDir (int spindle) const private
Referenced by CanonIF::spindleDir().
spindleSpeed()
double CanonIF::IFSettings::spindleSpeed (int spindle) const private
Referenced by CanonIF::spindleSpeed().
toolEntry()
CANON_TOOL_TABLE CanonIF::IFSettings::toolEntry (int ttIndex) const private
References ToolEntry::toCanon().
Referenced by CanonIF::toolEntry().
Member Data Documentation
adaptiveFeed
bool CanonIF::IFSettings::adaptiveFeed private
Referenced by CanonIF::isAdaptiveFeedEnabled().
canon
CanonConfig_t CanonIF::IFSettings::canon private
Referenced by IFSettings(), CanonIF::activePlane(), CanonIF::activeSpindle(), CanonIF::endPoint(), CanonIF::feedRate(), CanonIF::g92Offset(), CanonIF::motionMode(), CanonIF::motionTolerance(), CanonIF::naiveTolerance(), CanonIF::posA(), CanonIF::posB(), CanonIF::posC(), CanonIF::posU(), CanonIF::posV(), CanonIF::posW(), CanonIF::posX(), CanonIF::posY(), CanonIF::posZ(), selectPlane(), setG92Offset(), setJobUnits(), setSpindleMode(), setToolOffset(), setXYRotation(), CanonIF::toolOffset(), and CanonIF::xyRotation().
changer
StupidToolChangerIF CanonIF::IFSettings::changer private
Referenced by CanonIF::lastSlot(), CanonIF::nextSlot(), and CanonIF::selectTool().
colCurSeg
Quantity_Color CanonIF::IFSettings::colCurSeg private
Referenced by CanonIF::curSegColor().
colFeed
Quantity_Color CanonIF::IFSettings::colFeed private
Referenced by CanonIF::feedColor().
colLimits
Quantity_Color CanonIF::IFSettings::colLimits private
Referenced by CanonIF::limitColor().
colOldSeg
Quantity_Color CanonIF::IFSettings::colOldSeg private
Referenced by CanonIF::oldSegColor().
colTraverse
Quantity_Color CanonIF::IFSettings::colTraverse private
Referenced by CanonIF::traverseColor().
colWorkPiece
Quantity_Color CanonIF::IFSettings::colWorkPiece private
Referenced by CanonIF::workPieceColor().
feedHold
bool CanonIF::IFSettings::feedHold private
Referenced by CanonIF::isFeedHoldActive().
feedOverride
bool CanonIF::IFSettings::feedOverride private
Referenced by CanonIF::isFeedOverrideEnabled().
floodActive
bool CanonIF::IFSettings::floodActive private
Referenced by CanonIF::isFloodActive().
g5xOffsets
CANON_POSITION CanonIF::IFSettings::g5xOffsets[9] private
gf
GraphicFactory CanonIF::IFSettings::gf private
Referenced by CanonIF::graphicFactory().
iTraverseRate
double CanonIF::IFSettings::iTraverseRate private
Referenced by IFSettings(), and CanonIF::traverseRate().
machineUnits
CANON_UNITS CanonIF::IFSettings::machineUnits private
Referenced by IFSettings(), and CanonIF::machineUnits().
mistActive
bool CanonIF::IFSettings::mistActive private
Referenced by CanonIF::isMistActive().
properties
LcProperties& CanonIF::IFSettings::properties private
Referenced by IFSettings(), CanonIF::lcProperties(), and CanonIF::parameterFilename().
selectedOffset
int CanonIF::IFSettings::selectedOffset private
Referenced by CanonIF::selectedOffset().
speedOverride
bool CanonIF::IFSettings::speedOverride private
Referenced by isSpeedOverrideEnabled().
toolPath
QMultiMap<long, Handle(AIS_InteractiveObject)> CanonIF::IFSettings::toolPath private
Referenced by CanonIF::appendShape(), and CanonIF::toolPath().
toolTable
ToolTable& CanonIF::IFSettings::toolTable private
The documentation for this class was generated from the following files:
src/lcLib/control/canonif.h
src/lcLib/control/canonif.cpp