FalconView: ValueManager Class Reference
ValueManager Class Reference
#include <valuemanager.h>
Classes
class ValueHolder
Public Member Functions
ValueManager ()
void dump ()
ValueModel * getModel (const QString &name, const QVariant &defaultValue=QVariant())
QVariant getValue (const QString &name)
void setValue (const QString &name, const QVariant &value)
Private Member Functions
ValueManager (void *p)
Static Private Attributes
static ValueHolder * instance = nullptr
Constructor & Destructor Documentation
ValueManager() [1/2]
ValueManager::ValueManager ()
References instance.
ValueManager() [2/2]
ValueManager::ValueManager (void * p) private
References instance.
Member Function Documentation
dump()
void ValueManager::dump ()
References ValueManager::ValueHolder::dump(), and instance.
getModel()
ValueModel * ValueManager::getModel (const QString & name, const QVariant & defaultValue = QVariant())
References instance, and ValueManager::ValueHolder::models.
Referenced by AxisMask::calcActive(), PositionStatus::connectPos(), SettingsNotebook::connectSignals(), TestEdit::connectSignals(), JogView::connectSignals(), PathEditor::connectSignals(), PreViewEditor::connectSignals(), CurCodesStatus::connectSignals(), PositionStatus::connectSignals(), SpeedStatus::connectSignals(), ToolStatus::connectSignals(), MainWindow::createActions(), MainWindow::createConnections(), MainWindow::floodToggle(), MainWindow::mistToggle(), PreferencesEditor::setupLabels(), MultiStateToolButton::stateChanged(), MainWindow::tellStates(), and MainWindow::toggleAllButCenter().
getValue()
QVariant ValueManager::getValue (const QString & name)
References ValueModel::getValue(), instance, and ValueManager::ValueHolder::models.
Referenced by MainWindow::autoPause(), MainWindow::autoStart(), AxisMask::calcActive(), TestEdit::connectSignals(), CurCodesStatus::connectSignals(), SpeedStatus::connectSignals(), ToolStatus::connectSignals(), SysEventView::eventFilter(), ConfigManager::getBackground(), ConfigManager::getFont(), ConfigManager::getForeground(), GCodeEditor::highlightCurrentLine(), TestMain::initialize(), TestEdit::loadFile(), GCodeEditor::paintLineNumbers(), FixtureEdit::saveFixture(), PreferencesEditor::setupLabels(), MainWindow::startSpindleCCW(), MainWindow::startSpindleCW(), MainWindow::stopSpindle(), TestEdit::updateStyles(), FixtureManager::updateStyles(), CurCodesStatus::updateStyles(), PositionStatus::updateStyles(), SpeedStatus::updateStyles(), and ToolStatus::updateStyles().
setValue()
void ValueManager::setValue (const QString & name, const QVariant & value)
References instance, ValueManager::ValueHolder::models, and ValueModel::setValue().
Referenced by GCodeInfo::GCodeInfo(), GuiKernel::checkBE(), AxisMask::checkHomed(), PathEditor::connectSignals(), PositionCalculator::createModels(), StatusReader::createModels(), MainWindow::createValueModels(), PathEditor::dirtyChanged(), SysEventView::eventFilter(), SpeedStatus::fastFeedChanged(), SpeedStatus::feedChanged(), TestMain::initialize(), ConfigManager::initialize(), MainWindow::keyPressEvent(), PathEditor::loadFile(), Core::riseError(), GuiCore::riseError(), MainWindow::setAppMode(), Core::setAppMode(), GuiKernel::setAppMode4PageID(), ConfigManager::setBackground(), ConfigManager::setFont(), ConfigManager::setForeground(), MainWindow::setSingleStep(), JogView::setStepSize(), PreferencesEditor::setupLabels(), Core::showAllButCenter(), MainWindow::showErrMessages(), JogView::sliderChanged(), SpeedStatus::speedChanged(), GuiKernel::timerEvent(), MainWindow::toggleAbsolute(), StatusReader::update(), PositionCalculator::update(), and GCodeInfo::update().
Member Data Documentation
instance
ValueManager::ValueHolder * ValueManager::instance = nullptr static private
Referenced by ValueManager(), PluginPageFactory::createCenterPage(), PluginPageFactory::createDockable(), PluginPageFactory::createNotebookPage(), dump(), getModel(), getValue(), and setValue().
The documentation for this class was generated from the following files:
src/baselib/model/valuemanager.h
src/baselib/model/valuemanager.cpp