FalconView: ConfigManager Class Reference
ConfigManager Class Reference
#include <configmgr.h>
Public Member Functions
ConfigManager (const QString &appName="Config-Manager", const QString &group="SRD")
QColor getBackground (int index)
QFont getFont (int index)
QColor getForeground (int index)
QString geToString (int i)
void initialize ()
void setBackground (int index, const QColor &color)
void setFont (int index, const QFont &font)
void setForeground (int index, const QColor &color)
void setValue (const QString &key, const QVariant &value)
QVariant value (const QString &key, const QVariant &defaultValue=QVariant()) const
Public Attributes
QString iniFileName
QSettings settings
ValueManager vm
Private Attributes
const int lastIndex
Static Private Attributes
static const char * guiElemNames []
Constructor & Destructor Documentation
ConfigManager()
ConfigManager::ConfigManager (const QString & appName = "Config-Manager", const QString & group = "SRD")
References initialize().
Member Function Documentation
getBackground()
QColor ConfigManager::getBackground (int index)
References geToString(), ValueManager::getValue(), lastIndex, and vm.
Referenced by Config::getBackground().
getFont()
QFont ConfigManager::getFont (int index)
References geToString(), ValueManager::getValue(), lastIndex, and vm.
Referenced by Config::getFont().
getForeground()
QColor ConfigManager::getForeground (int index)
References geToString(), ValueManager::getValue(), lastIndex, and vm.
Referenced by Config::getForeground(), and GuiKernel::initialize().
geToString()
QString ConfigManager::geToString (int i)
References asString.
Referenced by getBackground(), getFont(), getForeground(), initialize(), Config::nameOf(), setBackground(), setFont(), and setForeground().
initialize()
void ConfigManager::initialize ()
References geToString(), lastIndex, settings, ValueManager::setValue(), and vm.
Referenced by ConfigManager().
setBackground()
void ConfigManager::setBackground (int index, const QColor & color)
References geToString(), lastIndex, settings, ValueManager::setValue(), and vm.
Referenced by Config::setBackground().
setFont()
void ConfigManager::setFont (int index, const QFont & font)
References geToString(), lastIndex, settings, ValueManager::setValue(), and vm.
Referenced by Config::setFont().
setForeground()
void ConfigManager::setForeground (int index, const QColor & color)
References geToString(), lastIndex, settings, ValueManager::setValue(), and vm.
Referenced by Config::setForeground().
setValue()
void ConfigManager::setValue (const QString & key, const QVariant & value)
References settings, and value().
Referenced by GuiKernel::initialize(), Config::setValue(), and GuiKernel::windowClosing().
value()
QVariant ConfigManager::value (const QString & key, const QVariant & defaultValue = QVariant()) const
References settings.
Referenced by GuiKernel::initialize(), setValue(), Core::showHelpAtPageChange(), and Config::value().
Member Data Documentation
guiElemNames
const char* ConfigManager::guiElemNames[] static private
iniFileName
QString ConfigManager::iniFileName
lastIndex
const int ConfigManager::lastIndex private
Referenced by getBackground(), getFont(), getForeground(), initialize(), setBackground(), setFont(), and setForeground().
settings
QSettings ConfigManager::settings
Referenced by Config::beginGroup(), Config::endGroup(), initialize(), setBackground(), setFont(), setForeground(), setValue(), value(), and GuiKernel::windowClosing().
vm
ValueManager ConfigManager::vm
Referenced by getBackground(), getFont(), getForeground(), initialize(), setBackground(), setFont(), and setForeground().
The documentation for this class was generated from the following files:
src/baselib/model/configmgr.h
src/baselib/model/configmgr.cpp