FalconView: DBHelper Class Reference
DBHelper Class Reference abstract
#include <dbhelper.h>
Public Member Functions
virtual bool connect (const QString &path)=0
virtual DBConnection * createDatabase (const QString &path)=0
virtual void createSampleData (DBConnection &conn)=0
DBConnection * dbConnection ()
Protected Attributes
DBConnection * conn
Member Function Documentation
connect()
virtual bool DBHelper::connect (const QString & path) pure virtual
Implemented in FalconViewDB.
Referenced by GuiKernel::initialize().
createDatabase()
virtual DBConnection* DBHelper::createDatabase (const QString & path) pure virtual
Implemented in FalconViewDB.
Referenced by GuiKernel::createDatabase().
createSampleData()
virtual void DBHelper::createSampleData (DBConnection & conn) pure virtual
Implemented in FalconViewDB.
Referenced by GuiKernel::createDatabase().
dbConnection()
DBConnection* DBHelper::dbConnection () inline
References conn.
Referenced by GuiKernel::createDatabase(), and GuiKernel::initialize().
Member Data Documentation
conn
DBConnection* DBHelper::conn protected
Referenced by FalconViewDB::connect(), FalconViewDB::createDatabase(), FalconViewDB::createSampleData(), and dbConnection().
The documentation for this class was generated from the following file:
src/baselib/util/dbhelper.h