FalconView: CenterPage Class Reference
CenterPage Class Reference
#include <centerpage.h>
Public Member Functions
CenterPage (AbstractCenterWidget *cw, bool visualFrame=false, QWidget *parent=nullptr)
AbstractCenterWidget * centerWidget ()
AbstractCenterWidget * centerWidget () const
virtual void closeEvent (QCloseEvent *e) override
QString id () const
QString name () const
QAction * viewAction ()
Private Attributes
AbstractCenterWidget * dcw
QFrame * frame
Constructor & Destructor Documentation
CenterPage()
CenterPage::CenterPage (AbstractCenterWidget * cw, bool visualFrame = false, QWidget * parent = nullptr) explicit
References dcw, and frame.
Member Function Documentation
centerWidget() [1/2]
AbstractCenterWidget* CenterPage::centerWidget () inline
References dcw.
Referenced by TestEdit::openFile().
centerWidget() [2/2]
AbstractCenterWidget* CenterPage::centerWidget () const inline
References dcw.
closeEvent()
void CenterPage::closeEvent (QCloseEvent * e) override virtual
References AbstractCenterWidget::closeEvent(), and dcw.
id()
QString CenterPage::id () const
References dcw.
name()
QString CenterPage::name () const
References dcw.
Referenced by PageStack::activatePage(), and MainWindow::testTools().
viewAction()
QAction * CenterPage::viewAction ()
References dcw, and AbstractCenterWidget::viewAction().
Referenced by PageStack::addPage().
Member Data Documentation
dcw
AbstractCenterWidget* CenterPage::dcw private
Referenced by CenterPage(), centerWidget(), closeEvent(), id(), name(), and viewAction().
frame
QFrame* CenterPage::frame private
Referenced by CenterPage().
The documentation for this class was generated from the following files:
src/guiLib/view/centerpage.h
src/guiLib/view/centerpage.cpp