FalconView: JogView Class Reference
JogView Class Reference
#include <jogview.h>
Signals
void dataChanged (AbstractCenterWidget *w, const QVariant &changed)
Public Member Functions
JogView (QWidget *parent=nullptr)
virtual ~JogView ()
virtual void closeEvent (QCloseEvent *e) override
virtual void showEvent (QShowEvent *e) override
QAction * viewAction ()
Protected Member Functions
virtual void connectSignals () override
virtual QWidget * createContent () override
void decStepSize ()
virtual bool eventFilter (QObject *src, QEvent *event) override
virtual QString fileName () const
void incStepSize ()
virtual void initialize (const QString &name=QString())
void jog (QWidget *o, int axis, int step)
void jogVelChanged ()
virtual void keyPressEvent (QKeyEvent *event) override
virtual void patch (void *pk, void *pc, void *pv, void *pu=nullptr, bool flag=false)
void setStepSize ()
virtual void setupUi (AbstractCenterWidget *parent)
void singleStep (bool singleStep)
void sliderChanged (const QVariant &v)
void stepSizeChanged (const QVariant &stepSize)
virtual void updateStyles () override
Protected Attributes
Config * cfg
GuiCore * core
ValueManager * vm
Private Attributes
bool addScrollArea
double defSpeed
double jogSpeed
double maxSpeed
QList< QRadioButton * > rbl
double stepSize
Ui::JogForm * ui
QString uiFileName
QAction * vAction
Constructor & Destructor Documentation
JogView()
JogView::JogView (QWidget * parent = nullptr) explicit
~JogView()
JogView::~JogView () virtual
Member Function Documentation
closeEvent()
void AbstractCenterWidget::closeEvent (QCloseEvent * e) override virtual inherited
Implements PluginPageInterface.
Reimplemented in HelpView, TestEdit, PreViewEditor, ToolManager, SettingsNotebook, FileManager, and LCToolTable.
Referenced by SettingsNotebook::closeEvent(), Dockable::closeEvent(), and CenterPage::closeEvent().
connectSignals()
void JogView::connectSignals () override protected virtual
Implements PluginPageInterface.
References ValueManager::getModel(), jogVelChanged(), setStepSize(), singleStep(), sliderChanged(), stepSizeChanged(), ui, ValueModel::valueChanged(), and AbstractCenterWidget::vm.
createContent()
QWidget * JogView::createContent () override protected virtual
Reimplemented from AbstractCenterWidget.
References AbstractCenterWidget::core, GuiCore::defaultVelocity(), defSpeed, jogVelChanged(), maxSpeed, GuiCore::maxVelocity(), rbl, setStepSize(), setupUi(), singleStep(), sliderChanged(), and ui.
dataChanged
void AbstractCenterWidget::dataChanged (AbstractCenterWidget * w, const QVariant & changed) signal inherited
Referenced by SettingsNotebook::addPage(), LCToolTable::keyPressEvent(), and LCToolTable::modelChanged().
decStepSize()
void JogView::decStepSize () protected
References rbl.
Referenced by eventFilter().
eventFilter()
bool JogView::eventFilter (QObject * src, QEvent * event) override protected virtual
References decStepSize(), incStepSize(), and ui.
fileName()
QString AbstractCenterWidget::fileName () const protected virtual inherited
Reimplemented in SpeedStatus, and CurCodesStatus.
References AbstractCenterWidget::uiFileName.
Referenced by AbstractCenterWidget::createContent().
incStepSize()
void JogView::incStepSize () protected
References rbl.
Referenced by eventFilter().
initialize()
void AbstractCenterWidget::initialize (const QString & name = QString()) protected virtual inherited
References AbstractCenterWidget::cfg, PluginPageInterface::connectSignals(), AbstractCenterWidget::core, AbstractCenterWidget::createContent(), PluginPageInterface::updateStyles(), and AbstractCenterWidget::vm.
Referenced by PluginPageFactory::createCenterPage(), FixtureManager::createContent(), PluginPageFactory::createDockable(), and PluginPageFactory::createNotebookPage().
jog()
void JogView::jog (QWidget * o, int axis, int step) protected
References GuiCore::beJogStart(), GuiCore::beJogStep(), GuiCore::beJogStop(), AbstractCenterWidget::core, jogSpeed, stepSize, and ui.
jogVelChanged()
void JogView::jogVelChanged () protected
References AbstractCenterWidget::core, defSpeed, Core::locale(), maxSpeed, sliderChanged(), and ui.
Referenced by connectSignals(), and createContent().
keyPressEvent()
void JogView::keyPressEvent (QKeyEvent * event) override protected virtual
References ui.
patch()
void AbstractCenterWidget::patch (void * pk, void * pc, void * pv, void * pu = nullptr, bool flag = false) protected virtual inherited
Reimplemented in SpeedStatus, CurCodesStatus, and PreViewEditor.
References AbstractCenterWidget::cfg, AbstractCenterWidget::core, Core::kernel, and AbstractCenterWidget::vm.
Referenced by PluginPageFactory::createCenterPage(), PluginPageFactory::createDockable(), PluginPageFactory::createNotebookPage(), PreViewEditor::patch(), CurCodesStatus::patch(), and SpeedStatus::patch().
setStepSize()
void JogView::setStepSize () protected
References ValueManager::setValue(), stepSize, ui, and AbstractCenterWidget::vm.
Referenced by connectSignals(), and createContent().
setupUi()
void JogView::setupUi (AbstractCenterWidget * parent) protected virtual
References GuiCore::axisMask(), AbstractCenterWidget::core, AxisMask::hasAAxis(), AxisMask::hasBAxis(), AxisMask::hasCAxis(), AxisMask::hasUAxis(), AxisMask::hasVAxis(), AxisMask::hasWAxis(), AxisMask::hasXAxis(), AxisMask::hasYAxis(), AxisMask::hasZAxis(), and ui.
Referenced by createContent().
showEvent()
void AbstractCenterWidget::showEvent (QShowEvent * e) override virtual inherited
Implements PluginPageInterface.
Reimplemented in SysEventView, PreViewEditor, ToolManager, FixtureManager, TestEdit, FileManager, and SettingsNotebook.
References AbstractCenterWidget::cfg, AbstractCenterWidget::core, GuiCore::help4Keyword(), and Config::value().
Referenced by SettingsNotebook::showEvent(), PreferencesEditor::showEvent(), FileManager::showEvent(), TestEdit::showEvent(), FixtureManager::showEvent(), ToolManager::showEvent(), and MDIEditor::showEvent().
singleStep()
void JogView::singleStep (bool singleStep) protected
References ui.
Referenced by connectSignals(), and createContent().
sliderChanged()
void JogView::sliderChanged (const QVariant & v) protected
References AbstractCenterWidget::core, defSpeed, jogSpeed, Core::locale(), maxSpeed, ValueManager::setValue(), ui, and AbstractCenterWidget::vm.
Referenced by connectSignals(), createContent(), and jogVelChanged().
stepSizeChanged()
void JogView::stepSizeChanged (const QVariant & stepSize) protected
References stepSize, and ui.
Referenced by connectSignals().
updateStyles()
void JogView::updateStyles () override protected virtual
Implements PluginPageInterface.
viewAction()
QAction * AbstractCenterWidget::viewAction () inherited
References AbstractCenterWidget::vAction.
Referenced by Dockable::viewAction(), and CenterPage::viewAction().
Member Data Documentation
addScrollArea
bool AbstractCenterWidget::addScrollArea private inherited
Referenced by AbstractCenterWidget::createContent().
cfg
Config* AbstractCenterWidget::cfg protected inherited
Referenced by PreferencesEditor::changeBackgroundColor(), PreferencesEditor::changeFont(), PreferencesEditor::changeForegroundColor(), LCToolTable::closeEvent(), FileManager::closeEvent(), ToolManager::closeEvent(), MDIEditor::closeEvent(), PreViewEditor::closeEvent(), TestEdit::closeEvent(), PositionStatus::connectPos(), TestEdit::connectSignals(), PreferencesEditor::connectSignals(), CurCodesStatus::connectSignals(), PositionStatus::connectSignals(), SpeedStatus::connectSignals(), ToolStatus::connectSignals(), LCToolTable::createContent(), FileManager::createContent(), PreferencesEditor::createContent(), ToolManager::createContent(), MDIEditor::createContent(), PreViewEditor::createContent(), SysEventView::createContent(), SettingsNotebook::currentChanged(), SysEventView::eventFilter(), AbstractCenterWidget::initialize(), AbstractCenterWidget::patch(), PreferencesEditor::previewCenterChanged(), HelpView::restoreState(), TestEdit::restoreState(), HelpView::saveState(), PreferencesEditor::setupLabels(), AbstractCenterWidget::showEvent(), SettingsNotebook::showEvent(), PreferencesEditor::statusInsideChanged(), PreferencesEditor::statusShowHelpChanged(), PreferencesEditor::statusToolMgrChanged(), TestEdit::updateStyles(), FixtureManager::updateStyles(), CurCodesStatus::updateStyles(), PositionStatus::updateStyles(), SpeedStatus::updateStyles(), and ToolStatus::updateStyles().
core
GuiCore* AbstractCenterWidget::core protected inherited
Referenced by LCToolTable::closeEvent(), LCToolTable::connectSignals(), LCToolTable::createContent(), HelpView::createContent(), FixtureManager::createContent(), ToolManager::createContent(), createContent(), SysEventView::createContent(), PositionStatus::createContent(), SettingsNotebook::currentChanged(), ToolManager::deleteTool(), ToolManager::editTool(), ToolManager::eventFilter(), SysEventView::eventFilter(), SpeedStatus::fastFeedChanged(), SpeedStatus::feedChanged(), AbstractCenterWidget::initialize(), jog(), jogVelChanged(), LCToolTable::keyPressEvent(), TestEdit::loadFile(), PathEditor::loadFile(), LCToolTable::modelChanged(), TestEdit::openFile(), AbstractCenterWidget::patch(), TestEdit::reallyLoadFile(), PathEditor::reallyLoadFile(), TestEdit::saveFile(), FixtureEdit::saveFixture(), ToolManager::saveToolChanges(), setupUi(), AbstractCenterWidget::showEvent(), SettingsNotebook::showEvent(), sliderChanged(), and SpeedStatus::speedChanged().
defSpeed
double JogView::defSpeed private
Referenced by createContent(), jogVelChanged(), and sliderChanged().
jogSpeed
double JogView::jogSpeed private
Referenced by jog(), and sliderChanged().
maxSpeed
double JogView::maxSpeed private
Referenced by createContent(), jogVelChanged(), and sliderChanged().
rbl
QList<QRadioButton*> JogView::rbl private
Referenced by createContent(), decStepSize(), and incStepSize().
stepSize
double JogView::stepSize private
Referenced by jog(), setStepSize(), and stepSizeChanged().
ui
Ui::JogForm* JogView::ui private
Referenced by connectSignals(), createContent(), eventFilter(), jog(), jogVelChanged(), keyPressEvent(), setStepSize(), setupUi(), singleStep(), sliderChanged(), and stepSizeChanged().
uiFileName
QString AbstractCenterWidget::uiFileName private inherited
Referenced by AbstractCenterWidget::fileName().
vAction
QAction* AbstractCenterWidget::vAction private inherited
Referenced by AbstractCenterWidget::viewAction().
vm
ValueManager* AbstractCenterWidget::vm protected inherited
Referenced by PositionStatus::connectPos(), SettingsNotebook::connectSignals(), TestEdit::connectSignals(), connectSignals(), PathEditor::connectSignals(), PreViewEditor::connectSignals(), CurCodesStatus::connectSignals(), PositionStatus::connectSignals(), SpeedStatus::connectSignals(), ToolStatus::connectSignals(), PathEditor::dirtyChanged(), SysEventView::eventFilter(), SpeedStatus::fastFeedChanged(), SpeedStatus::feedChanged(), AbstractCenterWidget::initialize(), TestEdit::loadFile(), PathEditor::loadFile(), AbstractCenterWidget::patch(), FixtureEdit::saveFixture(), setStepSize(), PreferencesEditor::setupLabels(), sliderChanged(), SpeedStatus::speedChanged(), TestEdit::updateStyles(), FixtureManager::updateStyles(), CurCodesStatus::updateStyles(), PositionStatus::updateStyles(), SpeedStatus::updateStyles(), and ToolStatus::updateStyles().
The documentation for this class was generated from the following files:
src/plugPages/JogView/jogview.h
src/plugPages/JogView/jogview.cpp