FalconView: Category Class Reference
Category Class Reference
#include <category.h>
Public Member Functions
Category (Category *parent=nullptr)
Category (const QSqlRecord &rec)
Category (int id, const QString &name)
~Category ()
Category * child (int number)
int childCount () const
int childNumber () const
int columnCount () const
QVariant data (int column) const
bool insertChildren (int position, int count, int columns)
bool insertColumns (int position, int columns)
Category * parent ()
bool remove ()
bool removeChildren (int position, int count)
bool removeColumns (int position, int columns)
bool setData (int column, const QVariant &value)
bool updateName (const QString &name)
Private Attributes
QList< Category * > childItems
Category * parentItem
Constructor & Destructor Documentation
Category() [1/3]
Category::Category (int id, const QString & name) explicit
Referenced by insertChildren().
Category() [2/3]
Category::Category (Category * parent = nullptr) explicit
Category() [3/3]
Category::Category (const QSqlRecord & rec) explicit
~Category()
Category::~Category ()
References childItems.
Member Function Documentation
child()
Category * Category::child (int number)
References childItems.
Referenced by CategoryTreeModel::CategoryTreeModel(), ToolManager::createCategory(), CategoryTreeModel::index(), CategoryTreeModel::root(), and CategoryTreeModel::setupModelData().
childCount()
int Category::childCount () const
References childItems.
Referenced by ToolManager::deleteCategory(), and CategoryTreeModel::rowCount().
childNumber()
int Category::childNumber () const
References childItems, and parentItem.
Referenced by CategoryTreeModel::parent().
columnCount()
int Category::columnCount () const
Referenced by CategoryTreeModel::CategoryTreeModel(), CategoryTreeModel::columnCount(), CategoryTreeModel::insertRows(), CategoryTreeModel::removeColumns(), and CategoryTreeModel::setupModelData().
data()
QVariant Category::data (int column) const
Referenced by ToolManager::createCategory(), CategoryTreeModel::data(), and ToolManager::deleteCategory().
insertChildren()
bool Category::insertChildren (int position, int count, int columns)
References Category(), and childItems.
Referenced by CategoryTreeModel::CategoryTreeModel(), and CategoryTreeModel::insertRows().
insertColumns()
bool Category::insertColumns (int position, int columns)
Referenced by CategoryTreeModel::insertColumns().
parent()
Category * Category::parent ()
References parentItem.
Referenced by CategoryTreeModel::parent().
remove()
bool Category::remove ()
Referenced by ToolManager::deleteCategory().
removeChildren()
bool Category::removeChildren (int position, int count)
References childItems.
Referenced by CategoryTreeModel::removeRows().
removeColumns()
bool Category::removeColumns (int position, int columns)
Referenced by CategoryTreeModel::removeColumns().
setData()
bool Category::setData (int column, const QVariant & value)
Referenced by CategoryTreeModel::CategoryTreeModel(), CategoryTreeModel::setData(), CategoryTreeModel::setHeaderData(), and CategoryTreeModel::setupModelData().
updateName()
bool Category::updateName (const QString & name)
Referenced by ToolManager::renameCategory().
Member Data Documentation
childItems
QList<Category*> Category::childItems private
Referenced by ~Category(), child(), childCount(), childNumber(), insertChildren(), and removeChildren().
parentItem
Category* Category::parentItem private
Referenced by childNumber(), and parent().
The documentation for this class was generated from the following files:
src/nbPages/ToolManager/category.h
src/nbPages/ToolManager/category.cpp