FalconView: TestMain Class Reference
TestMain Class Reference
#include <testmain.h>
Public Member Functions
TestMain (QWidget *parent=nullptr)
virtual ~TestMain ()=default
void checkPlugins ()
void initialize ()
void loadPlugins ()
void pluginsAbout ()
void testPlugin ()
Private Attributes
QAction * aboutPlugins = nullptr
QStringList pluginFileNames
QDir pluginsDir
Ui::MainWindow * ui = nullptr
Constructor & Destructor Documentation
TestMain()
TestMain::TestMain (QWidget * parent = nullptr) explicit
~TestMain()
virtual TestMain::~TestMain () virtual default
Member Function Documentation
checkPlugins()
void TestMain::checkPlugins ()
References GuiCore::pluggableMainPage().
Referenced by initialize().
initialize()
void TestMain::initialize ()
References aboutPlugins, checkPlugins(), ValueManager::getValue(), pluginsAbout(), pluginsDir, ValueManager::setValue(), testPlugin(), ui, and Config::value().
loadPlugins()
void TestMain::loadPlugins ()
References pluginFileNames, and pluginsDir.
pluginsAbout()
void TestMain::pluginsAbout ()
References pluginFileNames, and pluginsDir.
Referenced by initialize().
testPlugin()
void TestMain::testPlugin ()
Referenced by initialize().
Member Data Documentation
aboutPlugins
QAction* TestMain::aboutPlugins = nullptr private
Referenced by initialize().
pluginFileNames
QStringList TestMain::pluginFileNames private
Referenced by loadPlugins(), and pluginsAbout().
pluginsDir
QDir TestMain::pluginsDir private
Referenced by initialize(), loadPlugins(), and pluginsAbout().
ui
Ui::MainWindow* TestMain::ui = nullptr private
Referenced by initialize().
The documentation for this class was generated from the following files:
src/app/control/testmain.h
src/app/control/testmain.cpp