FalconView: ValueModel Class Reference
ValueModel Class Reference
#include <valuemodel.h>
Signals
void valueChanged (const QVariant &newValue)
Public Member Functions
ValueModel (const QString &name, const QVariant &value=0)
void dump () const
QString getName () const
QVariant getValue () const
void setValue (const QVariant &value)
Private Attributes
QString n
QVariant v
Constructor & Destructor Documentation
ValueModel()
ValueModel::ValueModel (const QString & name, const QVariant & value = 0) explicit
Member Function Documentation
dump()
void ValueModel::dump () const
References n, and v.
Referenced by MultiStateToolButton::stateChanged(), and MainWindow::tellStates().
getName()
QString ValueModel::getName () const inline
References n.
Referenced by AbstractCondition::name().
getValue()
QVariant ValueModel::getValue () const inline
References v.
Referenced by CurCodesStatus::connectSignals(), EqualCondition::eval(), GreaterCondition::eval(), NotCondition::eval(), SmallerCondition::eval(), MainWindow::floodToggle(), ValueManager::getValue(), MainWindow::mistToggle(), and MainWindow::toggleAllButCenter().
setValue()
void ValueModel::setValue (const QVariant & value)
References v, and valueChanged().
Referenced by ValueManager::setValue(), TestEngine::testAnd3Condition(), TestEngine::testAnd4Condition(), TestEngine::testAndCondition(), TestEngine::testBoolean(), TestEngine::testEqualCondition(), TestEngine::testGreaterCondition(), TestEngine::testOrCondition(), and TestEngine::testSmallerCondition().
valueChanged
void ValueModel::valueChanged (const QVariant & newValue) signal
Referenced by AbstractCondition::AbstractCondition(), MultiStateToolButton::MultiStateToolButton(), AxisMask::calcActive(), PositionStatus::connectPos(), SettingsNotebook::connectSignals(), TestEdit::connectSignals(), JogView::connectSignals(), PathEditor::connectSignals(), PreViewEditor::connectSignals(), CurCodesStatus::connectSignals(), PositionStatus::connectSignals(), SpeedStatus::connectSignals(), ToolStatus::connectSignals(), MainWindow::createConnections(), GuiKernel::initialize(), Ally3D::setOcctViewer(), PreferencesEditor::setupLabels(), and setValue().
Member Data Documentation
n
QString ValueModel::n private
Referenced by dump(), and getName().
v
QVariant ValueModel::v private
Referenced by dump(), getValue(), and setValue().
The documentation for this class was generated from the following files:
src/baselib/model/valuemodel.h
src/baselib/model/valuemodel.cpp