FalconView: TimeStamp Class Reference
TimeStamp Class Reference
#include <timestamp.h>
Static Public Member Functions
static long rtSequence ()
Member Function Documentation
rtSequence()
long TimeStamp::rtSequence () static
Referenced by SysEvent::SysEvent(), ToolManager::createContent(), FalconViewDB::createSysEventSamples(), ToolManager::deleteTool(), and ToolManager::eventFilter().
The documentation for this class was generated from the following files:
src/baselib/util/timestamp.h
src/baselib/util/timestamp.cpp