FalconView: DynDockable Class Reference
DynDockable Class Reference
#include <dyndockable.h>
Public Member Functions
DynDockable (AbstractCenterWidget *cw, QWidget *parent=nullptr)
AbstractCenterWidget * centerWidget ()
AbstractCenterWidget * centerWidget () const
QString id () const
void init (const QString &fileName, const QString &name, bool addScrollArea=false)
QString name () const
QAction * viewAction ()
Protected Member Functions
virtual void closeEvent (QCloseEvent *e) override
Static Protected Attributes
static const int DockingTitleHeight = 39
Private Attributes
AbstractCenterWidget * dcw
Constructor & Destructor Documentation
DynDockable()
DynDockable::DynDockable (AbstractCenterWidget * cw, QWidget * parent = nullptr)
Member Function Documentation
centerWidget() [1/2]
AbstractCenterWidget* DynDockable::centerWidget () inline
References dcw.
centerWidget() [2/2]
AbstractCenterWidget* DynDockable::centerWidget () const inline
References dcw.
closeEvent()
void DynDockable::closeEvent (QCloseEvent * e) override protected virtual
References AbstractCenterWidget::closeEvent(), and dcw.
id()
QString DynDockable::id () const
References dcw.
init()
void DynDockable::init (const QString & fileName, const QString & name, bool addScrollArea = false)
References dcw, AbstractCenterWidget::initialize(), and name().
name()
QString DynDockable::name () const
References dcw.
Referenced by init().
viewAction()
QAction * DynDockable::viewAction ()
References dcw, and AbstractCenterWidget::viewAction().
Member Data Documentation
dcw
AbstractCenterWidget* DynDockable::dcw private
Referenced by centerWidget(), closeEvent(), id(), init(), name(), and viewAction().
DockingTitleHeight
const int DynDockable::DockingTitleHeight = 39 static protected
The documentation for this class was generated from the following files:
src/app/view/dyndockable.h
src/app/view/dyndockable.cpp