FalconView: CategoryTreeModel Class Reference
CategoryTreeModel Class Reference
#include <CategoryTreeModel.h>
Public Member Functions
CategoryTreeModel (DBConnection &conn, QObject *parent=nullptr)
~CategoryTreeModel ()
int columnCount (const QModelIndex &parent=QModelIndex()) const override
QVariant data (const QModelIndex &index, int role) const override
Qt::ItemFlags flags (const QModelIndex &index) const override
QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const override
QModelIndex index (int row, int column, const QModelIndex &parent=QModelIndex()) const override
bool insertColumns (int position, int columns, const QModelIndex &parent=QModelIndex()) override
bool insertRows (int position, int rows, const QModelIndex &parent=QModelIndex()) override
QModelIndex parent (const QModelIndex &index) const override
bool removeColumns (int position, int columns, const QModelIndex &parent=QModelIndex()) override
bool removeRows (int position, int rows, const QModelIndex &parent=QModelIndex()) override
Category * root () const
int rowCount (const QModelIndex &parent=QModelIndex()) const override
bool setData (const QModelIndex &index, const QVariant &value, int role=Qt::EditRole) override
bool setHeaderData (int section, Qt::Orientation orientation, const QVariant &value, int role=Qt::EditRole) override
Private Member Functions
Category * getItem (const QModelIndex &index) const
void setupModelData (Category *parent)
Private Attributes
Category * rootItem
Static Private Attributes
static QVector< Category * > categories
Constructor & Destructor Documentation
CategoryTreeModel()
CategoryTreeModel::CategoryTreeModel (DBConnection & conn, QObject * parent = nullptr)
References Category::child(), Category::columnCount(), DBConnection::connect(), Category::insertChildren(), root(), rootItem, Category::setData(), and setupModelData().
~CategoryTreeModel()
CategoryTreeModel::~CategoryTreeModel ()
References rootItem.
Member Function Documentation
columnCount()
int CategoryTreeModel::columnCount (const QModelIndex & parent = QModelIndex()) const override
References Category::columnCount(), parent(), and rootItem.
Referenced by ToolManager::createCategory().
data()
QVariant CategoryTreeModel::data (const QModelIndex & index, int role) const override
References Category::data(), getItem(), and index().
Referenced by ToolManager::currentChanged(), and ToolManager::renameCategory().
flags()
Qt::ItemFlags CategoryTreeModel::flags (const QModelIndex & index) const override
References index().
getItem()
Category * CategoryTreeModel::getItem (const QModelIndex & index) const private
References index(), and rootItem.
Referenced by data(), index(), insertRows(), parent(), removeRows(), rowCount(), and setData().
headerData()
QVariant CategoryTreeModel::headerData (int section, Qt::Orientation orientation, int role = Qt::DisplayRole) const override
index()
QModelIndex CategoryTreeModel::index (int row, int column, const QModelIndex & parent = QModelIndex()) const override
References Category::child(), getItem(), and parent().
Referenced by ToolManager::createCategory(), ToolManager::currentChanged(), data(), flags(), getItem(), parent(), and setData().
insertColumns()
bool CategoryTreeModel::insertColumns (int position, int columns, const QModelIndex & parent = QModelIndex()) override
References Category::insertColumns(), parent(), and rootItem.
insertRows()
bool CategoryTreeModel::insertRows (int position, int rows, const QModelIndex & parent = QModelIndex()) override
References Category::columnCount(), getItem(), Category::insertChildren(), parent(), and rootItem.
parent()
QModelIndex CategoryTreeModel::parent (const QModelIndex & index) const override
References Category::childNumber(), getItem(), index(), Category::parent(), and rootItem.
Referenced by columnCount(), index(), insertColumns(), insertRows(), removeColumns(), removeRows(), rowCount(), and setupModelData().
removeColumns()
bool CategoryTreeModel::removeColumns (int position, int columns, const QModelIndex & parent = QModelIndex()) override
References Category::columnCount(), parent(), Category::removeColumns(), removeRows(), rootItem, and rowCount().
removeRows()
bool CategoryTreeModel::removeRows (int position, int rows, const QModelIndex & parent = QModelIndex()) override
References getItem(), parent(), and Category::removeChildren().
Referenced by ToolManager::deleteCategory(), and removeColumns().
root()
Category * CategoryTreeModel::root () const
References Category::child(), and rootItem.
Referenced by CategoryTreeModel(), and ToolManager::createCategory().
rowCount()
int CategoryTreeModel::rowCount (const QModelIndex & parent = QModelIndex()) const override
References Category::childCount(), getItem(), and parent().
Referenced by removeColumns().
setData()
bool CategoryTreeModel::setData (const QModelIndex & index, const QVariant & value, int role = Qt::EditRole) override
References getItem(), index(), and Category::setData().
Referenced by ToolManager::createCategory(), and ToolManager::renameCategory().
setHeaderData()
bool CategoryTreeModel::setHeaderData (int section, Qt::Orientation orientation, const QVariant & value, int role = Qt::EditRole) override
References rootItem, and Category::setData().
setupModelData()
void CategoryTreeModel::setupModelData (Category * parent) private
References categories, Category::child(), Category::columnCount(), parent(), rootItem, and Category::setData().
Referenced by CategoryTreeModel().
Member Data Documentation
categories
QVector< Category * > CategoryTreeModel::categories static private
Referenced by setupModelData().
rootItem
Category* CategoryTreeModel::rootItem private
Referenced by CategoryTreeModel(), ~CategoryTreeModel(), columnCount(), getItem(), insertColumns(), insertRows(), parent(), removeColumns(), root(), setHeaderData(), and setupModelData().
The documentation for this class was generated from the following files:
src/nbPages/ToolManager/CategoryTreeModel.h
src/nbPages/ToolManager/CategoryTreeModel.cpp