FalconView: Kernel Class Reference
Kernel Class Reference
#include <kernel.h>
Public Member Functions
virtual void logSysEvent (const SysEvent &se)
Protected Member Functions
Kernel (QApplication &app, const QString &appName, const QString &groupID)
virtual ~Kernel ()=default
virtual int axisMask () const
virtual QString fileName4 (const QString &fileID) const
virtual void initialize (DBHelper &dbAssist)
virtual void logSysEvent (const QString &msg)
virtual void processAppArgs (const QStringList &args)
virtual QLocale * setupTranslators ()
virtual QString version () const
Protected Attributes
QApplication & app
QString appName
ConfigManager * cfg
DBConnection * conn
QString groupID
QString langDir
QLocale * locale
bool simulator
QBasicTimer timer
Constructor & Destructor Documentation
Kernel()
Kernel::Kernel (QApplication & app, const QString & appName, const QString & groupID) explicit protected
~Kernel()
virtual Kernel::~Kernel () protected virtual default
Member Function Documentation
axisMask()
int Kernel::axisMask () const protected virtual
Reimplemented in GuiKernel.
Referenced by Core::axisMask().
fileName4()
QString Kernel::fileName4 (const QString & fileID) const protected virtual
Reimplemented in GuiKernel.
Referenced by Core::fileName4(), and GuiKernel::fileName4().
initialize()
void Kernel::initialize (DBHelper & dbAssist) protected virtual
Reimplemented in GuiKernel, and LCKernel.
References app, langDir, locale, processAppArgs(), and setupTranslators().
Referenced by Core::Core(), and GuiKernel::initialize().
logSysEvent() [1/2]
void Kernel::logSysEvent (const QString & msg) protected virtual
Reimplemented in GuiKernel.
References logSysEvent().
logSysEvent() [2/2]
void Kernel::logSysEvent (const SysEvent & se) virtual
Reimplemented in GuiKernel.
References SysEvent::type(), SysEvent::what(), and SysEvent::when().
Referenced by logSysEvent(), Core::riseError(), and GuiCore::riseError().
processAppArgs()
void Kernel::processAppArgs (const QStringList & args) protected virtual
Reimplemented in GuiKernel, and LCKernel.
References langDir.
Referenced by initialize().
setupTranslators()
QLocale * Kernel::setupTranslators () protected virtual
Reimplemented in LCKernel.
References app, and langDir.
Referenced by initialize().
version()
QString Kernel::version () const protected virtual
Referenced by GuiKernel::usage().
Member Data Documentation
app
QApplication& Kernel::app protected
Referenced by initialize(), and setupTranslators().
appName
QString Kernel::appName protected
cfg
ConfigManager* Kernel::cfg protected
Referenced by Config::Config(), GuiKernel::initialize(), Core::showHelpAtPageChange(), and GuiKernel::windowClosing().
conn
DBConnection* Kernel::conn protected
Referenced by GuiKernel::createDatabase(), Core::databaseConnection(), GuiKernel::fileName4(), and GuiKernel::initialize().
groupID
QString Kernel::groupID protected
langDir
QString Kernel::langDir protected
Referenced by GuiKernel::fileName4(), initialize(), GuiKernel::initialize(), processAppArgs(), GuiKernel::processAppArgs(), and setupTranslators().
locale
QLocale* Kernel::locale protected
Referenced by initialize(), Core::languagePrefix(), and Core::locale().
simulator
bool Kernel::simulator protected
Referenced by GuiKernel::initialize(), Core::isSimulator(), and GuiCore::isSimulator().
timer
QBasicTimer Kernel::timer protected
Referenced by GuiKernel::setupBackend(), and GuiKernel::timerEvent().
The documentation for this class was generated from the following files:
src/baselib/control/kernel.h
src/baselib/control/kernel.cpp