FalconView: ToolModel Class Reference
ToolModel Class Reference
#include <toolmodel.h>
Public Member Functions
ToolModel (DBConnection &conn, QObject *parent=nullptr)
QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const override
bool existsToolNum (int toolNum)
int exportTools ()
QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const override
int maxToolNum ()
int nextId ()
QVariant promptData (int section, int role=Qt::DisplayRole) const
void setCore (GuiCore *core)
void toggleSelection (int row)
int tools4Category (int categoryId)
Static Private Member Functions
static bool createTable ()
Private Attributes
QIcon ci
GuiCore * core
QIcon ui
Constructor & Destructor Documentation
ToolModel()
ToolModel::ToolModel (DBConnection & conn, QObject * parent = nullptr) explicit
References DBConnection::connect().
Member Function Documentation
createTable()
bool ToolModel::createTable () static private
data()
QVariant ToolModel::data (const QModelIndex & index, int role = Qt::DisplayRole) const override
Referenced by toggleSelection().
existsToolNum()
bool ToolModel::existsToolNum (int toolNum)
Referenced by ToolManager::createTool().
exportTools()
int ToolModel::exportTools ()
Referenced by ToolManager::eventFilter().
headerData()
QVariant ToolModel::headerData (int section, Qt::Orientation orientation, int role = Qt::DisplayRole) const override
maxToolNum()
int ToolModel::maxToolNum ()
Referenced by ToolManager::createTool().
nextId()
int ToolModel::nextId ()
Referenced by ToolManager::saveToolChanges().
promptData()
QVariant ToolModel::promptData (int section, int role = Qt::DisplayRole) const
setCore()
void ToolModel::setCore (GuiCore * core)
References core.
Referenced by ToolManager::createContent().
toggleSelection()
void ToolModel::toggleSelection (int row)
References data().
Referenced by ToolManager::eventFilter().
tools4Category()
int ToolModel::tools4Category (int categoryId)
Referenced by ToolManager::deleteCategory().
Member Data Documentation
ci
QIcon ToolModel::ci private
core
GuiCore* ToolModel::core private
Referenced by setCore().
ui
QIcon ToolModel::ui private
The documentation for this class was generated from the following files:
src/nbPages/ToolManager/toolmodel.h
src/nbPages/ToolManager/toolmodel.cpp