FalconView: HelixCurveAdaptor Class Reference
HelixCurveAdaptor Class Reference
#include <HelixCurveAdaptor.h>
Classes
class Evaluator
Base abstract class to evaluate helix.
Public Member Functions
HelixCurveAdaptor (const Geom_HelixData &theData)
Constructor.
HelixCurveAdaptor (const std::shared_ptr< Evaluator > &theEvaluator, double theMin, double theMax)
Constructor.
virtual GeomAbs_Shape Continuity () const override
virtual void D0 (const double U, gp_Pnt &P) const override
virtual void D1 (const double U, gp_Pnt &P, gp_Vec &V) const override
virtual void D2 (const double U, gp_Pnt &P, gp_Vec &V1, gp_Vec &V2) const override
virtual void D3 (const double U, gp_Pnt &P, gp_Vec &V1, gp_Vec &V2, gp_Vec &V3) const override
virtual gp_Vec DN (const double U, const Standard_Integer N) const override
virtual double FirstParameter () const override
virtual GeomAbs_CurveType GetType () const override
virtual Handle (Adaptor3d_Curve) Trim(const double First
virtual void Intervals (TColStd_Array1OfReal &T, const GeomAbs_Shape S) __CADEX_ADAPTOR3D_CURVE_CONST override
virtual Standard_Boolean IsClosed () const override
virtual Standard_Boolean IsPeriodic () const override
virtual double LastParameter () const override
virtual Standard_Integer NbIntervals (const GeomAbs_Shape S) __CADEX_ADAPTOR3D_CURVE_CONST override
virtual double Resolution (const double R3d) const override
virtual gp_Pnt Value (const double U) const override
Public Attributes
virtual const double Last
virtual const double const double Tol const override
Protected Attributes
std::shared_ptr< Evaluator > myEvaluator
double myMax
double myMin
Constructor & Destructor Documentation
HelixCurveAdaptor() [1/2]
HelixCurveAdaptor::HelixCurveAdaptor (const Geom_HelixData & theData)
Constructor.
References myEvaluator, and Geom_HelixData::Taper().
HelixCurveAdaptor() [2/2]
HelixCurveAdaptor::HelixCurveAdaptor (const std::shared_ptr< Evaluator > & theEvaluator, double theMin, double theMax)
Constructor.
Used when trimming
References myEvaluator.
Member Function Documentation
Continuity()
GeomAbs_Shape HelixCurveAdaptor::Continuity () const override virtual
Referenced by HHelixCurveAdaptor::Continuity().
D0()
virtual void HelixCurveAdaptor::D0 (const double U, gp_Pnt & P) const override virtual
D1()
virtual void HelixCurveAdaptor::D1 (const double U, gp_Pnt & P, gp_Vec & V) const override virtual
D2()
virtual void HelixCurveAdaptor::D2 (const double U, gp_Pnt & P, gp_Vec & V1, gp_Vec & V2) const override virtual
D3()
virtual void HelixCurveAdaptor::D3 (const double U, gp_Pnt & P, gp_Vec & V1, gp_Vec & V2, gp_Vec & V3) const override virtual
DN()
virtual gp_Vec HelixCurveAdaptor::DN (const double U, const Standard_Integer N) const override virtual
FirstParameter()
double HelixCurveAdaptor::FirstParameter () const override virtual
References myMin.
Referenced by HHelixCurveAdaptor::FirstParameter().
GetType()
virtual GeomAbs_CurveType HelixCurveAdaptor::GetType () const override virtual
Handle()
virtual HelixCurveAdaptor::Handle (Adaptor3d_Curve) const virtual
Intervals()
void HelixCurveAdaptor::Intervals (TColStd_Array1OfReal & T, const GeomAbs_Shape S) override virtual
IsClosed()
virtual Standard_Boolean HelixCurveAdaptor::IsClosed () const override virtual
IsPeriodic()
virtual Standard_Boolean HelixCurveAdaptor::IsPeriodic () const override virtual
LastParameter()
double HelixCurveAdaptor::LastParameter () const override virtual
References myMax.
Referenced by HHelixCurveAdaptor::LastParameter().
NbIntervals()
Standard_Integer HelixCurveAdaptor::NbIntervals (const GeomAbs_Shape S) override virtual
Resolution()
virtual double HelixCurveAdaptor::Resolution (const double R3d) const override virtual
Value()
virtual gp_Pnt HelixCurveAdaptor::Value (const double U) const override virtual
Member Data Documentation
Last
virtual const double HelixCurveAdaptor::Last
myEvaluator
std::shared_ptr<Evaluator> HelixCurveAdaptor::myEvaluator protected
Referenced by HelixCurveAdaptor().
myMax
double HelixCurveAdaptor::myMax protected
Referenced by LastParameter().
myMin
double HelixCurveAdaptor::myMin protected
Referenced by FirstParameter().
override
virtual const double const double Tol const HelixCurveAdaptor::override
The documentation for this class was generated from the following files:
src/guiLib/util/HelixCurveAdaptor.h
src/guiLib/util/HelixCurveAdaptor.cpp