FalconView: FileModel Class Reference
FileModel Class Reference
#include <filemodel.h>
Public Member Functions
FileModel (const QVector< QFileInfo > &contacts, QObject *parent=nullptr)
FileModel (QObject *parent=nullptr)
int columnCount (const QModelIndex &parent) const override
QVariant data (const QModelIndex &index, int role) const override
QFileInfo fileInfo (int row) const
Qt::ItemFlags flags (const QModelIndex &index) const override
QVariant headerData (int section, Qt::Orientation orientation, int role) const override
int rowCount (const QModelIndex &parent) const override
void setupModel (const QString &baseDir)
Private Attributes
QVector< QFileInfo > vFiles
Constructor & Destructor Documentation
FileModel() [1/2]
FileModel::FileModel (QObject * parent = nullptr) explicit
FileModel() [2/2]
FileModel::FileModel (const QVector< QFileInfo > & contacts, QObject * parent = nullptr)
Member Function Documentation
columnCount()
int FileModel::columnCount (const QModelIndex & parent) const override
data()
QVariant FileModel::data (const QModelIndex & index, int role) const override
References vFiles.
fileInfo()
QFileInfo FileModel::fileInfo (int row) const
References vFiles.
Referenced by FileManager::eventFilter(), and FileManager::selectionChanged().
flags()
Qt::ItemFlags FileModel::flags (const QModelIndex & index) const override
headerData()
QVariant FileModel::headerData (int section, Qt::Orientation orientation, int role) const override
rowCount()
int FileModel::rowCount (const QModelIndex & parent) const override
References vFiles.
setupModel()
void FileModel::setupModel (const QString & baseDir)
References vFiles.
Referenced by FileManager::currentChanged().
Member Data Documentation
vFiles
QVector<QFileInfo> FileModel::vFiles private
Referenced by data(), fileInfo(), rowCount(), and setupModel().
The documentation for this class was generated from the following files:
src/baselib/model/filemodel.h
src/baselib/model/filemodel.cpp