FalconView: JogButton Class Reference
JogButton Class Reference
#include <jogbutton.h>
Public Slots
void pressed ()
void released ()
void toggled (bool checked)
Public Member Functions
JogButton (QWidget *parent=nullptr)
virtual ~JogButton ()
void init (JogButton *counterPart)
Private Attributes
JogButton * counterPart
QIcon icoActive
QIcon icoDefault
Constructor & Destructor Documentation
JogButton()
JogButton::JogButton (QWidget * parent = nullptr) explicit
References pressed(), released(), and toggled().
~JogButton()
JogButton::~JogButton () virtual
Member Function Documentation
init()
void JogButton::init (JogButton * counterPart)
References counterPart, icoActive, and icoDefault.
pressed
void JogButton::pressed () slot
References counterPart, and icoActive.
Referenced by JogButton().
released
void JogButton::released () slot
References icoDefault.
Referenced by JogButton().
toggled
void JogButton::toggled (bool checked) slot
References counterPart.
Referenced by JogButton().
Member Data Documentation
counterPart
JogButton* JogButton::counterPart private
Referenced by init(), pressed(), and toggled().
icoActive
QIcon JogButton::icoActive private
Referenced by init(), and pressed().
icoDefault
QIcon JogButton::icoDefault private
Referenced by init(), and released().
The documentation for this class was generated from the following files:
src/guiLib/view/jogbutton.h
src/guiLib/view/jogbutton.cpp