FalconView: HelpContentWidget Class Reference
HelpContentWidget Class Reference
#include <helpcontentwidget.h>
Public Member Functions
HelpContentWidget (QWidget *parent=nullptr)
virtual ~HelpContentWidget ()
void parse (const QByteArray &ba, QMap< QString, QString > &pages)
void setFolderIcon (const QIcon &ico)
void setHelpIcon (const QIcon &ico)
void setPageIcon (const QIcon &ico)
void sourceChanged (const QUrl &src)
Protected Member Functions
void checkNode (QTreeWidgetItem *node, const QUrl &src)
QTreeWidgetItem * createItem (const QDomElement &e, QMap< QString, QString > &pages, QTreeWidgetItem *parent)
void processAttributes (const QDomElement &e, QMap< QString, QString > &pages, QTreeWidgetItem *item)
void processChildren (const QDomElement &e, QMap< QString, QString > &pages, QTreeWidgetItem *parentItem=nullptr)
QTreeWidgetItem * processElement (const QDomElement &e, QMap< QString, QString > &pages, QTreeWidgetItem *parent)
Private Attributes
QIcon folderIcon
QIcon helpIcon
int level
QIcon pageIcon
Constructor & Destructor Documentation
HelpContentWidget()
HelpContentWidget::HelpContentWidget (QWidget * parent = nullptr) explicit
~HelpContentWidget()
HelpContentWidget::~HelpContentWidget () virtual
Member Function Documentation
checkNode()
void HelpContentWidget::checkNode (QTreeWidgetItem * node, const QUrl & src) protected
Referenced by sourceChanged().
createItem()
QTreeWidgetItem * HelpContentWidget::createItem (const QDomElement & e, QMap< QString, QString > & pages, QTreeWidgetItem * parent) protected
References folderIcon, pageIcon, and processAttributes().
Referenced by processElement().
parse()
void HelpContentWidget::parse (const QByteArray & ba, QMap< QString, QString > & pages)
References level, and processChildren().
Referenced by HelpEngine::HelpEngine().
processAttributes()
void HelpContentWidget::processAttributes (const QDomElement & e, QMap< QString, QString > & pages, QTreeWidgetItem * item) protected
Referenced by createItem().
processChildren()
void HelpContentWidget::processChildren (const QDomElement & e, QMap< QString, QString > & pages, QTreeWidgetItem * parentItem = nullptr) protected
References level, and processElement().
Referenced by parse(), and processElement().
processElement()
QTreeWidgetItem * HelpContentWidget::processElement (const QDomElement & e, QMap< QString, QString > & pages, QTreeWidgetItem * parent) protected
References createItem(), and processChildren().
Referenced by processChildren().
setFolderIcon()
void HelpContentWidget::setFolderIcon (const QIcon & ico)
References folderIcon.
Referenced by HelpEngine::HelpEngine().
setHelpIcon()
void HelpContentWidget::setHelpIcon (const QIcon & ico)
References helpIcon.
setPageIcon()
void HelpContentWidget::setPageIcon (const QIcon & ico)
References pageIcon.
Referenced by HelpEngine::HelpEngine().
sourceChanged()
void HelpContentWidget::sourceChanged (const QUrl & src)
References checkNode().
Referenced by HelpView::sourceChanged().
Member Data Documentation
folderIcon
QIcon HelpContentWidget::folderIcon private
Referenced by createItem(), and setFolderIcon().
helpIcon
QIcon HelpContentWidget::helpIcon private
Referenced by setHelpIcon().
level
int HelpContentWidget::level private
Referenced by parse(), and processChildren().
pageIcon
QIcon HelpContentWidget::pageIcon private
Referenced by createItem(), and setPageIcon().
The documentation for this class was generated from the following files:
src/guiLib/view/helpcontentwidget.h
src/guiLib/view/helpcontentwidget.cpp