FalconView: OcctQtViewer Class Reference
OcctQtViewer Class Reference
OCCT 3D View.
#include <occtviewer.h>
Public Member Functions
OcctQtViewer (bool statusInPreview, bool verbose=false, QWidget *theParent=nullptr)
virtual ~OcctQtViewer ()
void addPlugin (AbstractCenterWidget *acw)
void backView ()
void fitAll ()
void frontView ()
const QString & getGlInfo ()
void isoView ()
void leftView ()
virtual QSize minimumSizeHint () const override
void rightView ()
void setBounds (const Bnd_Box &bounds)
virtual QSize sizeHint () const override
void topView ()
Protected Member Functions
virtual void closeEvent (QCloseEvent *e) override
virtual void createDecorations ()
const Handle (AIS_InteractiveContext) &context() const
Handle (AIS_Shape) cone()
Handle (AIS_ViewCube) cube() const
const Handle (V3d_View) &view() const
const Handle (V3d_Viewer) &viewer() const
virtual void initializeGL () override
virtual void mouseMoveEvent (QMouseEvent *e) override
virtual void mousePressEvent (QMouseEvent *e) override
virtual void mouseReleaseEvent (QMouseEvent *e) override
virtual void paintGL () override
virtual void wheelEvent (QWheelEvent *e) override
Private Member Functions
void dumpGlInfo (bool theIsBasic)
Handle (AIS_InteractiveContext) myContext
Handle (AIS_Shape) myCone
Handle (AIS_ViewCube) myViewCube
Handle (V3d_View) myView
Handle (V3d_Viewer) myViewer
virtual void handleViewRedraw (const Handle(AIS_InteractiveContext)&theCtx, const Handle(V3d_View)&theView) override
Request widget paintGL() event.
void updateView ()
Private Attributes
CurCodesStatus * ccStat
Bnd_Box myBounds
QString myGlInfo
bool myIsCoreProfile
QMap< QString, AbstractCenterWidget * > plugins
PositionStatus * posStat
SpeedStatus * speedStat
bool statusInPreview
ToolStatus * toolStat
bool verbose
Detailed Description
OCCT 3D View.
Constructor & Destructor Documentation
OcctQtViewer()
OcctQtViewer::OcctQtViewer (bool statusInPreview, bool verbose = false, QWidget * theParent = nullptr)
References Handle(), and myIsCoreProfile.
~OcctQtViewer()
OcctQtViewer::~OcctQtViewer () virtual
Member Function Documentation
addPlugin()
void OcctQtViewer::addPlugin (AbstractCenterWidget * acw)
References plugins.
Referenced by MainWindow::createDockables().
backView()
void OcctQtViewer::backView ()
References fitAll().
Referenced by MainWindow::createConnections(), and PreViewEditor::eventFilter().
closeEvent()
void OcctQtViewer::closeEvent (QCloseEvent * e) override protected virtual
createDecorations()
void OcctQtViewer::createDecorations () protected virtual
References plugins, and statusInPreview.
Referenced by initializeGL().
dumpGlInfo()
void OcctQtViewer::dumpGlInfo (bool theIsBasic) private
References myGlInfo.
Referenced by getGlInfo(), and initializeGL().
fitAll()
void OcctQtViewer::fitAll ()
References myBounds.
Referenced by backView(), PreViewEditor::eventFilter(), frontView(), isoView(), leftView(), rightView(), PreViewEditor::showEvent(), Ally3D::showPath(), and topView().
frontView()
void OcctQtViewer::frontView ()
References fitAll().
Referenced by MainWindow::createConnections(), and PreViewEditor::eventFilter().
getGlInfo()
const QString & OcctQtViewer::getGlInfo ()
References dumpGlInfo(), and myGlInfo.
Referenced by MainWindow::about().
Handle() [1/10]
const OcctQtViewer::Handle (AIS_InteractiveContext) const & inline protected
Handle() [2/10]
OcctQtViewer::Handle (AIS_InteractiveContext) private
Handle() [3/10]
OcctQtViewer::Handle (AIS_Shape) inline protected
Handle() [4/10]
OcctQtViewer::Handle (AIS_Shape) private
Handle() [5/10]
OcctQtViewer::Handle (AIS_ViewCube) const inline protected
Handle() [6/10]
OcctQtViewer::Handle (AIS_ViewCube) private
Handle() [7/10]
const OcctQtViewer::Handle (V3d_View) const & inline protected
Handle() [8/10]
OcctQtViewer::Handle (V3d_View) private
Handle() [9/10]
const OcctQtViewer::Handle (V3d_Viewer) const & inline protected
Referenced by OcctQtViewer(), initializeGL(), and paintGL().
Handle() [10/10]
OcctQtViewer::Handle (V3d_Viewer) private
handleViewRedraw()
void OcctQtViewer::handleViewRedraw (const Handle(AIS_InteractiveContext)& theCtx, const Handle(V3d_View)& theView) override private virtual
Request widget paintGL() event.
References updateView().
initializeGL()
void OcctQtViewer::initializeGL () override protected virtual
References createDecorations(), dumpGlInfo(), Handle(), myIsCoreProfile, statusInPreview, and verbose.
isoView()
void OcctQtViewer::isoView ()
References fitAll().
Referenced by MainWindow::createConnections(), and PreViewEditor::eventFilter().
leftView()
void OcctQtViewer::leftView ()
References fitAll().
Referenced by MainWindow::createConnections(), and PreViewEditor::eventFilter().
minimumSizeHint()
virtual QSize OcctQtViewer::minimumSizeHint () const inline override virtual
mouseMoveEvent()
void OcctQtViewer::mouseMoveEvent (QMouseEvent * e) override protected virtual
References updateView().
mousePressEvent()
void OcctQtViewer::mousePressEvent (QMouseEvent * e) override protected virtual
References updateView().
mouseReleaseEvent()
void OcctQtViewer::mouseReleaseEvent (QMouseEvent * e) override protected virtual
References updateView().
paintGL()
void OcctQtViewer::paintGL () override protected virtual
References Handle().
rightView()
void OcctQtViewer::rightView ()
References fitAll().
Referenced by MainWindow::createConnections(), and PreViewEditor::eventFilter().
setBounds()
void OcctQtViewer::setBounds (const Bnd_Box & bounds)
References myBounds.
Referenced by Ally3D::showPath().
sizeHint()
virtual QSize OcctQtViewer::sizeHint () const inline override virtual
topView()
void OcctQtViewer::topView ()
References fitAll().
Referenced by MainWindow::createConnections(), and PreViewEditor::eventFilter().
updateView()
void OcctQtViewer::updateView () private
Referenced by handleViewRedraw(), mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), and wheelEvent().
wheelEvent()
void OcctQtViewer::wheelEvent (QWheelEvent * e) override protected virtual
References updateView().
Member Data Documentation
ccStat
CurCodesStatus* OcctQtViewer::ccStat private
myBounds
Bnd_Box OcctQtViewer::myBounds private
Referenced by fitAll(), and setBounds().
myGlInfo
QString OcctQtViewer::myGlInfo private
Referenced by dumpGlInfo(), and getGlInfo().
myIsCoreProfile
bool OcctQtViewer::myIsCoreProfile private
Referenced by OcctQtViewer(), and initializeGL().
plugins
QMap<QString, AbstractCenterWidget*> OcctQtViewer::plugins private
Referenced by addPlugin(), and createDecorations().
posStat
PositionStatus* OcctQtViewer::posStat private
speedStat
SpeedStatus* OcctQtViewer::speedStat private
statusInPreview
bool OcctQtViewer::statusInPreview private
Referenced by createDecorations(), and initializeGL().
toolStat
ToolStatus* OcctQtViewer::toolStat private
verbose
bool OcctQtViewer::verbose private
Referenced by initializeGL().
The documentation for this class was generated from the following files:
src/guiLib/view/occtviewer.h
src/guiLib/view/occtviewer.cpp