FalconView: LcProperties Class Reference
LcProperties Class Reference
The LcProperties class process ini-files from linuxcnc.
#include <lcproperties.h>
Public Member Functions
LcProperties (const LcProperties &&other)
LcProperties (const QString &fileName=QString())
QString baseDir () const
void dump ()
QString fileName () const
QString getPath (const QString &groupID, const QString &name) const
LcProperties & operator= (const LcProperties &&other)
QString parameterFileName () const
QString toolImageDir () const
QString toolTableFileName () const
QVariant value (const QString &groupID, const QString &name) const
Protected Member Functions
void addGroup (const QString &groupID)
void addValue (const QString &name, const QVariant &value)
void processFile (QFile &file)
void processLine (const QString &line)
Private Attributes
QMap< QString, QVariant > * curMap
QFileInfo fn
QMap< QString, QMap< QString, QVariant > > properties
Detailed Description
The LcProperties class process ini-files from linuxcnc.
Constructor & Destructor Documentation
LcProperties() [1/2]
LcProperties::LcProperties (const QString & fileName = QString()) explicit
References fileName(), and processFile().
LcProperties() [2/2]
LcProperties::LcProperties (const LcProperties && other) explicit
Member Function Documentation
addGroup()
void LcProperties::addGroup (const QString & groupID) protected
References curMap, and properties.
Referenced by processLine().
addValue()
void LcProperties::addValue (const QString & name, const QVariant & value) protected
References curMap, and value().
Referenced by processLine().
baseDir()
QString LcProperties::baseDir () const inline
References fn.
Referenced by CanonIFSettings::CanonIFSettings(), and getPath().
dump()
void LcProperties::dump ()
References properties.
fileName()
QString LcProperties::fileName () const inline
References fn.
Referenced by LcProperties().
getPath()
QString LcProperties::getPath (const QString & groupID, const QString & name) const
References baseDir(), and value().
Referenced by GuiKernel::initialize(), parameterFileName(), toolImageDir(), and toolTableFileName().
operator=()
LcProperties & LcProperties::operator= (const LcProperties && other)
References curMap, and properties.
parameterFileName()
QString LcProperties::parameterFileName () const
References getPath().
Referenced by CanonIF::parameterFilename().
processFile()
void LcProperties::processFile (QFile & file) protected
References processLine().
Referenced by LcProperties().
processLine()
void LcProperties::processLine (const QString & line) protected
References addGroup(), addValue(), and value().
Referenced by processFile().
toolImageDir()
QString LcProperties::toolImageDir () const
References getPath().
Referenced by ToolTable::processFile().
toolTableFileName()
QString LcProperties::toolTableFileName () const
References getPath().
Referenced by GuiKernel::fileName4(), and GuiKernel::initialize().
value()
QVariant LcProperties::value (const QString & groupID, const QString & name) const
References properties.
Referenced by CanonIFSettings::CanonIFSettings(), addValue(), GuiKernel::defaultVelocity(), getPath(), GuiKernel::initialize(), GuiKernel::isLatheMode(), LCInterface::machineLimits(), GuiKernel::machineLimits(), GuiKernel::maxVelocity(), LCInterface::parseInline(), and processLine().
Member Data Documentation
curMap
QMap<QString, QVariant>* LcProperties::curMap private
Referenced by addGroup(), addValue(), and operator=().
fn
QFileInfo LcProperties::fn private
Referenced by baseDir(), and fileName().
properties
QMap<QString, QMap<QString, QVariant> > LcProperties::properties private
Referenced by addGroup(), dump(), operator=(), and value().
The documentation for this class was generated from the following files:
src/app/LC/lcproperties.h
src/app/LC/lcproperties.cpp