FalconView: src/guiLib/util/graphicfactory.cpp File Reference
graphicfactory.cpp File Reference
#include "graphicfactory.h"
#include <cassert>
#include <QVector3D>
#include <QDebug>
#include <AIS_ColoredShape.hxx>
#include <gp_Circ.hxx>
#include <Geom_Line.hxx>
#include <Geom_Circle.hxx>
#include <Geom_BSplineCurve.hxx>
#include <Geom_HelixData.h>
#include <Geom2d_TrimmedCurve.hxx>
#include <GC_MakeArcOfCircle.hxx>
#include <GC_MakeArcOfEllipse.hxx>
#include <GC_MakeCircle.hxx>
#include <gce_MakeDir.hxx>
#include <gce_MakeElips.hxx>
#include <TopoDS_Edge.hxx>
#include <BRepBuilderAPI_MakeEdge.hxx>
#include <BRepBuilderAPI_Transform.hxx>
Functions
Handle (AIS_Shape) GraphicFactory
Variables
double const MIN_DELTA = 0.001
Function Documentation
Handle()
Handle (AIS_Shape)
References GraphicFactory::Handle(), and GraphicFactory::to.
Referenced by ARC_FEED(), Geom_HelixData::MakeHelix(), STRAIGHT_FEED(), and STRAIGHT_TRAVERSE().
Variable Documentation
MIN_DELTA
double const MIN_DELTA = 0.001