#!/bin/bash
project=FalconView

qdoc ${project}.qdocconf
cp ${project}.qhp html
cd html
cp ../src/images/{fold,help-inf}*.* images
zip -u9 ../FalconView.qzh *.html images/* FalconView.qhp
cp -a ../FalconView.qzh .
