#!/bin/bash
project=FalconView
extIN=md
extOut=html

for i in $(ls src/*.$extIN)
do
  t=html${i#src}
  d=${t%.$extIN}.$extOut
  cat $i | gfm | fixhtml -e htmlEntities.def > $d
done
cd src
images=`grep -Ro -P "\(images/(.*)\)" | sed 's%.*(images/%%' | sed 's%)%%'`
cd ..
cp ${project}.qhp html
mkdir html/images 2>/dev/null
# add images from HelpEngine
# folder.svg
# folder-open.svg
# help-about.svg
for i in $images
do
  echo $i
  cp src/images/$i html/images
done
cd html
zip -u9 ../FalconView.qzh *.html images/* FalconView.qhp
cp -a ../FalconView.qzh .
